# Generated by Django 5.1.3 on 2024-12-07 22:36

import auto_prefetch
import codebase.sites.models
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("articles", "0001_initial"),
        ("base", "0001_initial"),
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allow_translation", models.BooleanField(default=False)),
                ("override_translated_fields", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=50, verbose_name="display name")),
                ("remarks", models.TextField(blank=True, null=True)),
                ("emoji", models.CharField(max_length=8, null=True)),
                ("emoji_in_brand", models.BooleanField(default=True)),
                ("page_title", models.CharField(max_length=64, null=True)),
                ("page_title_en", models.CharField(max_length=64, null=True)),
                ("page_title_de", models.CharField(max_length=64, null=True)),
                ("page_title_es", models.CharField(max_length=64, null=True)),
                ("page_title_fr", models.CharField(max_length=64, null=True)),
                ("page_title_el", models.CharField(max_length=64, null=True)),
                ("page_title_eo", models.CharField(max_length=64, null=True)),
                ("page_title_fi", models.CharField(max_length=64, null=True)),
                ("page_title_it", models.CharField(max_length=64, null=True)),
                ("page_title_nl", models.CharField(max_length=64, null=True)),
                ("page_title_nn", models.CharField(max_length=64, null=True)),
                ("page_title_pl", models.CharField(max_length=64, null=True)),
                ("page_title_pt", models.CharField(max_length=64, null=True)),
                ("page_title_pt_br", models.CharField(max_length=64, null=True)),
                ("page_title_ru", models.CharField(max_length=64, null=True)),
                ("page_title_sk", models.CharField(max_length=64, null=True)),
                ("page_title_sl", models.CharField(max_length=64, null=True)),
                ("page_title_sq", models.CharField(max_length=64, null=True)),
                ("page_title_sr", models.CharField(max_length=64, null=True)),
                ("page_title_sv", models.CharField(max_length=64, null=True)),
                ("page_title_tr", models.CharField(max_length=64, null=True)),
                ("page_title_uk", models.CharField(max_length=64, null=True)),
                ("page_description", models.TextField(max_length=256, null=True)),
                ("page_description_en", models.TextField(max_length=256, null=True)),
                ("page_description_de", models.TextField(max_length=256, null=True)),
                ("page_description_es", models.TextField(max_length=256, null=True)),
                ("page_description_fr", models.TextField(max_length=256, null=True)),
                ("page_description_el", models.TextField(max_length=256, null=True)),
                ("page_description_eo", models.TextField(max_length=256, null=True)),
                ("page_description_fi", models.TextField(max_length=256, null=True)),
                ("page_description_it", models.TextField(max_length=256, null=True)),
                ("page_description_nl", models.TextField(max_length=256, null=True)),
                ("page_description_nn", models.TextField(max_length=256, null=True)),
                ("page_description_pl", models.TextField(max_length=256, null=True)),
                ("page_description_pt", models.TextField(max_length=256, null=True)),
                ("page_description_pt_br", models.TextField(max_length=256, null=True)),
                ("page_description_ru", models.TextField(max_length=256, null=True)),
                ("page_description_sk", models.TextField(max_length=256, null=True)),
                ("page_description_sl", models.TextField(max_length=256, null=True)),
                ("page_description_sq", models.TextField(max_length=256, null=True)),
                ("page_description_sr", models.TextField(max_length=256, null=True)),
                ("page_description_sv", models.TextField(max_length=256, null=True)),
                ("page_description_tr", models.TextField(max_length=256, null=True)),
                ("page_description_uk", models.TextField(max_length=256, null=True)),
                ("page_keywords", models.TextField(max_length=128, null=True)),
                ("page_keywords_en", models.TextField(max_length=128, null=True)),
                ("page_keywords_de", models.TextField(max_length=128, null=True)),
                ("page_keywords_es", models.TextField(max_length=128, null=True)),
                ("page_keywords_fr", models.TextField(max_length=128, null=True)),
                ("page_keywords_el", models.TextField(max_length=128, null=True)),
                ("page_keywords_eo", models.TextField(max_length=128, null=True)),
                ("page_keywords_fi", models.TextField(max_length=128, null=True)),
                ("page_keywords_it", models.TextField(max_length=128, null=True)),
                ("page_keywords_nl", models.TextField(max_length=128, null=True)),
                ("page_keywords_nn", models.TextField(max_length=128, null=True)),
                ("page_keywords_pl", models.TextField(max_length=128, null=True)),
                ("page_keywords_pt", models.TextField(max_length=128, null=True)),
                ("page_keywords_pt_br", models.TextField(max_length=128, null=True)),
                ("page_keywords_ru", models.TextField(max_length=128, null=True)),
                ("page_keywords_sk", models.TextField(max_length=128, null=True)),
                ("page_keywords_sl", models.TextField(max_length=128, null=True)),
                ("page_keywords_sq", models.TextField(max_length=128, null=True)),
                ("page_keywords_sr", models.TextField(max_length=128, null=True)),
                ("page_keywords_sv", models.TextField(max_length=128, null=True)),
                ("page_keywords_tr", models.TextField(max_length=128, null=True)),
                ("page_keywords_uk", models.TextField(max_length=128, null=True)),
                (
                    "picocss_color",
                    models.CharField(
                        choices=[
                            ("amber", "Amber"),
                            ("blue", "Blue"),
                            ("fuchsia", "Fuchsia"),
                            ("jade", "Jade"),
                            ("grey", "Grey"),
                            ("purple", "Purple"),
                            ("cyan", "Cyan"),
                            ("red", "Read"),
                            ("violet", "Violet"),
                            ("indigo", "Indigo"),
                            ("slate", "Slate"),
                            ("lime", "Lime"),
                            ("colors", "Colors"),
                            ("orange", "Orange"),
                            ("pumpkin", "Pumpkin"),
                            ("zinc", "Zinc"),
                            ("sand", "Sand"),
                            ("yellow", "Yellow"),
                            ("pink", "Pink"),
                            ("green", "Green"),
                        ],
                        default="orange",
                        max_length=16,
                    ),
                ),
                ("footer_links_separator", models.CharField(default="|", max_length=4)),
                ("change_theme_light_in_footer", models.BooleanField(default=True)),
                ("change_theme_light_in_navbar", models.BooleanField(default=True)),
                ("change_language_in_navbar", models.BooleanField(default=True)),
                ("change_language_in_footer", models.BooleanField(default=True)),
                ("last_huey_flush", models.DateTimeField(null=True)),
                ("has_user_home", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "article_folders",
                    models.ManyToManyField(to="articles.articlessubmodule"),
                ),
                (
                    "default_language",
                    auto_prefetch.ForeignKey(
                        default="en",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="sites_with_default_languages",
                        to="base.language",
                        verbose_name="Default language",
                    ),
                ),
                ("page_folders", models.ManyToManyField(to="pages.pagessubmodule")),
                (
                    "rest_languages",
                    models.ManyToManyField(
                        related_name="sites_with_rest_languages",
                        to="base.language",
                        verbose_name="Rest of languages",
                    ),
                ),
            ],
            options={
                "verbose_name": "site",
                "verbose_name_plural": "sites",
                "ordering": ["domain__id"],
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", codebase.sites.models.SiteManager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            codebase.sites.models._simple_domain_name_validator
                        ],
                        verbose_name="domain name",
                    ),
                ),
                (
                    "site",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.site"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
