# Generated by Django 5.1.3 on 2024-12-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_site_options_rename_id_domain_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="is_main",
            field=models.BooleanField(default=True),
        ),
    ]
