# Generated by Django 5.1.4 on 2024-12-09 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0003_domain_is_main"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="site",
            name="page_description_eo",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_description_fi",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_description_nn",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_description_sq",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_description_sr",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_eo",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_fi",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_nn",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_sq",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_sr",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_title_eo",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_title_fi",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_title_nn",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_title_sq",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_title_sr",
        ),
    ]
