# Generated by Django 5.1.4 on 2024-12-09 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0004_remove_site_page_description_eo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="site",
            name="page_description_pt_br",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_pt_br",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_title_pt_br",
        ),
    ]
