# Generated by Django 5.1.4 on 2024-12-09 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0005_remove_site_page_description_pt_br_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="site",
            name="page_description_uk",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_uk",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_title_uk",
        ),
    ]
