# Generated by Django 5.1.4 on 2024-12-21 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0005_site_brand_name_alter_site_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="site",
            name="is_active",
        ),
    ]
