# Generated by Django 5.1.4 on 2024-12-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0006_remove_site_page_description_uk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="page_description_uk",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_keywords_uk",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_title_uk",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
