# Generated by Django 5.1.4 on 2024-12-15 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0008_alter_site_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Domain",
            new_name="Host",
        ),
        migrations.AlterModelOptions(
            name="site",
            options={
                "base_manager_name": "prefetch_manager",
                "ordering": ["host__name"],
                "verbose_name": "site",
                "verbose_name_plural": "sites",
            },
        ),
    ]
