# Generated by Django 5.1.4 on 2024-12-25 07:46

import codebase.sites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0010_alter_site_rest_languages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="host",
            name="name",
            field=models.CharField(
                db_index=True,
                max_length=100,
                primary_key=True,
                serialize=False,
                validators=[codebase.sites.models._simple_domain_name_validator],
                verbose_name="domain name",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="name",
            field=models.CharField(
                db_index=True, max_length=32, unique=True, verbose_name="Name"
            ),
        ),
    ]
