# Generated by Django 5.1.4 on 2024-12-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0013_remove_site_has_user_home_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="site",
            name="allow_translation",
        ),
        migrations.RemoveField(
            model_name="site",
            name="override_translated_fields",
        ),
        migrations.AddField(
            model_name="seo",
            name="allow_translation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="seo",
            name="override_translated_fields",
            field=models.BooleanField(default=False),
        ),
    ]
