# Generated by Django 5.1.4 on 2024-12-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0015_alter_seo_page_description_alter_seo_page_keywords_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="name",
            field=models.CharField(max_length=32, unique=True, verbose_name="Name"),
        ),
    ]
