# Generated by Django 5.1.4 on 2024-12-25 10:34

import codebase.base.utils.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0018_alter_site_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="emoji",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="site",
            name="emoji_in_brand",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="site",
            name="rest_languages",
            field=codebase.base.utils.db_fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("en", "English"),
                        ("de", "German"),
                        ("es", "Spanish"),
                        ("fr", "French"),
                        ("el", "Greek"),
                        ("it", "Italian"),
                        ("nl", "Dutch"),
                        ("pl", "Polish"),
                        ("pt", "Portuguese"),
                        ("ru", "Russian"),
                        ("sk", "Slovak"),
                        ("sl", "Slovenian"),
                        ("sv", "Swedish"),
                        ("tr", "Turkish"),
                        ("uk", "Ukrainian"),
                    ],
                    max_length=4,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
