# Generated by Django 5.2 on 2025-04-26 14:15

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0001_initial"),
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landingpage",
            name="site",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sites.site"
            ),
        ),
    ]
