# Generated by Django 5.2 on 2025-05-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0002_alter_landingpage_site"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faqssection",
            name="categories",
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="is_home",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="slug",
            field=models.SlugField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="slug_de",
            field=models.SlugField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="slug_en",
            field=models.SlugField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="slug_es",
            field=models.SlugField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="slug_fr",
            field=models.SlugField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="slug_it",
            field=models.SlugField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="slug_nl",
            field=models.SlugField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="slug_pt",
            field=models.SlugField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="title",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="title_de",
            field=models.CharField(default="", max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="title_en",
            field=models.CharField(default="", max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="title_es",
            field=models.CharField(default="", max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="title_fr",
            field=models.CharField(default="", max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="title_it",
            field=models.CharField(default="", max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="title_nl",
            field=models.CharField(default="", max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="title_pt",
            field=models.CharField(default="", max_length=128, null=True),
        ),
    ]
