# Generated by Django 5.2 on 2025-05-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faqs", "0003_faq_categories"),
        ("landing", "0003_remove_faqssection_categories_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="faqssection",
            name="categories",
            field=models.ManyToManyField(to="faqs.faqcategory"),
        ),
    ]
