# Generated by Django 5.2 on 2025-05-21 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0006_alter_articlessection_created_on_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="articlessection",
            old_name="show_created_on",
            new_name="show_created_at",
        ),
        migrations.RemoveField(
            model_name="articlessection",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="articlessection",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="benefititem",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="benefititem",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="faqssection",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="faqssection",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="finalctasection",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="finalctasection",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="herosection",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="herosection",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="landingpage",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="landingpage",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="problemsection",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="problemsection",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="solutionsection",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="solutionsection",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="stepactionsection",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="stepactionsection",
            name="updated_on",
        ),
        migrations.AddField(
            model_name="articlessection",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848231, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="articlessection",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848323, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="benefititem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848231, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="benefititem",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848323, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="faqssection",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848231, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="faqssection",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848323, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="finalctasection",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848231, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="finalctasection",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848323, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="herosection",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848231, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="herosection",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848323, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848231, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848323, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="problemsection",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848231, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="problemsection",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848323, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="solutionsection",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848231, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="solutionsection",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848323, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="stepactionsection",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848231, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="stepactionsection",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848323, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
