# Generated by Django 5.2 on 2025-06-15 18:30

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_link"),
        ("landing", "0009_alter_articlessection_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finalctasection",
            name="cta_link",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="base.link",
            ),
        ),
        migrations.AlterField(
            model_name="herosection",
            name="cta_link",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="base.link",
            ),
        ),
    ]
