default_language_version:
  python: python3.13
  node: 22.14.0

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-xml
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
        exclude: \.py-tpl$
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.6
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/sirwart/ripsecrets
    rev: v0.1.9
    hooks:
      - id: ripsecrets

  - repo: https://github.com/adamchainz/djade-pre-commit
    rev: "1.4.0"
    hooks:
      - id: djade
        args: [--target-version, "5.2"]

  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.24.0"
    hooks:
      - id: django-upgrade
        args: [--target-version, "5.2"]
