[project]
name = "one"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "django",
  "django-auto-prefetch",
  "django-cleanup",
  "django-extensions",
  "django-rosetta",
  "django-o365mail",
  "django-modeltranslation",
  "django-money[exchange]",
  "django-upgrade",
  "django-markdownify",
  "django-storages",
  "django_htmx",
  "django-allauth[socialaccount]",
  "boto3",
  "psycopg",
  "pillow",
  "huey",
  "redis",
  "hiredis",
  "geoip2",
  "Werkzeug",
  "django-browser-reload",
  "docutils",
  "django-debug-toolbar",
  "deepl",
  "Jinja2",
  "qrcode[pil]",
  "Pygments",
  "stripe",
  "python-barcode[images]",
  "django-taggit",
  "python-dotenv",
  "gunicorn",
  "ipython",
  "coverage[toml]",
  "factory-boy",
  "black",
  "pyclean",
  "isort",
  "ruff",
  "djade",
  "djlint",
  "ipdb",
]


[tool.ruff]
exclude = ["venv", "migrations", "submodules"]
line-length = 136

[tool.ruff.lint]
select = [
  # pycodestyle
  "E",
  # Pyflakes
  "F",
  # pyupgrade
  "UP",
  # flake8-bugbear
  "B",
  # flake8-simplify
  "SIM",
  # isort
  "I",
]

[tool.coverage.run]
branch = true
omit = ["manage.py"]
