# Generated by Django 5.1.2 on 2024-10-17 18:49

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="body_de",
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="body_en",
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="body_es",
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="title_de",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="title_en",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="title_es",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
