# Generated by Django 5.1.3 on 2024-11-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlesfolder",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
    ]
