# Generated by Django 5.1.3 on 2024-11-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_initial"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="sites",
            field=models.ManyToManyField(to="sites.site"),
        ),
    ]
