# Generated by Django 5.1.2 on 2024-10-17 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_article_body_de_article_body_en_article_body_es_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="st_ctime",
        ),
        migrations.RemoveField(
            model_name="articlefile",
            name="st_ctime",
        ),
    ]
