# Generated by Django 5.1.3 on 2024-11-16 10:11

import codebase.utils.abstracts
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_articlesfolder_is_premium"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlefile",
            name="file",
            field=models.FileField(upload_to=codebase.utils.abstracts.upload_page_file),
        ),
    ]
