# Generated by Django 5.1.2 on 2024-10-17 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_remove_article_st_ctime_remove_articlefile_st_ctime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="description",
        ),
    ]
