# Generated by Django 5.1.4 on 2024-12-09 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "articles",
            "0005_remove_article_body_pt_br_remove_article_slug_pt_br_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="body_uk",
        ),
        migrations.RemoveField(
            model_name="article",
            name="slug_uk",
        ),
        migrations.RemoveField(
            model_name="article",
            name="title_uk",
        ),
    ]
