# Generated by Django 5.1.3 on 2024-11-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_article_body_fr_article_slug_fr_article_title_fr"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="body_el",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="body_eo",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="body_fi",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="body_it",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="body_nl",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="body_nn",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="body_pl",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="body_pt",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="body_pt_br",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="body_ru",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="body_sk",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="body_sl",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="body_sq",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="body_sr",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="body_sv",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="body_tr",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="body_uk",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="slug_el",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="slug_eo",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="slug_fi",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="slug_it",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="slug_nl",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="slug_nn",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="slug_pl",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="slug_pt",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="slug_pt_br",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="slug_ru",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="slug_sk",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="slug_sl",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="slug_sq",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="slug_sr",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="slug_sv",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="slug_tr",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="slug_uk",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="title_el",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="title_eo",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="title_fi",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="title_it",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="title_nl",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="title_nn",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="title_pl",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="title_pt",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="title_pt_br",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="title_ru",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="title_sk",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="title_sl",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="title_sq",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="title_sr",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="title_sv",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="title_tr",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="title_uk",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
    ]
