# Generated by Django 5.1.3 on 2024-11-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0006_article_body_el_article_body_eo_article_body_fi_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="allow_translation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="article",
            name="override_translated_fields",
            field=models.BooleanField(default=False),
        ),
    ]
