# Generated by Django 5.1.3 on 2024-11-27 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0007_article_allow_translation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="submodule_folder",
        ),
    ]
