# Generated by Django 5.1.4 on 2024-12-16 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0007_article_body_uk_article_slug_uk_article_title_uk"),
        ("sites", "0009_rename_domain_host_alter_site_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ArticlesSubmodule",
            new_name="ArticleParentFolder",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="submodule",
            new_name="parent",
        ),
        migrations.RenameField(
            model_name="articlefile",
            old_name="parent_page",
            new_name="parent",
        ),
    ]
