# Generated by Django 5.1.3 on 2024-11-27 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0009_remove_article_featured_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="allow_translation",
        ),
        migrations.RemoveField(
            model_name="article",
            name="override_translated_fields",
        ),
    ]
