# Generated by Django 5.1.3 on 2024-11-27 21:31

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0011_article_submodule"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlefile",
            name="parent_page",
            field=auto_prefetch.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="articles.article",
            ),
            preserve_default=False,
        ),
    ]
