from django.urls import path
from django.utils.translation import gettext_lazy as _

from .views import (
    CandidateCreateOrEditRedirectView,
    CandidateCreateView,
    CandidateDashboardView,
    CandidateDeleteView,
    CandidateDetailView,
    CandidateEditHxView,
    CandidateEditView,
    CandidateExtraEditHxView,
    CandidatePhotoDeleteHxView,
    CandidatePhotoEditHxView,
    EducationCreateHxView,
    EducationDeleteHxView,
    EducationEditHxView,
    EducationOrderHxView,
    ExperienceCreateHxView,
    ExperienceDeleteHxView,
    ExperienceEditHxView,
    ExperienceOrderHxView,
    JobApplicationDeleteHxView,
    JobApplicationView,
    PubCandidateView,
    RecommendedJobsView,
    SkillCreateHxView,
    SkillDeleteHxView,
    SkillEditHxView,
    SkillOrderHxView,
)

urlpatterns = [
    path(
        "➕",
        CandidateCreateView.as_view(),
        name="candidate_create",
    ),
    path(
        "<uuid:pk>",
        CandidateDetailView.as_view(),
        name="candidate_detail",
    ),
    path(
        "<uuid:pk>/📝",
        CandidateEditView.as_view(),
        name="candidate_edit",
    ),
    path(
        "<uuid:pk>/🗑️",
        CandidateDeleteView.as_view(),
        name="candidate_delete",
    ),
    path(
        "<uuid:pk>/info-edit",
        CandidateEditHxView.as_view(),
        name="candidateinfo_edit",
    ),
    path(
        "<uuid:pk>/extra-edit",
        CandidateExtraEditHxView.as_view(),
        name="candidateextra_edit",
    ),
    path(
        "<uuid:pk>/photo-edit",
        CandidatePhotoEditHxView.as_view(),
        name="candidatephoto_edit",
    ),
    path(
        "<uuid:pk>/photo-delete",
        CandidatePhotoDeleteHxView.as_view(),
        name="candidatephoto_delete",
    ),
    path(
        "<uuid:pk>/pub",
        PubCandidateView.as_view(),
        name="pub_candidate_detail",
    ),
    # Profiles
    path(
        _("dashboard"),
        CandidateDashboardView.as_view(),
        name="candidate_dashboard",
    ),
    path(
        "create-or-edit",
        CandidateCreateOrEditRedirectView.as_view(),
        name="candidate_create_or_edit",
    ),
    # Job apps
    path(
        _("apply"),
        JobApplicationView.as_view(),
        name="job_apply",
    ),
    # Jobs
    path(
        _("recommended-jobs"),
        RecommendedJobsView.as_view(),
        name="candidate_recommended_jobs",
    ),
    path(
        "job-app/<uuid:pk>/delete",
        JobApplicationDeleteHxView.as_view(),
        name="jobapplication_delete",
    ),
    # Skills
    path(
        "skill/<uuid:candidate_pk>/create",
        SkillCreateHxView.as_view(),
        name="candidateskill_create",
    ),
    path(
        "skill/<uuid:candidate_pk>/order",
        SkillOrderHxView.as_view(),
        name="candidateskill_order",
    ),
    path(
        "skill/<uuid:candidate_pk>/<uuid:pk>/delete",
        SkillDeleteHxView.as_view(),
        name="candidateskill_delete",
    ),
    path(
        "skill/<uuid:candidate_pk>/<uuid:pk>/edit",
        SkillEditHxView.as_view(),
        name="candidateskill_edit",
    ),
    # Education
    path(
        "education/<uuid:candidate_pk>/create",
        EducationCreateHxView.as_view(),
        name="candidateeducation_create",
    ),
    path(
        "education/<uuid:candidate_pk>/order",
        EducationOrderHxView.as_view(),
        name="candidateeducation_order",
    ),
    path(
        "education/<uuid:candidate_pk>/<uuid:pk>/delete",
        EducationDeleteHxView.as_view(),
        name="candidateeducation_delete",
    ),
    path(
        "education/<uuid:candidate_pk>/<uuid:pk>/edit",
        EducationEditHxView.as_view(),
        name="candidateeducation_edit",
    ),
    # Experience
    path(
        "experience/<uuid:candidate_pk>/create",
        ExperienceCreateHxView.as_view(),
        name="candidateexperience_create",
    ),
    path(
        "experience/<uuid:candidate_pk>/order",
        ExperienceOrderHxView.as_view(),
        name="candidateexperience_order",
    ),
    path(
        "experience/<uuid:candidate_pk>/<uuid:pk>/delete",
        ExperienceDeleteHxView.as_view(),
        name="candidateexperience_delete",
    ),
    path(
        "experience/<uuid:candidate_pk>/<uuid:pk>/edit",
        ExperienceEditHxView.as_view(),
        name="candidateexperience_edit",
    ),
]
