# Generated by Django 5.0.3 on 2024-03-15 21:16

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_remove_menulistitem_title_en_gb_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dirname", models.CharField(max_length=128, unique=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("de", "German"),
                        ],
                        default="en",
                        max_length=8,
                    ),
                ),
                ("topics", models.ManyToManyField(to="content.topic")),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
