# Generated by Django 5.0.3 on 2024-03-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_listingproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="listingproduct",
            name="image",
            field=models.ImageField(null=True, upload_to="listings"),
        ),
    ]
