# Generated by Django 5.0.3 on 2024-03-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_listingproduct_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productpagefeature",
            name="product_page",
        ),
        migrations.AddField(
            model_name="listingproduct",
            name="slug",
            field=models.SlugField(max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name="ProductPage",
        ),
        migrations.DeleteModel(
            name="ProductPageFeature",
        ),
    ]
