# Generated by Django 5.0.3 on 2024-03-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_listingproduct_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="listingproduct",
            name="promoted",
            field=models.BooleanField(default=False),
        ),
    ]
