# Generated by Django 5.0.3 on 2024-03-17 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_listingproduct_promoted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listingproduct",
            name="slug",
        ),
    ]
