# Generated by Django 5.0.3 on 2024-03-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "content",
            "0011_listingproduct_created_on_listingproduct_updated_on_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="listing_tag",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="listingproduct",
            name="public",
            field=models.BooleanField(default=False),
        ),
    ]
