# Generated by Django 5.0.3 on 2024-03-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0013_alter_topic_slug_alter_topic_slug_de_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="slug",
            field=models.SlugField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="topic",
            name="slug_de",
            field=models.SlugField(max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="topic",
            name="slug_en",
            field=models.SlugField(max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="topic",
            name="slug_es",
            field=models.SlugField(max_length=32, null=True, unique=True),
        ),
    ]
