# Generated by Django 5.0.4 on 2024-04-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0014_alter_topic_slug_alter_topic_slug_de_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField(max_length=1024, verbose_name="Message")),
            ],
        ),
    ]
