# Generated by Django 5.0.4 on 2024-05-09 20:22

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0015_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("name_en", models.CharField(max_length=32, null=True)),
                ("name_es", models.CharField(max_length=32, null=True)),
                ("name_de", models.CharField(max_length=32, null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="listingproduct",
            name="tags",
            field=models.ManyToManyField(to="content.listingtag"),
        ),
    ]
