# Generated by Django 5.0.4 on 2024-05-09 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0016_listingtag_listingproduct_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="listing_tag",
        ),
    ]
