# Generated by Django 5.1.4 on 2024-12-19 21:39

import pathlib

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_book_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="pdf",
            field=models.FileField(
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/private/",
                    location=pathlib.PurePosixPath("/home/rami/repos/one/private"),
                ),
                upload_to="books/",
            ),
        ),
    ]
