# Generated by Django 5.1.3 on 2024-11-09 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BarChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=32, null=True)),
                ("png", models.ImageField(null=True, upload_to="graphs")),
                ("pdf", models.FileField(null=True, upload_to="graphs")),
                ("svg", models.ImageField(null=True, upload_to="barcodes")),
                ("source", models.TextField(null=True)),
                (
                    "data",
                    models.TextField(verbose_name="Data in format: ItemName ItemValue"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CodabarBarcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("png", models.ImageField(null=True, upload_to="barcodes")),
                ("svg", models.ImageField(null=True, upload_to="barcodes")),
                ("jpg", models.ImageField(null=True, upload_to="barcodes")),
                (
                    "text",
                    models.CharField(
                        max_length=32,
                        validators=[
                            django.core.validators.MinLengthValidator(5),
                            django.core.validators.MaxLengthValidator(32),
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Code128Barcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("png", models.ImageField(null=True, upload_to="barcodes")),
                ("svg", models.ImageField(null=True, upload_to="barcodes")),
                ("jpg", models.ImageField(null=True, upload_to="barcodes")),
                (
                    "text",
                    models.CharField(
                        max_length=32,
                        validators=[
                            django.core.validators.MinLengthValidator(5),
                            django.core.validators.MaxLengthValidator(32),
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Code39Barcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("png", models.ImageField(null=True, upload_to="barcodes")),
                ("svg", models.ImageField(null=True, upload_to="barcodes")),
                ("jpg", models.ImageField(null=True, upload_to="barcodes")),
                (
                    "text",
                    models.CharField(
                        max_length=32,
                        validators=[
                            django.core.validators.MinLengthValidator(5),
                            django.core.validators.MaxLengthValidator(32),
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EAN13Barcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("png", models.ImageField(null=True, upload_to="barcodes")),
                ("svg", models.ImageField(null=True, upload_to="barcodes")),
                ("jpg", models.ImageField(null=True, upload_to="barcodes")),
                (
                    "text",
                    models.CharField(
                        max_length=12,
                        validators=[
                            django.core.validators.MinLengthValidator(12),
                            django.core.validators.MaxLengthValidator(12),
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EAN13GuardBarcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("png", models.ImageField(null=True, upload_to="barcodes")),
                ("svg", models.ImageField(null=True, upload_to="barcodes")),
                ("jpg", models.ImageField(null=True, upload_to="barcodes")),
                (
                    "text",
                    models.CharField(
                        max_length=12,
                        validators=[
                            django.core.validators.MinLengthValidator(12),
                            django.core.validators.MaxLengthValidator(12),
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EAN14Barcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("png", models.ImageField(null=True, upload_to="barcodes")),
                ("svg", models.ImageField(null=True, upload_to="barcodes")),
                ("jpg", models.ImageField(null=True, upload_to="barcodes")),
                (
                    "text",
                    models.CharField(
                        max_length=13,
                        validators=[
                            django.core.validators.MinLengthValidator(13),
                            django.core.validators.MaxLengthValidator(13),
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EAN8Barcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("png", models.ImageField(null=True, upload_to="barcodes")),
                ("svg", models.ImageField(null=True, upload_to="barcodes")),
                ("jpg", models.ImageField(null=True, upload_to="barcodes")),
                (
                    "text",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.MinLengthValidator(7),
                            django.core.validators.MaxLengthValidator(7),
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EAN8GuardBarcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("png", models.ImageField(null=True, upload_to="barcodes")),
                ("svg", models.ImageField(null=True, upload_to="barcodes")),
                ("jpg", models.ImageField(null=True, upload_to="barcodes")),
                (
                    "text",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.MinLengthValidator(7),
                            django.core.validators.MaxLengthValidator(7),
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GanttChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=32, null=True)),
                ("png", models.ImageField(null=True, upload_to="graphs")),
                ("pdf", models.FileField(null=True, upload_to="graphs")),
                ("svg", models.ImageField(null=True, upload_to="barcodes")),
                ("source", models.TextField(null=True)),
                (
                    "data",
                    models.TextField(
                        verbose_name="Data in format (dates as YYYY-MM-DD): TaskName DateStart DateEnd"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GS1_128Barcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("png", models.ImageField(null=True, upload_to="barcodes")),
                ("svg", models.ImageField(null=True, upload_to="barcodes")),
                ("jpg", models.ImageField(null=True, upload_to="barcodes")),
                (
                    "text",
                    models.CharField(
                        max_length=32,
                        validators=[
                            django.core.validators.MinLengthValidator(5),
                            django.core.validators.MaxLengthValidator(32),
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HeatMapChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=32, null=True)),
                ("png", models.ImageField(null=True, upload_to="graphs")),
                ("pdf", models.FileField(null=True, upload_to="graphs")),
                ("svg", models.ImageField(null=True, upload_to="barcodes")),
                ("source", models.TextField(null=True)),
                ("data", models.TextField(verbose_name="Matrix heat")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ISBN10Barcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("png", models.ImageField(null=True, upload_to="barcodes")),
                ("svg", models.ImageField(null=True, upload_to="barcodes")),
                ("jpg", models.ImageField(null=True, upload_to="barcodes")),
                (
                    "text",
                    models.CharField(
                        max_length=32,
                        validators=[
                            django.core.validators.MinLengthValidator(5),
                            django.core.validators.MaxLengthValidator(32),
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ISBN13Barcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("png", models.ImageField(null=True, upload_to="barcodes")),
                ("svg", models.ImageField(null=True, upload_to="barcodes")),
                ("jpg", models.ImageField(null=True, upload_to="barcodes")),
                (
                    "text",
                    models.CharField(
                        max_length=32,
                        validators=[
                            django.core.validators.MinLengthValidator(5),
                            django.core.validators.MaxLengthValidator(32),
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ISSNBarcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("png", models.ImageField(null=True, upload_to="barcodes")),
                ("svg", models.ImageField(null=True, upload_to="barcodes")),
                ("jpg", models.ImageField(null=True, upload_to="barcodes")),
                (
                    "text",
                    models.CharField(
                        max_length=32,
                        validators=[
                            django.core.validators.MinLengthValidator(5),
                            django.core.validators.MaxLengthValidator(32),
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ITFBarcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("png", models.ImageField(null=True, upload_to="barcodes")),
                ("svg", models.ImageField(null=True, upload_to="barcodes")),
                ("jpg", models.ImageField(null=True, upload_to="barcodes")),
                (
                    "text",
                    models.CharField(
                        max_length=32,
                        validators=[
                            django.core.validators.MinLengthValidator(5),
                            django.core.validators.MaxLengthValidator(32),
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JANBarcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("png", models.ImageField(null=True, upload_to="barcodes")),
                ("svg", models.ImageField(null=True, upload_to="barcodes")),
                ("jpg", models.ImageField(null=True, upload_to="barcodes")),
                (
                    "text",
                    models.CharField(
                        max_length=12,
                        validators=[
                            django.core.validators.MinLengthValidator(12),
                            django.core.validators.MaxLengthValidator(12),
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PointDataChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=32, null=True)),
                ("png", models.ImageField(null=True, upload_to="graphs")),
                ("pdf", models.FileField(null=True, upload_to="graphs")),
                ("svg", models.ImageField(null=True, upload_to="barcodes")),
                ("source", models.TextField(null=True)),
                ("data", models.TextField(verbose_name="Data in format: X Y")),
                ("x_label", models.CharField(max_length=32, null=True)),
                ("y_label", models.CharField(max_length=32, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PZNBarcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("png", models.ImageField(null=True, upload_to="barcodes")),
                ("svg", models.ImageField(null=True, upload_to="barcodes")),
                ("jpg", models.ImageField(null=True, upload_to="barcodes")),
                (
                    "text",
                    models.CharField(
                        max_length=32,
                        validators=[
                            django.core.validators.MinLengthValidator(5),
                            django.core.validators.MaxLengthValidator(32),
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=32)),
                ("jpg", models.ImageField(null=True, upload_to="qcodes")),
            ],
        ),
        migrations.CreateModel(
            name="SpiderChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=32, null=True)),
                ("png", models.ImageField(null=True, upload_to="graphs")),
                ("pdf", models.FileField(null=True, upload_to="graphs")),
                ("svg", models.ImageField(null=True, upload_to="barcodes")),
                ("source", models.TextField(null=True)),
                (
                    "labels",
                    models.CharField(
                        max_length=128,
                        null=True,
                        verbose_name="Labels in format: NameAxis1 NameAxis2 NameAxis3...",
                    ),
                ),
                (
                    "data",
                    models.TextField(
                        verbose_name="Data in format: Legend number1 number2 number3..."
                    ),
                ),
                ("fill", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UPCBarcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("png", models.ImageField(null=True, upload_to="barcodes")),
                ("svg", models.ImageField(null=True, upload_to="barcodes")),
                ("jpg", models.ImageField(null=True, upload_to="barcodes")),
                (
                    "text",
                    models.CharField(
                        max_length=32,
                        validators=[
                            django.core.validators.MinLengthValidator(5),
                            django.core.validators.MaxLengthValidator(32),
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
