# Generated by Django 5.2 on 2025-05-06 18:40

import auto_prefetch
import datetime
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0002_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("de", "German"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("pt", "Portuguese"),
                        ],
                        default="de",
                        max_length=8,
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("body", models.TextField()),
                ("job_id", models.CharField(blank=True, max_length=32, null=True)),
                ("source_url", models.URLField(blank=True, max_length=128, null=True)),
                ("duration", models.DurationField(default=datetime.timedelta(days=30))),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("expires_on", models.DateTimeField(editable=False)),
                ("is_active", models.BooleanField(default=True, editable=False)),
                (
                    "company_location",
                    auto_prefetch.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.companylocation",
                    ),
                ),
                (
                    "recruiter",
                    auto_prefetch.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="companies.person",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
                "indexes": [
                    models.Index(
                        condition=models.Q(
                            ("company_location__isnull", False), ("is_active", True)
                        ),
                        fields=["company_location"],
                        name="job_company_location_fkey",
                    ),
                    models.Index(
                        condition=models.Q(
                            ("recruiter__isnull", False), ("is_active", True)
                        ),
                        fields=["recruiter"],
                        name="job_recruiter_fkey",
                    ),
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
