# Generated by Django 5.2 on 2025-05-11 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="duration",
            field=models.DurationField(default=datetime.timedelta(days=60)),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="source_url",
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(max_length=128),
        ),
    ]
