# Generated by Django 5.2 on 2025-05-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0007_company_job_detail_container_class_and_more"),
        ("jobs", "0002_alter_job_body_alter_job_duration_alter_job_job_id_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="job",
            name="job_company_location_fkey",
        ),
        migrations.RemoveField(
            model_name="job",
            name="company_location",
        ),
        migrations.AddField(
            model_name="job",
            name="company_location",
            field=models.ManyToManyField(blank=True, to="companies.companylocation"),
        ),
    ]
