# Generated by Django 5.2 on 2025-05-14 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_remove_job_job_company_location_fkey_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="company_location",
            new_name="company_locations",
        ),
    ]
