# Generated by Django 5.2 on 2025-05-14 21:02

import auto_prefetch
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0007_company_job_detail_container_class_and_more"),
        ("jobs", "0004_rename_company_location_job_company_locations"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="company",
            field=auto_prefetch.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="companies.company",
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                condition=models.Q(("company__isnull", False), ("is_active", True)),
                fields=["company"],
                name="job_company_fkey",
            ),
        ),
    ]
