# Generated by Django 5.2 on 2025-04-26 09:29

import auto_prefetch
import datetime
import django.db.models.deletion
import django.db.models.manager
import one.db
import one.sites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("de", "German"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("pt", "Portuguese"),
                        ],
                        default="en",
                        max_length=4,
                    ),
                ),
                (
                    "languages",
                    one.db.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("en", "English"),
                                ("de", "German"),
                                ("es", "Spanish"),
                                ("fr", "French"),
                                ("it", "Italian"),
                                ("nl", "Dutch"),
                                ("pt", "Portuguese"),
                            ],
                            max_length=8,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "site_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("dgt", "DGT"),
                            ("english", "English quizzes"),
                        ],
                        default="standard",
                        max_length=16,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        db_index=True,
                        max_length=32,
                        unique=True,
                        validators=[one.sites.models._simple_domain_name_validator],
                        verbose_name="Name",
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("brand_name", models.CharField(max_length=32, null=True)),
                ("emoji", models.CharField(blank=True, max_length=8, null=True)),
                ("emoji_in_brand", models.BooleanField(blank=True, default=True)),
                (
                    "picocss_color",
                    models.CharField(
                        choices=[
                            ("amber", "Amber"),
                            ("blue", "Blue"),
                            ("fuchsia", "Fuchsia"),
                            ("jade", "Jade"),
                            ("grey", "Grey"),
                            ("purple", "Purple"),
                            ("cyan", "Cyan"),
                            ("red", "Read"),
                            ("violet", "Violet"),
                            ("indigo", "Indigo"),
                            ("slate", "Slate"),
                            ("lime", "Lime"),
                            ("colors", "Colors"),
                            ("orange", "Orange"),
                            ("pumpkin", "Pumpkin"),
                            ("zinc", "Zinc"),
                            ("sand", "Sand"),
                            ("yellow", "Yellow"),
                            ("pink", "Pink"),
                            ("green", "Green"),
                        ],
                        default="pumpkin",
                        max_length=16,
                    ),
                ),
                ("footer_links_separator", models.CharField(default="|", max_length=4)),
                ("footer_text", models.TextField(blank=True, null=True)),
                ("change_theme_light_in_footer", models.BooleanField(default=True)),
                ("change_theme_light_in_navbar", models.BooleanField(default=True)),
                ("change_language_in_navbar", models.BooleanField(default=True)),
                ("change_language_in_footer", models.BooleanField(default=True)),
                (
                    "spam_requests_duration",
                    models.DurationField(default=datetime.timedelta(days=1)),
                ),
                (
                    "requests_duration",
                    models.DurationField(default=datetime.timedelta(days=14)),
                ),
                (
                    "topics",
                    one.db.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("django", "Django"),
                                ("htmx", "htmx"),
                                ("alpinejs", "AlpineJS"),
                                ("devops", "DevOps"),
                                ("python", "Python"),
                                ("linux", "Linux"),
                                ("latex", "LaTex"),
                                ("matlab", "Matlab"),
                                ("siemens", "Siemens"),
                                ("excel", "Excel"),
                                ("maths", "Maths"),
                                ("mechanics", "Mechanics"),
                                ("english", "English"),
                                ("electronics", "Electronics"),
                                ("calendar", "Calendars"),
                            ],
                            max_length=16,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=64, null=True)),
                ("title_en", models.CharField(blank=True, max_length=64, null=True)),
                ("title_de", models.CharField(blank=True, max_length=64, null=True)),
                ("title_es", models.CharField(blank=True, max_length=64, null=True)),
                ("title_fr", models.CharField(blank=True, max_length=64, null=True)),
                ("title_it", models.CharField(blank=True, max_length=64, null=True)),
                ("title_nl", models.CharField(blank=True, max_length=64, null=True)),
                ("title_pt", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=256, null=True),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, max_length=256, null=True),
                ),
                (
                    "description_de",
                    models.TextField(blank=True, max_length=256, null=True),
                ),
                (
                    "description_es",
                    models.TextField(blank=True, max_length=256, null=True),
                ),
                (
                    "description_fr",
                    models.TextField(blank=True, max_length=256, null=True),
                ),
                (
                    "description_it",
                    models.TextField(blank=True, max_length=256, null=True),
                ),
                (
                    "description_nl",
                    models.TextField(blank=True, max_length=256, null=True),
                ),
                (
                    "description_pt",
                    models.TextField(blank=True, max_length=256, null=True),
                ),
                ("keywords", models.TextField(blank=True, max_length=256, null=True)),
                (
                    "keywords_en",
                    models.TextField(blank=True, max_length=256, null=True),
                ),
                (
                    "keywords_de",
                    models.TextField(blank=True, max_length=256, null=True),
                ),
                (
                    "keywords_es",
                    models.TextField(blank=True, max_length=256, null=True),
                ),
                (
                    "keywords_fr",
                    models.TextField(blank=True, max_length=256, null=True),
                ),
                (
                    "keywords_it",
                    models.TextField(blank=True, max_length=256, null=True),
                ),
                (
                    "keywords_nl",
                    models.TextField(blank=True, max_length=256, null=True),
                ),
                (
                    "keywords_pt",
                    models.TextField(blank=True, max_length=256, null=True),
                ),
                (
                    "brand_email_sender",
                    auto_prefetch.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="emails.sender",
                    ),
                ),
                (
                    "noreply_email_sender",
                    auto_prefetch.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="emails.sender",
                    ),
                ),
            ],
            options={
                "verbose_name": "site",
                "verbose_name_plural": "sites",
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", one.sites.models.SiteManager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
