# Generated by Django 5.2 on 2025-07-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="site_type",
            field=models.CharField(
                choices=[
                    ("standard", "Standard"),
                    ("dgt", "DGT"),
                    ("english", "English quizzes"),
                    ("jobapps", "Job applications"),
                ],
                default="standard",
                max_length=16,
            ),
        ),
    ]
