# Generated by Django 5.2 on 2025-05-21 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0003_site_created_on_site_updated_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 17, 9, 777148, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="updated_on",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 17, 9, 777236, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
