# Generated by Django 5.2.4 on 2025-07-25 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0003_alter_site_topics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="site",
            name="keywords",
        ),
        migrations.RemoveField(
            model_name="site",
            name="keywords_de",
        ),
        migrations.RemoveField(
            model_name="site",
            name="keywords_en",
        ),
        migrations.RemoveField(
            model_name="site",
            name="keywords_es",
        ),
        migrations.RemoveField(
            model_name="site",
            name="keywords_fr",
        ),
        migrations.RemoveField(
            model_name="site",
            name="keywords_it",
        ),
        migrations.RemoveField(
            model_name="site",
            name="keywords_nl",
        ),
        migrations.RemoveField(
            model_name="site",
            name="keywords_pt",
        ),
    ]
