# Generated by Django 5.1.4 on 2024-12-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0004_alter_site_rest_languages"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="brand_name",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="site",
            name="name",
            field=models.CharField(max_length=32, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="site",
            name="picocss_color",
            field=models.CharField(
                choices=[
                    ("amber", "Amber"),
                    ("blue", "Blue"),
                    ("fuchsia", "Fuchsia"),
                    ("jade", "Jade"),
                    ("grey", "Grey"),
                    ("purple", "Purple"),
                    ("cyan", "Cyan"),
                    ("red", "Read"),
                    ("violet", "Violet"),
                    ("indigo", "Indigo"),
                    ("slate", "Slate"),
                    ("lime", "Lime"),
                    ("colors", "Colors"),
                    ("orange", "Orange"),
                    ("pumpkin", "Pumpkin"),
                    ("zinc", "Zinc"),
                    ("sand", "Sand"),
                    ("yellow", "Yellow"),
                    ("pink", "Pink"),
                    ("green", "Green"),
                ],
                default="pumpkin",
                max_length=16,
            ),
        ),
    ]
