# Generated by Django 5.1.4 on 2024-12-25 08:21

from django.db import migrations, models

import one.sites.models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0011_alter_host_name_alter_site_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="host",
            name="name",
            field=models.CharField(
                db_index=True,
                max_length=100,
                primary_key=True,
                serialize=False,
                validators=[one.sites.models._simple_domain_name_validator],
                verbose_name="host name",
            ),
        ),
    ]
