# Generated by Django 5.1.4 on 2024-12-25 09:53

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0012_alter_host_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="site",
            name="has_user_home",
        ),
        migrations.RemoveField(
            model_name="site",
            name="last_huey_flush",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_description",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_description_de",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_description_el",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_description_en",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_description_es",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_description_fr",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_description_it",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_description_nl",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_description_pl",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_description_pt",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_description_ru",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_description_sk",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_description_sl",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_description_sv",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_description_tr",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_description_uk",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_de",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_el",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_en",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_es",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_fr",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_it",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_nl",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_pl",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_pt",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_ru",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_sk",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_sl",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_sv",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_tr",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_uk",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_title",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_title_de",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_title_el",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_title_en",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_title_es",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_title_fr",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_title_it",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_title_nl",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_title_pl",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_title_pt",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_title_ru",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_title_sk",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_title_sl",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_title_sv",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_title_tr",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_title_uk",
        ),
        migrations.CreateModel(
            name="Seo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_title", models.CharField(max_length=64, null=True)),
                ("page_title_en", models.CharField(max_length=64, null=True)),
                ("page_title_de", models.CharField(max_length=64, null=True)),
                ("page_title_es", models.CharField(max_length=64, null=True)),
                ("page_title_fr", models.CharField(max_length=64, null=True)),
                ("page_title_el", models.CharField(max_length=64, null=True)),
                ("page_title_it", models.CharField(max_length=64, null=True)),
                ("page_title_nl", models.CharField(max_length=64, null=True)),
                ("page_title_pl", models.CharField(max_length=64, null=True)),
                ("page_title_pt", models.CharField(max_length=64, null=True)),
                ("page_title_ru", models.CharField(max_length=64, null=True)),
                ("page_title_sk", models.CharField(max_length=64, null=True)),
                ("page_title_sl", models.CharField(max_length=64, null=True)),
                ("page_title_sv", models.CharField(max_length=64, null=True)),
                ("page_title_tr", models.CharField(max_length=64, null=True)),
                ("page_title_uk", models.CharField(max_length=64, null=True)),
                ("page_description", models.TextField(max_length=256, null=True)),
                ("page_description_en", models.TextField(max_length=256, null=True)),
                ("page_description_de", models.TextField(max_length=256, null=True)),
                ("page_description_es", models.TextField(max_length=256, null=True)),
                ("page_description_fr", models.TextField(max_length=256, null=True)),
                ("page_description_el", models.TextField(max_length=256, null=True)),
                ("page_description_it", models.TextField(max_length=256, null=True)),
                ("page_description_nl", models.TextField(max_length=256, null=True)),
                ("page_description_pl", models.TextField(max_length=256, null=True)),
                ("page_description_pt", models.TextField(max_length=256, null=True)),
                ("page_description_ru", models.TextField(max_length=256, null=True)),
                ("page_description_sk", models.TextField(max_length=256, null=True)),
                ("page_description_sl", models.TextField(max_length=256, null=True)),
                ("page_description_sv", models.TextField(max_length=256, null=True)),
                ("page_description_tr", models.TextField(max_length=256, null=True)),
                ("page_description_uk", models.TextField(max_length=256, null=True)),
                ("page_keywords", models.TextField(max_length=128, null=True)),
                ("page_keywords_en", models.TextField(max_length=128, null=True)),
                ("page_keywords_de", models.TextField(max_length=128, null=True)),
                ("page_keywords_es", models.TextField(max_length=128, null=True)),
                ("page_keywords_fr", models.TextField(max_length=128, null=True)),
                ("page_keywords_el", models.TextField(max_length=128, null=True)),
                ("page_keywords_it", models.TextField(max_length=128, null=True)),
                ("page_keywords_nl", models.TextField(max_length=128, null=True)),
                ("page_keywords_pl", models.TextField(max_length=128, null=True)),
                ("page_keywords_pt", models.TextField(max_length=128, null=True)),
                ("page_keywords_ru", models.TextField(max_length=128, null=True)),
                ("page_keywords_sk", models.TextField(max_length=128, null=True)),
                ("page_keywords_sl", models.TextField(max_length=128, null=True)),
                ("page_keywords_sv", models.TextField(max_length=128, null=True)),
                ("page_keywords_tr", models.TextField(max_length=128, null=True)),
                ("page_keywords_uk", models.TextField(max_length=128, null=True)),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.site"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
