# Generated by Django 5.1.4 on 2024-12-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0017_alter_site_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="name",
            field=models.CharField(
                db_index=True, max_length=32, unique=True, verbose_name="Name"
            ),
        ),
    ]
