# Generated by Django 5.1.4 on 2024-12-26 11:33

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0019_alter_site_emoji_alter_site_emoji_in_brand_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="requests_duration",
            field=models.DurationField(default=datetime.timedelta(days=14)),
        ),
        migrations.AddField(
            model_name="site",
            name="spammy_requests_duration",
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
