# Generated by Django 5.1.4 on 2024-12-29 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0020_site_requests_duration_site_spammy_requests_duration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="site",
            old_name="spammy_requests_duration",
            new_name="spam_requests_duration",
        ),
    ]
