# Generated by Django 5.1.4 on 2025-01-06 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0021_rename_spammy_requests_duration_site_spam_requests_duration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="site",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "site",
                "verbose_name_plural": "sites",
            },
        ),
    ]
