# Generated by Django 5.1.4 on 2025-01-18 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0022_alter_site_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="site",
            old_name="name",
            new_name="domain",
        ),
    ]
