# Generated by Django 5.1.4 on 2025-01-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0026_alter_seo_languages"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="page_description",
            field=models.TextField(default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="site",
            name="page_description_de",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_description_el",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_description_en",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_description_es",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_description_fr",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_description_it",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_description_nl",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_description_pl",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_description_pt",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_description_ru",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_description_sk",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_description_sl",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_description_sv",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_description_tr",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_description_uk",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_keywords",
            field=models.TextField(default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="site",
            name="page_keywords_de",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_keywords_el",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_keywords_en",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_keywords_es",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_keywords_fr",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_keywords_it",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_keywords_nl",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_keywords_pl",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_keywords_pt",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_keywords_ru",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_keywords_sk",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_keywords_sl",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_keywords_sv",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_keywords_tr",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_keywords_uk",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_title",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="site",
            name="page_title_de",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_title_el",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_title_en",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_title_es",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_title_fr",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_title_it",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_title_nl",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_title_pl",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_title_pt",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_title_ru",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_title_sk",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_title_sl",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_title_sv",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_title_tr",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="page_title_uk",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name="Seo",
        ),
    ]
