# Generated by Django 5.1.4 on 2025-01-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0028_alter_site_rest_languages"),
    ]

    operations = [
        migrations.RenameField(
            model_name="site",
            old_name="rest_languages",
            new_name="languages",
        ),
    ]
