# Generated by Django 5.1 on 2025-03-15 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0029_rename_rest_languages_site_languages"),
    ]

    operations = [
        migrations.RenameField(
            model_name="site",
            old_name="default_language",
            new_name="language",
        ),
    ]
