# Generated by Django 5.1.7 on 2025-03-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_topic_article_folders"),
        ("sites", "0030_rename_default_language_site_language"),
    ]

    operations = [
        migrations.RenameField(
            model_name="site",
            old_name="page_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="page_description_de",
            new_name="description_de",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="page_description_el",
            new_name="description_el",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="page_description_en",
            new_name="description_en",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="page_description_es",
            new_name="description_es",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="page_description_fr",
            new_name="description_fr",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="page_description_it",
            new_name="description_it",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="page_description_nl",
            new_name="description_nl",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="page_description_pl",
            new_name="description_pl",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="page_description_pt",
            new_name="description_pt",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="page_description_ru",
            new_name="description_ru",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="page_description_sk",
            new_name="description_sk",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="page_description_sl",
            new_name="description_sl",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="page_description_sv",
            new_name="description_sv",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="page_description_tr",
            new_name="description_tr",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="page_description_uk",
            new_name="description_uk",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="page_title",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="page_title_de",
            new_name="title_de",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="page_title_el",
            new_name="title_el",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="page_title_en",
            new_name="title_en",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="page_title_es",
            new_name="title_es",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="page_title_fr",
            new_name="title_fr",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="page_title_it",
            new_name="title_it",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="page_title_nl",
            new_name="title_nl",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="page_title_pl",
            new_name="title_pl",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="page_title_pt",
            new_name="title_pt",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="page_title_ru",
            new_name="title_ru",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="page_title_sk",
            new_name="title_sk",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="page_title_sl",
            new_name="title_sl",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="page_title_sv",
            new_name="title_sv",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="page_title_tr",
            new_name="title_tr",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="page_title_uk",
            new_name="title_uk",
        ),
        migrations.RemoveField(
            model_name="site",
            name="article_folders",
        ),
        # migrations.RemoveField(
        #     model_name="site",
        #     name="books",
        # ),
        # migrations.RemoveField(
        #     model_name="site",
        #     name="page_folders",
        # ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_de",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_el",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_en",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_es",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_fr",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_it",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_nl",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_pl",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_pt",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_ru",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_sk",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_sl",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_sv",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_tr",
        ),
        migrations.RemoveField(
            model_name="site",
            name="page_keywords_uk",
        ),
        # migrations.AddField(
        #     model_name="site",
        #     name="topics",
        #     field=models.ManyToManyField(blank=True, to="base.topic"),
        # ),
    ]
