# Generated by Django 5.1 on 2025-03-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0034_site_keywords_alter_site_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="keywords_de",
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="keywords_en",
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="keywords_es",
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="keywords_fr",
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="keywords_it",
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="keywords_nl",
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="keywords_pt",
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
