# Generated by Django 5.2 on 2025-04-14 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0036_site_topics_new"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="site",
        #     name="topics",
        # ),
    ]
