# Generated by Django 5.2 on 2025-04-14 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0037_remove_site_topics"),
    ]

    operations = [
        migrations.RenameField(
            model_name="site",
            old_name="topics_new",
            new_name="topics",
        ),
    ]
