# Generated by Django 5.2 on 2025-04-20 18:43

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0036_replymessage_sender"),
        ("sites", "0038_rename_topics_new_site_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="brand_email_sender",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="emails.sender",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="nonreply_email_sender",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="emails.sender",
            ),
        ),
    ]
