# Generated by Django 5.2 on 2025-04-20 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0039_site_brand_email_sender_site_nonreply_email_sender"),
    ]

    operations = [
        migrations.RenameField(
            model_name="site",
            old_name="nonreply_email_sender",
            new_name="noreply_email_sender",
        ),
    ]
