# Generated by Django 5.2 on 2025-04-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0040_rename_nonreply_email_sender_site_noreply_email_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="footer_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
