# Generated by Django 5.2 on 2025-07-13 08:05

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.text.Concat(
                    "first_name", models.Value(" "), "last_name"
                ),
                output_field=models.CharField(max_length=300),
            ),
        ),
    ]
