# Generated by Django 5.1.4 on 2025-01-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0022_alter_site_options"),
        ("users", "0003_alter_user_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sites",
            field=models.ManyToManyField(blank=True, to="sites.site"),
        ),
    ]
