# Generated by Django 5.1 on 2025-03-30 19:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="possible_spam",
        ),
        migrations.AddField(
            model_name="user",
            name="when_asked_to_verify",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
