# Generated by Django 5.2 on 2025-04-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_user_possible_spam_user_when_asked_to_verify"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="asked_to_verify_email",
            field=models.BooleanField(db_default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="country_code",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en", "English"),
                    ("de", "German"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("it", "Italian"),
                    ("nl", "Dutch"),
                    ("pt", "Portuguese"),
                ],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="when_asked_to_verify",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
