# Generated by Django 5.1.4 on 2025-01-26 05:20

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0005_product_summary_de_product_summary_el_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allow_translation", models.BooleanField(default=False)),
                ("override_translated_fields", models.BooleanField(default=False)),
                ("general_listing_description", models.TextField()),
                ("general_listing_description_en", models.TextField(null=True)),
                ("general_listing_description_de", models.TextField(null=True)),
                ("general_listing_description_es", models.TextField(null=True)),
                ("general_listing_description_fr", models.TextField(null=True)),
                ("general_listing_description_el", models.TextField(null=True)),
                ("general_listing_description_it", models.TextField(null=True)),
                ("general_listing_description_nl", models.TextField(null=True)),
                ("general_listing_description_pl", models.TextField(null=True)),
                ("general_listing_description_pt", models.TextField(null=True)),
                ("general_listing_description_ru", models.TextField(null=True)),
                ("general_listing_description_sk", models.TextField(null=True)),
                ("general_listing_description_sl", models.TextField(null=True)),
                ("general_listing_description_sv", models.TextField(null=True)),
                ("general_listing_description_tr", models.TextField(null=True)),
                ("general_listing_description_uk", models.TextField(null=True)),
                ("products", models.ManyToManyField(blank=True, to="products.product")),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
