# Generated by Django 5.1.4 on 2025-01-26 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0003_alter_shop_languages"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shop",
            old_name="languages",
            new_name="rest_languages",
        ),
    ]
