# Generated by Django 5.1.4 on 2025-01-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0004_rename_languages_shop_rest_languages"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shop",
            old_name="rest_languages",
            new_name="languages",
        ),
    ]
