# Generated by Django 5.2 on 2025-05-23 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0005_remove_app_created_on_remove_app_updated_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="app",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="etsyauth",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="etsyauth",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="listingfile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="listingfile",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="listingimage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="listingimage",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.utils.timezone.now
            ),
        ),
    ]
