# Generated by Django 5.1.4 on 2025-01-28 06:08

import auto_prefetch
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "etsy",
            "0006_rename_general_listing_description_shop_generic_listing_description_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                (
                    "keystring",
                    models.CharField(
                        help_text="An Etsy App API Key keystring for the app.",
                        max_length=256,
                    ),
                ),
                (
                    "redirect_uri",
                    models.URLField(
                        default="https://ramib.ch/etsy/callback",
                        help_text="A callback URL your app uses to receive the authorization code",
                    ),
                ),
                (
                    "scopes",
                    models.CharField(
                        default="listings_d, listings_r, listings_w, profile_r, profile_w, shops_r, shops_w, transactions_r",
                        help_text="The scopes your application requires to use specific endpoints",
                        max_length=256,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="A state string, similar to a strong password, which protects against Cross-site request forgery exploits.",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "code_verifier",
                    models.CharField(
                        blank=True,
                        help_text="A code verifier for code exchange (PKCE)",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="An OAuth authorization code required to request an OAuth token",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "access_token",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "refresh_token",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="listing",
            name="listing_type",
            field=models.CharField(
                choices=[
                    ("physical", "Physical"),
                    ("download", "Download"),
                    ("both", "Both"),
                ],
                default="download",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="shop_id",
            field=models.PositiveIntegerField(
                default=39982277,
                help_text="1. Log in into etsy\n2. Visit your shop at 'https://www.etsy.com/shop/<your-shop>'\n3. View Page Source and search for 'shop_id'",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="overprice_percentage",
            field=models.SmallIntegerField(
                default=150,
                help_text="Percent to apply to Etsy listing price.",
                validators=[
                    django.core.validators.MinValueValidator(50),
                    django.core.validators.MaxValueValidator(300),
                ],
                verbose_name="Price percentace",
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="app",
            field=auto_prefetch.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="etsy.app"
            ),
            preserve_default=False,
        ),
    ]
