# Generated by Django 5.1.4 on 2025-01-28 19:59

from django.db import migrations, models

import one.base.utils.db


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0007_app_listing_listing_type_shop_shop_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shop",
            old_name="overprice_percentage",
            new_name="price_percentage",
        ),
        migrations.AlterField(
            model_name="app",
            name="scopes",
            field=one.base.utils.db.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("address_r", "address_r: see billing and shipping addresses"),
                        (
                            "address_w",
                            "address_w: update billing and shipping addresses",
                        ),
                        ("billing_r", "billing_r: see all billing statement data"),
                        ("cart_r", "cart_r: read shopping carts"),
                        ("cart_w", "cart_w: add/remove from shopping carts"),
                        ("email_r", "email_r: read a user profile"),
                        ("favorites_r", "favorites_r: see private favorites"),
                        ("favorites_w", "favorites_w: add/remove favorites"),
                        ("feedback_r", "feedback_r: see purchase info in feedback"),
                        ("listings_d", "listings_d: delete listings"),
                        ("listings_r", "listings_r: see all listings "),
                        ("listings_w", "listings_w: create/edit listings"),
                        ("profile_r", "profile_r: see all profile data"),
                        ("profile_w", "profile_w: update user profile, avatar, etc."),
                        ("recommend_r", "recommend_r: see recommended listings"),
                        (
                            "recommend_w",
                            "recommend_w: accept/reject recommended listings",
                        ),
                        ("shops_r", "shops_r: see private shop info"),
                        ("shops_w", "shops_w: update shop"),
                        ("transactions_r", "transactions_r: see all payment data"),
                        ("transactions_w", "transactions_w: update receipts"),
                    ],
                    max_length=16,
                ),
                blank=True,
                default=str,
                help_text="The scopes your application requires to use specific endpoints",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="shop_id",
            field=models.PositiveIntegerField(
                default=39982277,
                help_text="1. Log in into etsy. 2. Visit your shop at 'https://www.etsy.com/shop/<your-shop>'. 3. View Page Source and search for 'shop_id'.",
            ),
        ),
    ]
