# Generated by Django 5.1.4 on 2025-01-29 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0009_alter_app_scopes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="quantity",
            field=models.PositiveSmallIntegerField(
                default=999,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999),
                ],
            ),
        ),
    ]
