# Generated by Django 5.1.4 on 2025-01-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0010_alter_listing_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="response",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="name",
            field=models.CharField(default="Shop example", max_length=64),
        ),
    ]
