# Generated by Django 5.1.4 on 2025-01-31 16:44

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0011_listing_response_shop_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="A state string, similar to a strong password, which protects against Cross-site request forgery exploits.",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "code_verifier",
                    models.CharField(
                        blank=True,
                        help_text="A code verifier for code exchange (PKCE)",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="An OAuth authorization code required to request an OAuth token",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "access_token",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "refresh_token",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "app",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="etsy.app"
                    ),
                ),
                (
                    "user",
                    auto_prefetch.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
