# Generated by Django 5.1.4 on 2025-02-01 17:31

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0013_usershopauth_delete_userauth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="app",
            name="access_token",
        ),
        migrations.RemoveField(
            model_name="app",
            name="code",
        ),
        migrations.RemoveField(
            model_name="app",
            name="code_verifier",
        ),
        migrations.RemoveField(
            model_name="app",
            name="expires_at",
        ),
        migrations.RemoveField(
            model_name="app",
            name="refresh_token",
        ),
        migrations.RemoveField(
            model_name="app",
            name="state",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="app",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="shop_id",
        ),
        migrations.AddField(
            model_name="listing",
            name="user_shop_auth",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="etsy.usershopauth",
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="user_shop_auth",
            field=auto_prefetch.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="etsy.usershopauth",
            ),
        ),
        migrations.AlterField(
            model_name="usershopauth",
            name="app",
            field=auto_prefetch.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="etsy.app"
            ),
        ),
    ]
