# Generated by Django 5.1.4 on 2025-02-01 19:57

import one.base.utils.db_fields
import one.etsy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0014_remove_app_access_token_remove_app_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usershopauth",
            name="scopes",
            field=one.base.utils.db_fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("address_r", "address_r: see billing and shipping addresses"),
                        (
                            "address_w",
                            "address_w: update billing and shipping addresses",
                        ),
                        ("billing_r", "billing_r: see all billing statement data"),
                        ("cart_r", "cart_r: read shopping carts"),
                        ("cart_w", "cart_w: add/remove from shopping carts"),
                        ("email_r", "email_r: read a user profile"),
                        ("favorites_r", "favorites_r: see private favorites"),
                        ("favorites_w", "favorites_w: add/remove favorites"),
                        ("feedback_r", "feedback_r: see purchase info in feedback"),
                        ("listings_d", "listings_d: delete listings"),
                        ("listings_r", "listings_r: see all listings "),
                        ("listings_w", "listings_w: create/edit listings"),
                        ("profile_r", "profile_r: see all profile data"),
                        ("profile_w", "profile_w: update user profile, avatar, etc."),
                        ("recommend_r", "recommend_r: see recommended listings"),
                        (
                            "recommend_w",
                            "recommend_w: accept/reject recommended listings",
                        ),
                        ("shops_r", "shops_r: see private shop info"),
                        ("shops_w", "shops_w: update shop"),
                        ("transactions_r", "transactions_r: see all payment data"),
                        ("transactions_w", "transactions_w: update receipts"),
                    ],
                    max_length=16,
                ),
                default=one.etsy.models.get_default_scopes,
                help_text="The scopes your application requires to use specific endpoints",
                size=None,
            ),
        ),
    ]
