# Generated by Django 5.1.4 on 2025-02-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0015_usershopauth_scopes"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="etsy_payload",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
