# Generated by Django 5.1.4 on 2025-02-04 07:13

from django.db import migrations, models

import one.base.utils.db


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0017_usershop_rename_listing_productlisting_userlisting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlisting",
            name="tags",
            field=one.base.utils.db.ChoiceArrayField(
                base_field=models.CharField(max_length=20), default=list, size=13
            ),
        ),
    ]
