# Generated by Django 5.1.4 on 2025-02-04 19:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0018_alter_userlisting_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlisting",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20), default=list, size=13
            ),
        ),
    ]
