# Generated by Django 5.1.4 on 2025-02-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0019_alter_userlisting_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="keystring",
            field=models.CharField(
                help_text="An Etsy App API Key keystring for the app.",
                max_length=256,
                unique=True,
            ),
        ),
    ]
