# Generated by Django 5.1.4 on 2025-02-05 19:23

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
import storages.backends.s3
from django.db import migrations, models

import one.etsy.models


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0020_alter_app_keystring"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usershopauth",
            options={"base_manager_name": "prefetch_manager", "ordering": ["-id"]},
        ),
        migrations.CreateModel(
            name="UserListingFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("listing_file_id", models.PositiveBigIntegerField(null=True)),
                (
                    "file",
                    models.FileField(
                        storage=storages.backends.s3.S3Storage(
                            default_acl="private",
                            gzip=False,
                            location="private",
                            querystring_auth=True,
                        ),
                        upload_to=one.etsy.models.get_file_path,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("rank", models.PositiveSmallIntegerField(default=1)),
                ("filename", models.CharField(max_length=256, null=True)),
                ("filesize", models.CharField(max_length=256, null=True)),
                ("size_bytes", models.PositiveBigIntegerField(null=True)),
                ("filetype", models.CharField(max_length=128, null=True)),
                ("create_timestamp", models.PositiveBigIntegerField(null=True)),
                ("created_timestamp", models.PositiveBigIntegerField(null=True)),
                (
                    "listing",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="etsy.userlisting",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="UserListingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        storage=storages.backends.s3.S3Storage(
                            default_acl="private",
                            gzip=False,
                            location="private",
                            querystring_auth=True,
                        ),
                        upload_to=one.etsy.models.get_file_path,
                    ),
                ),
                ("listing_image_id", models.PositiveBigIntegerField(null=True)),
                ("rank", models.PositiveSmallIntegerField(default=1)),
                ("name", models.CharField(max_length=256)),
                ("overwrite", models.BooleanField(default=False)),
                ("is_watermarked", models.BooleanField(default=False)),
                ("alt_text", models.CharField(max_length=250)),
                ("hex_code", models.TextField(null=True)),
                ("red", models.PositiveSmallIntegerField(null=True)),
                ("green", models.PositiveSmallIntegerField(null=True)),
                ("blue", models.PositiveSmallIntegerField(null=True)),
                ("hue", models.PositiveSmallIntegerField(null=True)),
                ("saturation", models.PositiveSmallIntegerField(null=True)),
                ("brightness", models.PositiveSmallIntegerField(null=True)),
                ("is_black_and_white", models.BooleanField(default=False)),
                ("creation_tsz", models.PositiveBigIntegerField(null=True)),
                ("created_timestamp", models.PositiveBigIntegerField(null=True)),
                ("url_75x75", models.URLField(max_length=512, null=True)),
                ("url_170x135", models.URLField(max_length=512, null=True)),
                ("url_570xN", models.URLField(max_length=512, null=True)),
                ("url_fullxfull", models.URLField(max_length=512, null=True)),
                ("full_height", models.PositiveIntegerField(null=True)),
                ("full_width", models.PositiveIntegerField(null=True)),
                (
                    "listing",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="etsy.userlisting",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
