# Generated by Django 5.1.4 on 2025-02-07 05:03

import auto_prefetch
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0021_alter_usershopauth_options_userlistingfile_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userlisting",
            name="user_shop_auth",
        ),
        migrations.AddField(
            model_name="usershop",
            name="name",
            field=models.CharField(default="Esty shop", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usershop",
            name="user_shop_auth",
            field=auto_prefetch.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="etsy.usershopauth",
            ),
            preserve_default=False,
        ),
    ]
