# Generated by Django 5.1.4 on 2025-02-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0022_remove_userlisting_user_shop_auth_usershop_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlisting",
            name="tags",
            field=models.TextField(null=True),
        ),
    ]
