# Generated by Django 5.1.4 on 2025-02-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0023_alter_userlisting_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlisting",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
