# Generated by Django 5.1.4 on 2025-02-09 09:25

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0024_alter_userlisting_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userlisting",
            name="user_shop",
        ),
        migrations.AddField(
            model_name="userlisting",
            name="user_shop_auth",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="etsy.usershopauth",
            ),
        ),
    ]
