# Generated by Django 5.1.4 on 2025-02-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0026_remove_userlistingfile_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userlistingimage",
            old_name="image",
            new_name="file",
        ),
        migrations.AlterField(
            model_name="userlistingimage",
            name="alt_text",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="userlistingimage",
            name="name",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
