# Generated by Django 5.1.4 on 2025-02-18 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0027_rename_image_userlistingimage_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="topics",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="user_shop_auth",
        ),
        migrations.DeleteModel(
            name="ProductListing",
        ),
        migrations.DeleteModel(
            name="Shop",
        ),
    ]
