# Generated by Django 5.1.4 on 2025-02-18 18:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0028_remove_shop_topics_remove_shop_user_shop_auth_and_more"),
        ("products", "0012_rename_productlisting_etsylisting"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserShopAuth",
            new_name="EtsyAuth",
        ),
        migrations.RenameModel(
            old_name="UserListingFile",
            new_name="ListingFile",
        ),
        migrations.RenameField(
            model_name="userlisting",
            old_name="user_shop_auth",
            new_name="etsy_auth",
        ),
        migrations.RenameField(
            model_name="usershop",
            old_name="user_shop_auth",
            new_name="etsy_auth",
        ),
    ]
