# Generated by Django 5.1.4 on 2025-02-18 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0029_rename_usershopauth_etsyauth_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserListing",
            new_name="Listing",
        ),
    ]
