# Generated by Django 5.1.4 on 2025-02-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0032_rename_name_shop_shop_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="digital_listing_count",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shop",
            name="create_date",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="created_timestamp",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
