# Generated by Django 5.1.4 on 2025-02-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0033_shop_digital_listing_count_alter_shop_create_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="digital_listing_count",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="listing_active_count",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="num_favorers",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="policy_update_date",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="review_count",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="shipping_from_country_iso",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="shop_location_country_iso",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="transaction_sold_count",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="update_date",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="updated_timestamp",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="url",
            field=models.URLField(max_length=256, null=True),
        ),
    ]
