# Generated by Django 5.1.4 on 2025-02-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0034_alter_shop_digital_listing_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="shop_dict",
            field=models.JSONField(null=True),
        ),
    ]
