# Generated by Django 5.1.4 on 2025-02-18 22:23

from django.db import migrations, models

import one.base.utils.db


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0035_shop_shop_dict"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="languages",
            field=one.base.utils.db.ChoiceArrayField(
                base_field=models.CharField(max_length=16), default=[], size=None
            ),
        ),
    ]
