# Generated by Django 5.1.4 on 2025-02-18 22:24

import one.base.utils.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0036_alter_shop_languages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="languages",
            field=one.base.utils.db_fields.ChoiceArrayField(
                base_field=models.CharField(max_length=16),
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
