# Generated by Django 5.1.4 on 2025-02-18 22:31

from django.db import migrations, models

import one.base.utils.db_fields
import one.etsy.models


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0037_alter_shop_languages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="languages",
            field=one.base.utils.db_fields.ChoiceArrayField(
                base_field=models.CharField(max_length=16),
                size=None,
            ),
        ),
    ]
