# Generated by Django 5.1.4 on 2025-02-18 22:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0039_alter_shop_languages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=16),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
