# Generated by Django 5.1.4 on 2025-02-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0040_alter_shop_languages"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="listing_id",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
