# Generated by Django 5.1.4 on 2025-02-21 20:16

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0041_listing_listing_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listingfile",
            name="listing",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="etsy.listing",
            ),
        ),
        migrations.AlterField(
            model_name="userlistingimage",
            name="listing",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="etsy.listing",
            ),
        ),
    ]
