# Generated by Django 5.1.4 on 2025-02-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0042_alter_listingfile_listing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="featured_rank",
            field=models.IntegerField(null=True),
        ),
    ]
