# Generated by Django 5.1.4 on 2025-02-21 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0043_alter_listing_featured_rank"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userlistingimage",
            name="name",
        ),
    ]
