# Generated by Django 5.1.4 on 2025-02-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0045_rename_userlistingimage_listingimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shop",
            old_name="shop_dict",
            new_name="etsy_dict",
        ),
        migrations.AddField(
            model_name="listing",
            name="etsy_dict",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="listingfile",
            name="etsy_dict",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="listingimage",
            name="etsy_dict",
            field=models.JSONField(null=True),
        ),
    ]
