# Generated by Django 5.1.4 on 2025-02-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0046_rename_shop_dict_shop_etsy_dict_listing_etsy_dict_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listingimage",
            name="is_black_and_white",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="listingimage",
            name="is_watermarked",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="listingimage",
            name="overwrite",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
