# Generated by Django 5.1.4 on 2025-02-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0047_alter_listingimage_is_black_and_white_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="taxonomy_id",
            field=models.PositiveIntegerField(default=2078),
        ),
    ]
