# Generated by Django 5.1.4 on 2025-02-22 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0048_alter_listing_taxonomy_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="etsyauth",
            options={"base_manager_name": "prefetch_manager"},
        ),
    ]
