# Generated by Django 5.1.4 on 2025-02-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0050_app_is_commercial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="is_personalizable",
            field=models.BooleanField(
                default=False, help_text="This listing is personalizable or not."
            ),
        ),
    ]
