# Generated by Django 5.1.4 on 2025-02-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0051_alter_listing_is_personalizable"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="is_supply",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="When true, tags the listing as a supply product, else indicates that it's a finished product. Helps buyers locate the listing under the Supplies heading. Requires 'who_made' and 'when_made'.",
                null=True,
            ),
        ),
    ]
