# Generated by Django 5.1.4 on 2025-03-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etsy", "0052_listing_is_supply"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="id",
        ),
        migrations.AlterField(
            model_name="shop",
            name="shop_id",
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
    ]
