# Generated by Django 5.1.4 on 2024-12-13 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"base_manager_name": "prefetch_manager", "ordering": ["-id"]},
        ),
    ]
