# Generated by Django 5.1.4 on 2024-12-22 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_message_deleted"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="author",
            new_name="user",
        ),
    ]
