# Generated by Django 5.1.4 on 2024-12-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_rename_author_message_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "base_manager_name": "prefetch_manager",
                "ordering": ["-created_at"],
            },
        ),
    ]
