# Generated by Django 5.1.4 on 2024-12-22 21:03

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_chat_site"),
        ("sites", "0010_alter_site_rest_languages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="site",
            field=auto_prefetch.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="sites.site"
            ),
            preserve_default=False,
        ),
    ]
