# Generated by Django 5.1.4 on 2025-01-03 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_alter_page_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pageparentfolder",
            name="sites",
        ),
    ]
