# Generated by Django 5.1.4 on 2025-01-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_remove_pageparentfolder_sites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(
                blank=True, editable=False, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug_de",
            field=models.SlugField(
                blank=True, editable=False, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug_el",
            field=models.SlugField(
                blank=True, editable=False, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug_en",
            field=models.SlugField(
                blank=True, editable=False, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug_es",
            field=models.SlugField(
                blank=True, editable=False, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug_fr",
            field=models.SlugField(
                blank=True, editable=False, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug_it",
            field=models.SlugField(
                blank=True, editable=False, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug_nl",
            field=models.SlugField(
                blank=True, editable=False, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug_pl",
            field=models.SlugField(
                blank=True, editable=False, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug_pt",
            field=models.SlugField(
                blank=True, editable=False, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug_ru",
            field=models.SlugField(
                blank=True, editable=False, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug_sk",
            field=models.SlugField(
                blank=True, editable=False, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug_sl",
            field=models.SlugField(
                blank=True, editable=False, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug_sv",
            field=models.SlugField(
                blank=True, editable=False, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug_tr",
            field=models.SlugField(
                blank=True, editable=False, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug_uk",
            field=models.SlugField(
                blank=True, editable=False, max_length=128, null=True
            ),
        ),
    ]
