# Generated by Django 5.1.3 on 2024-12-07 22:36

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allow_translation", models.BooleanField(default=False)),
                ("override_translated_fields", models.BooleanField(default=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("plans", "Plans"),
                            ("products", "Products"),
                            ("info", "Informative"),
                            ("accounts", "Accounts"),
                            ("legal", "Legal concerns"),
                        ],
                        max_length=32,
                    ),
                ),
                ("question", models.CharField(max_length=256)),
                ("question_en", models.CharField(max_length=256, null=True)),
                ("question_de", models.CharField(max_length=256, null=True)),
                ("question_es", models.CharField(max_length=256, null=True)),
                ("question_fr", models.CharField(max_length=256, null=True)),
                ("question_el", models.CharField(max_length=256, null=True)),
                ("question_eo", models.CharField(max_length=256, null=True)),
                ("question_fi", models.CharField(max_length=256, null=True)),
                ("question_it", models.CharField(max_length=256, null=True)),
                ("question_nl", models.CharField(max_length=256, null=True)),
                ("question_nn", models.CharField(max_length=256, null=True)),
                ("question_pl", models.CharField(max_length=256, null=True)),
                ("question_pt", models.CharField(max_length=256, null=True)),
                ("question_pt_br", models.CharField(max_length=256, null=True)),
                ("question_ru", models.CharField(max_length=256, null=True)),
                ("question_sk", models.CharField(max_length=256, null=True)),
                ("question_sl", models.CharField(max_length=256, null=True)),
                ("question_sq", models.CharField(max_length=256, null=True)),
                ("question_sr", models.CharField(max_length=256, null=True)),
                ("question_sv", models.CharField(max_length=256, null=True)),
                ("question_tr", models.CharField(max_length=256, null=True)),
                ("question_uk", models.CharField(max_length=256, null=True)),
                ("answer", models.TextField()),
                ("answer_en", models.TextField(null=True)),
                ("answer_de", models.TextField(null=True)),
                ("answer_es", models.TextField(null=True)),
                ("answer_fr", models.TextField(null=True)),
                ("answer_el", models.TextField(null=True)),
                ("answer_eo", models.TextField(null=True)),
                ("answer_fi", models.TextField(null=True)),
                ("answer_it", models.TextField(null=True)),
                ("answer_nl", models.TextField(null=True)),
                ("answer_nn", models.TextField(null=True)),
                ("answer_pl", models.TextField(null=True)),
                ("answer_pt", models.TextField(null=True)),
                ("answer_pt_br", models.TextField(null=True)),
                ("answer_ru", models.TextField(null=True)),
                ("answer_sk", models.TextField(null=True)),
                ("answer_sl", models.TextField(null=True)),
                ("answer_sq", models.TextField(null=True)),
                ("answer_sr", models.TextField(null=True)),
                ("answer_sv", models.TextField(null=True)),
                ("answer_tr", models.TextField(null=True)),
                ("answer_uk", models.TextField(null=True)),
                ("can_be_shown_in_home", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
