# Generated by Django 5.1.3 on 2024-11-16 18:07

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("plans", "Plans"),
                            ("products", "Products"),
                            ("info", "Informative"),
                            ("accounts", "Accounts"),
                            ("legal", "Legal concerns"),
                        ],
                        max_length=32,
                    ),
                ),
                ("question", models.CharField(max_length=256)),
                ("question_en", models.CharField(max_length=256, null=True)),
                ("question_de", models.CharField(max_length=256, null=True)),
                ("question_es", models.CharField(max_length=256, null=True)),
                ("answer", models.TextField()),
                ("answer_en", models.TextField(null=True)),
                ("answer_de", models.TextField(null=True)),
                ("answer_es", models.TextField(null=True)),
                ("sites", models.ManyToManyField(to="sites.site")),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
