# Generated by Django 5.1.3 on 2024-11-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faqs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="can_be_shown_in_home",
            field=models.BooleanField(default=True),
        ),
    ]
