# Generated by Django 5.1.4 on 2024-12-09 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faqs", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faq",
            name="answer_eo",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="answer_fi",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="answer_nn",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="answer_sq",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="answer_sr",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="question_eo",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="question_fi",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="question_nn",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="question_sq",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="question_sr",
        ),
    ]
