# Generated by Django 5.1.3 on 2024-11-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faqs", "0002_faq_can_be_shown_in_home"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
