# Generated by Django 5.1.4 on 2024-12-09 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faqs", "0003_remove_faq_answer_eo_remove_faq_answer_fi_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faq",
            name="answer_pt_br",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="question_pt_br",
        ),
    ]
