# Generated by Django 5.1.4 on 2024-12-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faqs", "0004_faq_featured"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faq",
            name="is_active",
        ),
    ]
