# Generated by Django 5.1.4 on 2024-12-09 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faqs", "0004_remove_faq_answer_pt_br_remove_faq_question_pt_br"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faq",
            name="answer_uk",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="question_uk",
        ),
    ]
