# Generated by Django 5.1.3 on 2024-11-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faqs", "0005_faq_answer_el_faq_answer_eo_faq_answer_fi_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="allow_translation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="faq",
            name="override_translated_fields",
            field=models.BooleanField(default=False),
        ),
    ]
