# Generated by Django 5.1.3 on 2024-11-24 06:53

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_rename_languages_extendedsite_rest_languages_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=auto_prefetch.ForeignKey(
                default="en",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="base.language",
            ),
        ),
    ]
