# Generated by Django 5.2 on 2025-04-26 09:29

import auto_prefetch
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import one.base.utils.db
import one.products.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("etsy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(editable=False, max_length=64, unique=True)),
                (
                    "present_in_filesystem",
                    models.BooleanField(default=True, editable=False),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("de", "German"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("pt", "Portuguese"),
                        ],
                        default="en",
                        max_length=4,
                    ),
                ),
                (
                    "languages",
                    one.base.utils.db.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("en", "English"),
                                ("de", "German"),
                                ("es", "Spanish"),
                                ("fr", "French"),
                                ("it", "Italian"),
                                ("nl", "Dutch"),
                                ("pt", "Portuguese"),
                            ],
                            max_length=8,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "topics",
                    one.base.utils.db.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("django", "Django"),
                                ("htmx", "htmx"),
                                ("alpinejs", "AlpineJS"),
                                ("devops", "DevOps"),
                                ("python", "Python"),
                                ("linux", "Linux"),
                                ("latex", "LaTex"),
                                ("matlab", "Matlab"),
                                ("siemens", "Siemens"),
                                ("excel", "Excel"),
                                ("maths", "Maths"),
                                ("mechanics", "Mechanics"),
                                ("english", "English"),
                                ("electronics", "Electronics"),
                                ("calendar", "Calendars"),
                            ],
                            max_length=16,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("title_en", models.CharField(max_length=128, null=True)),
                ("title_de", models.CharField(max_length=128, null=True)),
                ("title_es", models.CharField(max_length=128, null=True)),
                ("title_fr", models.CharField(max_length=128, null=True)),
                ("title_it", models.CharField(max_length=128, null=True)),
                ("title_nl", models.CharField(max_length=128, null=True)),
                ("title_pt", models.CharField(max_length=128, null=True)),
                ("slug", models.SlugField(max_length=128)),
                ("slug_en", models.SlugField(max_length=128, null=True)),
                ("slug_de", models.SlugField(max_length=128, null=True)),
                ("slug_es", models.SlugField(max_length=128, null=True)),
                ("slug_fr", models.SlugField(max_length=128, null=True)),
                ("slug_it", models.SlugField(max_length=128, null=True)),
                ("slug_nl", models.SlugField(max_length=128, null=True)),
                ("slug_pt", models.SlugField(max_length=128, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_de", models.TextField(blank=True, null=True)),
                ("description_es", models.TextField(blank=True, null=True)),
                ("description_fr", models.TextField(blank=True, null=True)),
                ("description_it", models.TextField(blank=True, null=True)),
                ("description_nl", models.TextField(blank=True, null=True)),
                ("description_pt", models.TextField(blank=True, null=True)),
                ("price", models.FloatField(default=1.0)),
                (
                    "discount_percentage",
                    models.SmallIntegerField(
                        default=90,
                        help_text="It is applied to the country with the lowest GDP per capita.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Discount in percentage",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_draft", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="EtsyShop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("de", "German"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("pt", "Portuguese"),
                        ],
                        default="en",
                        max_length=4,
                    ),
                ),
                (
                    "languages",
                    one.base.utils.db.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("en", "English"),
                                ("de", "German"),
                                ("es", "Spanish"),
                                ("fr", "French"),
                                ("it", "Italian"),
                                ("nl", "Dutch"),
                                ("pt", "Portuguese"),
                            ],
                            max_length=8,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("name", models.CharField(default="Shop example", max_length=64)),
                ("generic_listing_description", models.TextField()),
                ("generic_listing_description_en", models.TextField(null=True)),
                ("generic_listing_description_de", models.TextField(null=True)),
                ("generic_listing_description_es", models.TextField(null=True)),
                ("generic_listing_description_fr", models.TextField(null=True)),
                ("generic_listing_description_it", models.TextField(null=True)),
                ("generic_listing_description_nl", models.TextField(null=True)),
                ("generic_listing_description_pt", models.TextField(null=True)),
                (
                    "topics",
                    one.base.utils.db.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("django", "Django"),
                                ("htmx", "htmx"),
                                ("alpinejs", "AlpineJS"),
                                ("devops", "DevOps"),
                                ("python", "Python"),
                                ("linux", "Linux"),
                                ("latex", "LaTex"),
                                ("matlab", "Matlab"),
                                ("siemens", "Siemens"),
                                ("excel", "Excel"),
                                ("maths", "Maths"),
                                ("mechanics", "Mechanics"),
                                ("english", "English"),
                                ("electronics", "Electronics"),
                                ("calendar", "Calendars"),
                            ],
                            max_length=16,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "price_percentage",
                    models.SmallIntegerField(
                        default=150,
                        help_text="Percent to apply to Etsy listing price.",
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(300),
                        ],
                        verbose_name="Price percentace",
                    ),
                ),
                ("etsy_payload", models.JSONField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "user_shop_auth",
                    auto_prefetch.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="etsy.etsyauth",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="EtsyListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("include_generic_description", models.BooleanField(default=True)),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=999,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(999),
                        ],
                    ),
                ),
                ("price", models.FloatField(default=1.0)),
                (
                    "who_made",
                    models.CharField(
                        choices=[
                            ("i_did", "I did"),
                            ("someone_else", "Someone else"),
                            ("collective", "Collective"),
                        ],
                        default="i_did",
                        max_length=32,
                    ),
                ),
                (
                    "when_made",
                    models.CharField(
                        choices=[
                            ("made_to_order", "Made to order"),
                            ("2020_2025", "2020 - 2025"),
                            ("2010_2019", "2010 - 2019"),
                            ("2006_2009", "2006 - 2009"),
                            ("before_2006", "Before 2006"),
                        ],
                        default="2020_2025",
                        max_length=32,
                    ),
                ),
                (
                    "taxonomy_id",
                    models.PositiveIntegerField(
                        choices=[(2078, "Digital prints")], default=2078
                    ),
                ),
                (
                    "listing_type",
                    models.CharField(
                        choices=[
                            ("physical", "Physical"),
                            ("download", "Download"),
                            ("both", "Both"),
                        ],
                        default="download",
                        max_length=32,
                    ),
                ),
                ("response", models.JSONField(blank=True, null=True)),
                ("listing_id", models.PositiveIntegerField(blank=True, null=True)),
                ("url", models.URLField(blank=True, max_length=256, null=True)),
                ("state", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "shop",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.etsyshop",
                    ),
                ),
                (
                    "product",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ProductFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "file",
                    models.FileField(
                        storage=storages.backends.s3.S3Storage(
                            default_acl="private",
                            gzip=False,
                            location="private",
                            querystring_auth=True,
                        ),
                        upload_to=one.products.models.get_file_path,
                    ),
                ),
                (
                    "product",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("file", models.FileField(upload_to=one.products.models.get_file_path)),
                (
                    "product",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
