# Generated by Django 5.2 on 2025-04-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                db_index=True, editable=False, max_length=64, unique=True
            ),
        ),
    ]
