# Generated by Django 5.1.4 on 2025-01-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_product_tags_remove_product_created_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="etsy_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="etsy_url",
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="product",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
