# Generated by Django 5.1.4 on 2025-01-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_etsy_id_product_etsy_url_product_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="allow_translation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="override_translated_fields",
            field=models.BooleanField(default=False),
        ),
    ]
