# Generated by Django 5.2.4 on 2025-08-01 11:25

import one.db
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_etsyshop_topics_alter_product_topics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etsyshop",
            name="topics",
            field=one.db.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("one", "One project"),
                        ("django", "Django"),
                        ("htmx", "htmx"),
                        ("alpinejs", "AlpineJS"),
                        ("devops", "DevOps"),
                        ("python", "Python"),
                        ("javascript", "JavasSript"),
                        ("linux", "Linux"),
                        ("latex", "LaTex"),
                        ("matlab", "Matlab"),
                        ("siemens", "Siemens"),
                        ("excel", "Excel"),
                        ("postgres", "PostgreSQL"),
                        ("maths", "Maths"),
                        ("mechanics", "Mechanics"),
                        ("english", "English"),
                        ("electronics", "Electronics"),
                        ("calendar", "Calendars"),
                        ("career", "Career"),
                        ("psychology", "Psychology"),
                        ("philosophy", "Philosophy"),
                        ("finance", "Finance"),
                        ("marketing", "Marketing"),
                        ("entrepreneurship", "Entrepreneurship"),
                    ],
                    max_length=16,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="topics",
            field=one.db.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("one", "One project"),
                        ("django", "Django"),
                        ("htmx", "htmx"),
                        ("alpinejs", "AlpineJS"),
                        ("devops", "DevOps"),
                        ("python", "Python"),
                        ("javascript", "JavasSript"),
                        ("linux", "Linux"),
                        ("latex", "LaTex"),
                        ("matlab", "Matlab"),
                        ("siemens", "Siemens"),
                        ("excel", "Excel"),
                        ("postgres", "PostgreSQL"),
                        ("maths", "Maths"),
                        ("mechanics", "Mechanics"),
                        ("english", "English"),
                        ("electronics", "Electronics"),
                        ("calendar", "Calendars"),
                        ("career", "Career"),
                        ("psychology", "Psychology"),
                        ("philosophy", "Philosophy"),
                        ("finance", "Finance"),
                        ("marketing", "Marketing"),
                        ("entrepreneurship", "Entrepreneurship"),
                    ],
                    max_length=16,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
