# Generated by Django 5.1.4 on 2025-01-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_allow_translation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="summary_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="summary_el",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="summary_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="summary_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="summary_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="summary_it",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="summary_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="summary_pl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="summary_pt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="summary_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="summary_sk",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="summary_sl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="summary_sv",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="summary_tr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="summary_uk",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="title_de",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="title_el",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="title_en",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="title_es",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="title_fr",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="title_it",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="title_nl",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="title_pl",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="title_pt",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="title_ru",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="title_sk",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="title_sl",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="title_sv",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="title_tr",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="title_uk",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
