# Generated by Django 5.2 on 2025-05-21 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_etsylisting_created_on_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="etsylisting",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="etsylisting",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="etsyshop",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="etsyshop",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="product",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="product",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="productfile",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="productfile",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="updated_on",
        ),
        migrations.AddField(
            model_name="etsylisting",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848231, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="etsylisting",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848323, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="etsyshop",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848231, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="etsyshop",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848323, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848231, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848323, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="productfile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848231, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="productfile",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848323, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848231, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848323, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
