# Generated by Django 5.1.4 on 2025-01-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_summary_de_product_summary_el_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="allow_translation",
        ),
        migrations.RemoveField(
            model_name="product",
            name="override_translated_fields",
        ),
        migrations.AddField(
            model_name="product",
            name="default_language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("de", "German"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("el", "Greek"),
                    ("it", "Italian"),
                    ("nl", "Dutch"),
                    ("pl", "Polish"),
                    ("pt", "Portuguese"),
                    ("ru", "Russian"),
                    ("sk", "Slovak"),
                    ("sl", "Slovenian"),
                    ("sv", "Swedish"),
                    ("tr", "Turkish"),
                    ("uk", "Ukrainian"),
                ],
                default="en",
                max_length=4,
            ),
        ),
    ]
