# Generated by Django 5.2 on 2025-05-23 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_remove_etsylisting_created_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etsylisting",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="etsylisting",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="etsyshop",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="etsyshop",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="productfile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="productfile",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.utils.timezone.now
            ),
        ),
    ]
