# Generated by Django 5.1.4 on 2025-01-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_product_rest_languages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="rest_languages",
        ),
    ]
