# Generated by Django 5.1.4 on 2025-01-28 04:23

import django.core.validators
import one.products.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_product_languages"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="summary",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="summary_de",
            new_name="description_de",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="summary_el",
            new_name="description_el",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="summary_en",
            new_name="description_en",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="summary_es",
            new_name="description_es",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="summary_fr",
            new_name="description_fr",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="summary_it",
            new_name="description_it",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="summary_nl",
            new_name="description_nl",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="summary_pl",
            new_name="description_pl",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="summary_pt",
            new_name="description_pt",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="summary_ru",
            new_name="description_ru",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="summary_sk",
            new_name="description_sk",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="summary_sl",
            new_name="description_sl",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="summary_sv",
            new_name="description_sv",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="summary_tr",
            new_name="description_tr",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="summary_uk",
            new_name="description_uk",
        ),
        migrations.RemoveField(
            model_name="product",
            name="etsy_id",
        ),
        migrations.RemoveField(
            model_name="product",
            name="etsy_url",
        ),
        migrations.AddField(
            model_name="product",
            name="discount_percentage",
            field=models.SmallIntegerField(
                default=90,
                help_text="It is applied to the country with the lowest GDP per capita.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Discount in percentage",
            ),
        ),
        migrations.AlterField(
            model_name="productfile",
            name="file",
            field=models.FileField(
                storage=storages.backends.s3.S3Storage(
                    default_acl="private",
                    gzip=False,
                    location="private",
                    querystring_auth=True,
                ),
                upload_to=one.products.models.get_file_path,
            ),
        ),
    ]
