# Generated by Django 5.1.4 on 2025-02-18 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_etsyshop_productlisting"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductListing",
            new_name="EtsyListing",
        ),
    ]
