# Generated by Django 5.1.4 on 2025-03-10 21:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_product_created_on_product_updated_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="etsyshop",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="etsyshop",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
