# Generated by Django 5.1.4 on 2025-03-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_etsylisting_created_on_etsylisting_updated_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="etsylisting",
            name="include_generic_description",
            field=models.BooleanField(default=True),
        ),
    ]
