# Generated by Django 5.1.7 on 2025-03-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0017_rename_default_language_etsyshop_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="present_in_filesystem",
            field=models.BooleanField(default=True),
        ),
    ]
