# Generated by Django 5.1.7 on 2025-03-26 19:20

import one.base.utils.db
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0018_product_present_in_filesystem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="etsyshop",
            name="generic_listing_description_el",
        ),
        migrations.RemoveField(
            model_name="etsyshop",
            name="generic_listing_description_pl",
        ),
        migrations.RemoveField(
            model_name="etsyshop",
            name="generic_listing_description_ru",
        ),
        migrations.RemoveField(
            model_name="etsyshop",
            name="generic_listing_description_sk",
        ),
        migrations.RemoveField(
            model_name="etsyshop",
            name="generic_listing_description_sl",
        ),
        migrations.RemoveField(
            model_name="etsyshop",
            name="generic_listing_description_sv",
        ),
        migrations.RemoveField(
            model_name="etsyshop",
            name="generic_listing_description_tr",
        ),
        migrations.RemoveField(
            model_name="etsyshop",
            name="generic_listing_description_uk",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description_el",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description_pl",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description_sk",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description_sl",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description_sv",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description_tr",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description_uk",
        ),
        migrations.RemoveField(
            model_name="product",
            name="title_el",
        ),
        migrations.RemoveField(
            model_name="product",
            name="title_pl",
        ),
        migrations.RemoveField(
            model_name="product",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="product",
            name="title_sk",
        ),
        migrations.RemoveField(
            model_name="product",
            name="title_sl",
        ),
        migrations.RemoveField(
            model_name="product",
            name="title_sv",
        ),
        migrations.RemoveField(
            model_name="product",
            name="title_tr",
        ),
        migrations.RemoveField(
            model_name="product",
            name="title_uk",
        ),
        migrations.AlterField(
            model_name="etsyshop",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("de", "German"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("it", "Italian"),
                    ("nl", "Dutch"),
                    ("pt", "Portuguese"),
                ],
                default="en",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="etsyshop",
            name="languages",
            field=one.base.utils.db.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("en", "English"),
                        ("de", "German"),
                        ("es", "Spanish"),
                        ("fr", "French"),
                        ("it", "Italian"),
                        ("nl", "Dutch"),
                        ("pt", "Portuguese"),
                    ],
                    max_length=8,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("de", "German"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("it", "Italian"),
                    ("nl", "Dutch"),
                    ("pt", "Portuguese"),
                ],
                default="en",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="languages",
            field=one.base.utils.db.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("en", "English"),
                        ("de", "German"),
                        ("es", "Spanish"),
                        ("fr", "French"),
                        ("it", "Italian"),
                        ("nl", "Dutch"),
                        ("pt", "Portuguese"),
                    ],
                    max_length=8,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
