# Generated by Django 5.2 on 2025-04-14 05:30

import one.base.utils.db
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0019_remove_etsyshop_generic_listing_description_el_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="etsyshop",
            name="topics_new",
            field=one.base.utils.db.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("django", "Django"),
                        ("htmx", "htmx"),
                        ("alpinejs", "AlpineJS"),
                        ("devops", "DevOps"),
                        ("python", "Python"),
                        ("linux", "Linux"),
                        ("latex", "LaTex"),
                        ("matlab", "Matlab"),
                        ("siemens", "Siemens"),
                        ("excel", "Excel"),
                        ("maths", "Maths"),
                        ("mechanics", "Mechanics"),
                        ("english", "English"),
                        ("electronics", "Electronics"),
                        ("calendar", "Calendars"),
                    ],
                    max_length=16,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="topics_new",
            field=one.base.utils.db.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("django", "Django"),
                        ("htmx", "htmx"),
                        ("alpinejs", "AlpineJS"),
                        ("devops", "DevOps"),
                        ("python", "Python"),
                        ("linux", "Linux"),
                        ("latex", "LaTex"),
                        ("matlab", "Matlab"),
                        ("siemens", "Siemens"),
                        ("excel", "Excel"),
                        ("maths", "Maths"),
                        ("mechanics", "Mechanics"),
                        ("english", "English"),
                        ("electronics", "Electronics"),
                        ("calendar", "Calendars"),
                    ],
                    max_length=16,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
