# Generated by Django 5.2 on 2025-04-14 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0020_etsyshop_topics_new_product_topics_new"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="etsyshop",
        #     name="topics",
        # ),
        # migrations.RemoveField(
        #     model_name="product",
        #     name="topics",
        # ),
    ]
