# Generated by Django 5.2 on 2025-04-14 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0021_remove_etsyshop_topics_remove_product_topics"),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name="etsyshop",
        #     old_name="topics_new",
        #     new_name="topics",
        # ),
        # migrations.RenameField(
        #     model_name="product",
        #     old_name="topics_new",
        #     new_name="topics",
        # ),
    ]
