# Generated by Django 5.2 on 2025-04-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0022_rename_topics_new_etsyshop_topics_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
    ]
