# Generated by Django 5.2 on 2025-04-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0023_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="present_in_filesystem",
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
