# Generated by Django 5.2 on 2025-04-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0024_alter_product_present_in_filesystem"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug_de",
            field=models.SlugField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="slug_en",
            field=models.SlugField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="slug_es",
            field=models.SlugField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="slug_fr",
            field=models.SlugField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="slug_it",
            field=models.SlugField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="slug_nl",
            field=models.SlugField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="slug_pt",
            field=models.SlugField(max_length=128, null=True),
        ),
    ]
