# Generated by Django 5.2 on 2025-05-21 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="barchart",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="codabarbarcode",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="code128barcode",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="code39barcode",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="ean13barcode",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="ean13guardbarcode",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="ean14barcode",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="ean8barcode",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="ean8guardbarcode",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="ganttchart",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="gs1_128barcode",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="heatmapchart",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="isbn10barcode",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="isbn13barcode",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="issnbarcode",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="itfbarcode",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="janbarcode",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="pointdatachart",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="pznbarcode",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="spiderchart",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="upcbarcode",
            old_name="created_on",
            new_name="created_at",
        ),
    ]
