# Generated by Django 5.2 on 2025-06-15 18:44

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("name_en", models.CharField(max_length=128, null=True)),
                ("name_de", models.CharField(max_length=128, null=True)),
                ("name_es", models.CharField(max_length=128, null=True)),
                ("name_fr", models.CharField(max_length=128, null=True)),
                ("name_it", models.CharField(max_length=128, null=True)),
                ("name_nl", models.CharField(max_length=128, null=True)),
                ("name_pt", models.CharField(max_length=128, null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.CharField(max_length=256)),
                ("question_en", models.CharField(max_length=256, null=True)),
                ("question_de", models.CharField(max_length=256, null=True)),
                ("question_es", models.CharField(max_length=256, null=True)),
                ("question_fr", models.CharField(max_length=256, null=True)),
                ("question_it", models.CharField(max_length=256, null=True)),
                ("question_nl", models.CharField(max_length=256, null=True)),
                ("question_pt", models.CharField(max_length=256, null=True)),
                ("answer", models.TextField()),
                ("answer_en", models.TextField(null=True)),
                ("answer_de", models.TextField(null=True)),
                ("answer_es", models.TextField(null=True)),
                ("answer_fr", models.TextField(null=True)),
                ("answer_it", models.TextField(null=True)),
                ("answer_nl", models.TextField(null=True)),
                ("answer_pt", models.TextField(null=True)),
                ("sites", models.ManyToManyField(to="sites.site")),
                ("categories", models.ManyToManyField(to="faqs.faqcategory")),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
