# Generated by Django 5.2 on 2025-05-10 18:55

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faqs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("name_en", models.CharField(max_length=128, null=True)),
                ("name_de", models.CharField(max_length=128, null=True)),
                ("name_es", models.CharField(max_length=128, null=True)),
                ("name_fr", models.CharField(max_length=128, null=True)),
                ("name_it", models.CharField(max_length=128, null=True)),
                ("name_nl", models.CharField(max_length=128, null=True)),
                ("name_pt", models.CharField(max_length=128, null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name="faq",
            name="category",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="featured",
        ),
    ]
