# Generated by Django 5.2 on 2025-05-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faqs", "0002_faqcategory_remove_faq_category_remove_faq_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="categories",
            field=models.ManyToManyField(to="faqs.faqcategory"),
        ),
    ]
