# Generated by Django 5.2 on 2025-05-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faqs", "0002_faqcategory_remove_faq_featured_alter_faq_category_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="faq",
            name="faq_category_fkey",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="category",
        ),
        migrations.AddField(
            model_name="faq",
            name="categories",
            field=models.ManyToManyField(to="faqs.faqcategory"),
        ),
    ]
