# Generated by Django 5.1.4 on 2025-01-26 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faqs", "0007_alter_faq_languages"),
    ]

    operations = [
        migrations.RenameField(
            model_name="faq",
            old_name="languages",
            new_name="rest_languages",
        ),
    ]
