# Generated by Django 5.1 on 2025-03-15 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faqs", "0009_rename_rest_languages_faq_languages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faq",
            name="default_language",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="languages",
        ),
    ]
