# Generated by Django 5.1.7 on 2025-03-26 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faqs", "0010_remove_faq_default_language_remove_faq_languages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faq",
            name="answer_el",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="answer_pl",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="answer_ru",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="answer_sk",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="answer_sl",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="answer_sv",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="answer_tr",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="answer_uk",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="question_el",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="question_pl",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="question_ru",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="question_sk",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="question_sl",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="question_sv",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="question_tr",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="question_uk",
        ),
    ]
