# Generated by Django 5.0.4 on 2024-04-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0002_remove_recipient_name_emailtemplate_attachment1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailtemplate",
            old_name="respond_to",
            new_name="reply_to",
        ),
        migrations.AddField(
            model_name="recipient",
            name="email_address_cc",
            field=models.EmailField(blank=True, max_length=64, null=True),
        ),
    ]
