# Generated by Django 5.0.4 on 2024-04-27 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0003_rename_respond_to_emailtemplate_reply_to_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipient",
            old_name="email_address",
            new_name="addresses",
        ),
        migrations.RenameField(
            model_name="recipient",
            old_name="email_address_cc",
            new_name="cc_addresses",
        ),
    ]
