# Generated by Django 5.0.4 on 2024-04-27 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0004_rename_email_address_recipient_addresses_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipient",
            name="cc_addresses",
        ),
    ]
