# Generated by Django 5.0.4 on 2024-04-28 12:13

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0005_remove_recipient_cc_addresses"),
    ]

    operations = [
        migrations.CreateModel(
            name="PastRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("addresses", models.EmailField(max_length=64)),
                (
                    "email_sent_on",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("subject", models.CharField(max_length=128)),
                ("body", models.TextField()),
                (
                    "email_template",
                    auto_prefetch.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="emails.emailtemplate",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
