# Generated by Django 5.0.4 on 2024-04-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0006_pastrecipient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pastrecipient",
            name="addresses",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="addresses",
            field=models.CharField(max_length=128),
        ),
    ]
