# Generated by Django 5.0.4 on 2024-04-28 21:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0008_pastrecipient_var1_pastrecipient_var2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pastrecipient",
            name="addresses",
        ),
        migrations.RemoveField(
            model_name="recipient",
            name="addresses",
        ),
        migrations.AddField(
            model_name="pastrecipient",
            name="address",
            field=models.EmailField(default="test@example.com", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipient",
            name="address",
            field=models.EmailField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
