# Generated by Django 5.0.4 on 2024-05-25 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0010_emailtemplate_cc_pastrecipient_remarks_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailtemplate",
            name="var4_meaning",
        ),
        migrations.RemoveField(
            model_name="emailtemplate",
            name="var5_meaning",
        ),
        migrations.RemoveField(
            model_name="pastrecipient",
            name="var4",
        ),
        migrations.RemoveField(
            model_name="pastrecipient",
            name="var5",
        ),
        migrations.RemoveField(
            model_name="recipient",
            name="var4",
        ),
        migrations.RemoveField(
            model_name="recipient",
            name="var5",
        ),
    ]
