# Generated by Django 5.1.4 on 2024-12-30 19:57

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0018_delete_spampath"),
        ("search", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="searchterm",
            name="country_code",
        ),
        migrations.AddField(
            model_name="searchterm",
            name="client",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clients.client",
            ),
        ),
    ]
