# Generated by Django 5.1.3 on 2024-11-06 22:35

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("emoji", models.CharField(default="", max_length=8)),
                ("emoji_in_brand", models.BooleanField(default=True)),
                ("default_page_title", models.CharField(max_length=64)),
                ("default_page_description", models.TextField(max_length=256)),
                ("default_page_keywords", models.CharField(max_length=128)),
                ("change_theme_light_in_footer", models.BooleanField(default=True)),
                ("change_theme_light_in_navbar", models.BooleanField(default=True)),
                ("last_huey_flush", models.DateTimeField(null=True)),
                (
                    "site",
                    auto_prefetch.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
