# Generated by Django 5.1.3 on 2024-12-07 22:36

import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True, max_length=8, primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Traffic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_path", models.CharField(max_length=255)),
                ("request_method", models.CharField(default="GET", max_length=7)),
                ("request_GET", models.TextField(null=True)),
                ("request_POST", models.TextField(null=True)),
                ("request_GET_ref", models.CharField(max_length=255, null=True)),
                ("request_headers", models.TextField(null=True)),
                ("request_country_code", models.CharField(max_length=8, null=True)),
                ("response_status_code", models.PositiveSmallIntegerField(default=200)),
                ("response_headers", models.TextField(null=True)),
                (
                    "time",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="time",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
