# Generated by Django 5.1.3 on 2024-11-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendedsite",
            name="force_translation_from_default",
            field=models.BooleanField(default=False),
        ),
    ]
