# Generated by Django 5.1.3 on 2024-11-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_description_de",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_description_en",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_description_es",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_keywords_de",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_keywords_en",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_keywords_es",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_title_de",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_title_en",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_title_es",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
