# Generated by Django 5.1.3 on 2024-11-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendedsite",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
