# Generated by Django 5.1.3 on 2024-11-09 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_extendedsite_force_translation_from_default"),
    ]

    operations = [
        migrations.RenameField(
            model_name="extendedsite",
            old_name="force_translation_from_default",
            new_name="translate_fields_from_default_language",
        ),
    ]
