# Generated by Django 5.1.2 on 2024-10-24 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_pagelink_article_pagelink_page"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pagelink",
            old_name="custom_title",
            new_name="external_title",
        ),
        migrations.RenameField(
            model_name="pagelink",
            old_name="custom_title_de",
            new_name="external_title_de",
        ),
        migrations.RenameField(
            model_name="pagelink",
            old_name="custom_title_en",
            new_name="external_title_en",
        ),
        migrations.RenameField(
            model_name="pagelink",
            old_name="custom_title_es",
            new_name="external_title_es",
        ),
    ]
