# Generated by Django 5.1.3 on 2024-11-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="traffic",
            old_name="response_code",
            new_name="response_status_code",
        ),
        migrations.RenameField(
            model_name="traffic",
            old_name="request_site",
            new_name="site",
        ),
        migrations.RenameField(
            model_name="traffic",
            old_name="request_user",
            new_name="user",
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="picocss_color",
            field=models.CharField(
                choices=[
                    ("amber", "Amber"),
                    ("blue", "Blue"),
                    ("fuchsia", "Fuchsia"),
                    ("jade", "Jade"),
                    ("grey", "Grey"),
                    ("purple", "Purple"),
                    ("cyan", "Cyan"),
                    ("red", "Read"),
                    ("violet", "Violet"),
                    ("indigo", "Indigo"),
                    ("slate", "Slate"),
                    ("lime", "Lime"),
                    ("colors", "Colors"),
                    ("orange", "Orange"),
                    ("pumpkin", "Pumpkin"),
                    ("zinc", "Zinc"),
                    ("sand", "Sand"),
                    ("yellow", "Yellow"),
                    ("pink", "Pink"),
                    ("green", "Green"),
                ],
                default="orange",
                max_length=16,
            ),
        ),
    ]
