# Generated by Django 5.1.3 on 2024-11-07 20:02

import django.contrib.sites.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_extendedsite_default_page_description_de_and_more"),
        ("sites", "0005_delete_extendedsite"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="extendedsite",
            options={},
        ),
        migrations.AlterModelManagers(
            name="extendedsite",
            managers=[
                ("objects", django.contrib.sites.models.SiteManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="extendedsite",
            name="id",
        ),
        migrations.RemoveField(
            model_name="extendedsite",
            name="site",
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="site_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="sites.site",
            ),
            preserve_default=False,
        ),
    ]
