# Generated by Django 5.1.3 on 2024-11-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_rename_response_code_traffic_response_status_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendedsite",
            name="footer_links_separator",
            field=models.CharField(default="|", max_length=4),
        ),
    ]
