# Generated by Django 5.1.3 on 2024-11-09 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "base",
            "0003_rename_force_translation_from_default_extendedsite_translate_fields_from_default_language",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="extendedsite",
            old_name="translate_fields_from_default_language",
            new_name="translate_fields_from_default",
        ),
    ]
