# Generated by Django 5.1.3 on 2024-11-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_extendedsite_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extendedsite",
            name="default_page_keywords",
            field=models.TextField(max_length=128),
        ),
        migrations.AlterField(
            model_name="extendedsite",
            name="default_page_keywords_de",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="extendedsite",
            name="default_page_keywords_en",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="extendedsite",
            name="default_page_keywords_es",
            field=models.TextField(max_length=128, null=True),
        ),
    ]
