# Generated by Django 5.1.2 on 2024-10-30 22:39

import auto_prefetch
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_menuitem_remove_pagelink_footer_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagelink",
            name="show_in_navbar",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="pagelink",
            name="menu_item",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.menuitem",
            ),
        ),
    ]
