# Generated by Django 5.1.3 on 2024-11-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_extendedsite_default_page_keywords_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extendedsite",
            name="default_page_description",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="extendedsite",
            name="default_page_keywords",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="extendedsite",
            name="default_page_title",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="extendedsite",
            name="emoji",
            field=models.CharField(max_length=8, null=True),
        ),
    ]
