# Generated by Django 5.1.4 on 2024-12-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_delete_language"),
    ]

    operations = [
        migrations.RenameField(
            model_name="traffic",
            old_name="request_GET",
            new_name="get",
        ),
        migrations.RenameField(
            model_name="traffic",
            old_name="request_POST",
            new_name="headers",
        ),
        migrations.RenameField(
            model_name="traffic",
            old_name="request_method",
            new_name="method",
        ),
        migrations.RenameField(
            model_name="traffic",
            old_name="request_headers",
            new_name="post",
        ),
        migrations.RenameField(
            model_name="traffic",
            old_name="response_status_code",
            new_name="status_code",
        ),
        migrations.RemoveField(
            model_name="traffic",
            name="request_GET_ref",
        ),
        migrations.RemoveField(
            model_name="traffic",
            name="request_country_code",
        ),
        migrations.RemoveField(
            model_name="traffic",
            name="request_path",
        ),
        migrations.RemoveField(
            model_name="traffic",
            name="response_headers",
        ),
        migrations.AddField(
            model_name="traffic",
            name="country_code",
            field=models.CharField(db_index=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="traffic",
            name="path",
            field=models.CharField(db_index=True, default="/", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="traffic",
            name="ref",
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
