# Generated by Django 5.1.3 on 2024-11-23 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_extendedsite_footer_links_separator"),
    ]

    operations = [
        migrations.RenameField(
            model_name="extendedsite",
            old_name="allow_field_translation",
            new_name="allow_translation",
        ),
    ]
