# Generated by Django 5.1.3 on 2024-11-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "base",
            "0005_rename_translate_fields_from_default_extendedsite_allow_field_translation",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="extendedsite",
            name="has_user_home",
            field=models.BooleanField(default=False),
        ),
    ]
