# Generated by Django 5.1.2 on 2024-10-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_pagelink_show_in_navbar_alter_pagelink_menu_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagelink",
            name="url_path",
            field=models.CharField(
                blank=True,
                choices=[
                    ("home", "Home"),
                    ("search", "Search"),
                    ("sitemap", "Sitemap"),
                    ("article-list", "Articles"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
