# Generated by Django 5.1.3 on 2024-11-23 12:20

import auto_prefetch
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_article_can_be_shown_in_home"),
        ("base", "0005_rename_allow_field_translation_extendedsite_allow_translation"),
        ("pages", "0002_alter_page_submodule_folder"),
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="extendedsite",
            name="article_folders",
            field=models.ManyToManyField(to="articles.articlesfolder"),
        ),
        migrations.AlterField(
            model_name="extendedsite",
            name="page_folders",
            field=models.ManyToManyField(to="pages.pagesfolder"),
        ),
        migrations.AlterField(
            model_name="traffic",
            name="site",
            field=auto_prefetch.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="sites.site"
            ),
        ),
        migrations.AlterField(
            model_name="traffic",
            name="user",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
