# Generated by Django 5.1.4 on 2024-12-09 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_topic_allow_translation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="name_eo",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="name_fi",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="name_nn",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="name_sq",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="name_sr",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="slug_eo",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="slug_fi",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="slug_nn",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="slug_sq",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="slug_sr",
        ),
    ]
