# Generated by Django 5.1.2 on 2024-10-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_pagelink_url_path"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pagelink",
            options={"base_manager_name": "prefetch_manager", "ordering": ("order",)},
        ),
        migrations.AddField(
            model_name="pagelink",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
