# Generated by Django 5.1.4 on 2024-12-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_traffic_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="traffic",
            name="ip_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
