# Generated by Django 5.1.3 on 2024-11-13 12:15

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_extendedsite_has_user_home"),
        ("sites", "0005_delete_extendedsite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Traffic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_path", models.CharField(max_length=255)),
                ("request_method", models.CharField(default="GET", max_length=7)),
                ("request_GET", models.TextField(null=True)),
                ("request_GET_ref", models.CharField(max_length=255)),
                ("request_headers", models.TextField(null=True)),
                ("request_country_code", models.CharField(max_length=8)),
                ("response_code", models.PositiveSmallIntegerField(default=200)),
                ("response_headers", models.TextField(null=True)),
                (
                    "time",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="time",
                    ),
                ),
                (
                    "request_site",
                    auto_prefetch.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sites.site",
                    ),
                ),
                (
                    "request_user",
                    auto_prefetch.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
