# Generated by Django 5.1.4 on 2024-12-09 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_remove_topic_name_eo_remove_topic_name_fi_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="name_pt_br",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="slug_pt_br",
        ),
    ]
