# Generated by Django 5.1.4 on 2024-12-24 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_traffic_ip_blocked"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Traffic",
        ),
    ]
