# Generated by Django 5.1.3 on 2024-11-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_traffic"),
    ]

    operations = [
        migrations.AddField(
            model_name="traffic",
            name="request_POST",
            field=models.TextField(null=True),
        ),
    ]
