# Generated by Django 5.1.3 on 2024-11-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_alter_language_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendedsite",
            name="languges",
            field=models.ManyToManyField(to="base.language"),
        ),
    ]
