# Generated by Django 5.1.3 on 2024-11-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_traffic_request_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traffic",
            name="request_GET_ref",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
