# Generated by Django 5.1.2 on 2024-10-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_rename_external_title_pagelink_custom_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagelink",
            name="show_in_footer",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pagelink",
            name="show_in_navbar",
            field=models.BooleanField(default=False),
        ),
    ]
