# Generated by Django 5.1.2 on 2024-10-31 15:25

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_pagelink_show_in_footer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMediaLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=128, null=True)),
                ("title_en", models.CharField(blank=True, max_length=128, null=True)),
                ("title_de", models.CharField(blank=True, max_length=128, null=True)),
                ("title_es", models.CharField(blank=True, max_length=128, null=True)),
                ("url", models.URLField(blank=True, max_length=128, null=True)),
                ("url_en", models.URLField(blank=True, max_length=128, null=True)),
                ("url_de", models.URLField(blank=True, max_length=128, null=True)),
                ("url_es", models.URLField(blank=True, max_length=128, null=True)),
                ("target_blank", models.BooleanField(default=False)),
                ("show", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name="pagelink",
            name="show_in_footer",
        ),
    ]
