# Generated by Django 5.1.3 on 2024-11-23 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_extendedsite_languges"),
    ]

    operations = [
        migrations.RenameField(
            model_name="extendedsite",
            old_name="languges",
            new_name="languages",
        ),
    ]
