# Generated by Django 5.1.2 on 2024-10-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_socialmedialink_remove_pagelink_show_in_footer"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagelink",
            name="emoji",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="pagelink",
            name="emoji_as_title",
            field=models.BooleanField(default=False),
        ),
    ]
