# Generated by Django 5.1.2 on 2024-10-31 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_pagelink_emoji_pagelink_emoji_as_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagelink",
            name="menu_item",
        ),
        migrations.RemoveField(
            model_name="pagelink",
            name="article",
        ),
        migrations.RemoveField(
            model_name="pagelink",
            name="page",
        ),
        migrations.DeleteModel(
            name="SocialMediaLink",
        ),
        migrations.DeleteModel(
            name="MenuItem",
        ),
        migrations.DeleteModel(
            name="PageLink",
        ),
    ]
