# Generated by Django 5.1.3 on 2024-11-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_extendedsite_default_page_description_fr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_description_el",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_description_eo",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_description_fi",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_description_it",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_description_nl",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_description_nn",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_description_pl",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_description_pt",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_description_pt_br",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_description_ru",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_description_sk",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_description_sl",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_description_sq",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_description_sr",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_description_sv",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_description_tr",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_description_uk",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_keywords_el",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_keywords_eo",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_keywords_fi",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_keywords_it",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_keywords_nl",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_keywords_nn",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_keywords_pl",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_keywords_pt",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_keywords_pt_br",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_keywords_ru",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_keywords_sk",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_keywords_sl",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_keywords_sq",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_keywords_sr",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_keywords_sv",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_keywords_tr",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_keywords_uk",
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_title_el",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_title_eo",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_title_fi",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_title_it",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_title_nl",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_title_nn",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_title_pl",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_title_pt",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_title_pt_br",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_title_ru",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_title_sk",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_title_sl",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_title_sq",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_title_sr",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_title_sv",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_title_tr",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_page_title_uk",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
