# Generated by Django 5.1.3 on 2024-11-05 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_siteattrs_delete_website"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="siteattrs",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "Site attribute",
                "verbose_name_plural": "Site attributes",
            },
        ),
        migrations.RemoveField(
            model_name="siteattrs",
            name="_singleton",
        ),
    ]
