# Generated by Django 5.1.3 on 2024-11-24 06:33

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_extendedsite_default_page_description_el_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="extendedsite",
            old_name="languages",
            new_name="rest_languages",
        ),
        migrations.RemoveField(
            model_name="extendedsite",
            name="language",
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="default_language",
            field=auto_prefetch.ForeignKey(
                default="en",
                on_delete=django.db.models.deletion.CASCADE,
                to="base.language",
                verbose_name="Default languages",
            ),
        ),
    ]
