# Generated by Django 5.1.3 on 2024-11-05 20:47

import django.contrib.sites.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_alter_siteattrs_options_remove_siteattrs__singleton"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="siteattrs",
            managers=[
                ("objects", django.contrib.sites.models.SiteManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="siteattrs",
            name="id",
        ),
        migrations.RemoveField(
            model_name="siteattrs",
            name="site",
        ),
        migrations.AddField(
            model_name="siteattrs",
            name="site_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="sites.site",
            ),
            preserve_default=False,
        ),
    ]
