# Generated by Django 5.1.3 on 2024-11-05 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0016_alter_siteattrs_managers_remove_siteattrs_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="siteattrs",
            options={},
        ),
    ]
