# Generated by Django 5.1.3 on 2024-11-24 11:52

import auto_prefetch
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0017_alter_extendedsite_default_language_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extendedsite",
            name="default_language",
            field=auto_prefetch.ForeignKey(
                default="en",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="extendedsites_with_default_languages",
                to="base.language",
                verbose_name="Default languages",
            ),
        ),
        migrations.AlterField(
            model_name="extendedsite",
            name="rest_languages",
            field=models.ManyToManyField(
                related_name="extendedsites_with_rest_languages",
                to="base.language",
                verbose_name="Rest of languages",
            ),
        ),
    ]
