# Generated by Django 5.1.3 on 2024-11-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0018_alter_extendedsite_default_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendedsite",
            name="override_translated_fields",
            field=models.BooleanField(default=False),
        ),
    ]
