# Generated by Django 5.1.3 on 2024-11-24 17:06

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0019_extendedsite_override_translated_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extendedsite",
            name="default_language",
            field=auto_prefetch.ForeignKey(
                default="en",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="extendedsites_with_default_languages",
                to="base.language",
                verbose_name="Default language",
            ),
        ),
    ]
