# Generated by Django 5.1.3 on 2024-12-07 22:36

import django.core.validators
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FooterItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allow_translation", models.BooleanField(default=False)),
                ("override_translated_fields", models.BooleanField(default=False)),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(8),
                        ],
                    ),
                ),
                ("emoji", models.CharField(blank=True, max_length=8, null=True)),
                ("title", models.CharField(max_length=64)),
                ("title_en", models.CharField(max_length=64, null=True)),
                ("title_de", models.CharField(max_length=64, null=True)),
                ("title_es", models.CharField(max_length=64, null=True)),
                ("title_fr", models.CharField(max_length=64, null=True)),
                ("title_el", models.CharField(max_length=64, null=True)),
                ("title_eo", models.CharField(max_length=64, null=True)),
                ("title_fi", models.CharField(max_length=64, null=True)),
                ("title_it", models.CharField(max_length=64, null=True)),
                ("title_nl", models.CharField(max_length=64, null=True)),
                ("title_nn", models.CharField(max_length=64, null=True)),
                ("title_pl", models.CharField(max_length=64, null=True)),
                ("title_pt", models.CharField(max_length=64, null=True)),
                ("title_pt_br", models.CharField(max_length=64, null=True)),
                ("title_ru", models.CharField(max_length=64, null=True)),
                ("title_sk", models.CharField(max_length=64, null=True)),
                ("title_sl", models.CharField(max_length=64, null=True)),
                ("title_sq", models.CharField(max_length=64, null=True)),
                ("title_sr", models.CharField(max_length=64, null=True)),
                ("title_sv", models.CharField(max_length=64, null=True)),
                ("title_tr", models.CharField(max_length=64, null=True)),
                ("title_uk", models.CharField(max_length=64, null=True)),
                (
                    "show_type",
                    models.CharField(
                        choices=[
                            ("user", "👤 For logged user"),
                            ("no_user", "🕵🏻 For anonymous user"),
                            ("always", "👁️ Show always"),
                            ("never", "🫣 Never show"),
                        ],
                        default="always",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="FooterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "show_type",
                    models.CharField(
                        choices=[
                            ("user", "👤 For logged user"),
                            ("no_user", "🕵🏻 For anonymous user"),
                            ("always", "👁️ Show always"),
                            ("never", "🫣 Never show"),
                        ],
                        default="always",
                        max_length=16,
                    ),
                ),
                ("new_tab", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="NavbarLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("emoji", models.CharField(blank=True, max_length=8, null=True)),
                ("show_as_emoji", models.BooleanField(default=False)),
                (
                    "show_type",
                    models.CharField(
                        choices=[
                            ("user", "👤 For logged user"),
                            ("no_user", "🕵🏻 For anonymous user"),
                            ("always", "👁️ Show always"),
                            ("never", "🫣 Never show"),
                        ],
                        default="always",
                        max_length=16,
                    ),
                ),
                ("new_tab", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="SocialMediaLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("url", models.URLField(max_length=256)),
                ("url_en", models.URLField(max_length=256, null=True)),
                ("url_de", models.URLField(max_length=256, null=True)),
                ("url_es", models.URLField(max_length=256, null=True)),
                ("url_fr", models.URLField(max_length=256, null=True)),
                ("url_el", models.URLField(max_length=256, null=True)),
                ("url_eo", models.URLField(max_length=256, null=True)),
                ("url_fi", models.URLField(max_length=256, null=True)),
                ("url_it", models.URLField(max_length=256, null=True)),
                ("url_nl", models.URLField(max_length=256, null=True)),
                ("url_nn", models.URLField(max_length=256, null=True)),
                ("url_pl", models.URLField(max_length=256, null=True)),
                ("url_pt", models.URLField(max_length=256, null=True)),
                ("url_pt_br", models.URLField(max_length=256, null=True)),
                ("url_ru", models.URLField(max_length=256, null=True)),
                ("url_sk", models.URLField(max_length=256, null=True)),
                ("url_sl", models.URLField(max_length=256, null=True)),
                ("url_sq", models.URLField(max_length=256, null=True)),
                ("url_sr", models.URLField(max_length=256, null=True)),
                ("url_sv", models.URLField(max_length=256, null=True)),
                ("url_tr", models.URLField(max_length=256, null=True)),
                ("url_uk", models.URLField(max_length=256, null=True)),
                ("new_tab", models.BooleanField(default=True)),
                (
                    "show_type",
                    models.CharField(
                        choices=[
                            ("user", "👤 For logged user"),
                            ("no_user", "🕵🏻 For anonymous user"),
                            ("always", "👁️ Show always"),
                            ("never", "🫣 Never show"),
                        ],
                        default="always",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
