# Generated by Django 5.1.2 on 2024-10-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="emoji",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
