# Generated by Django 5.1.3 on 2024-11-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="footeritem",
            name="force_translation_from_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="footerlink",
            name="force_translation_from_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="navbarlink",
            name="force_translation_from_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="socialmedialink",
            name="force_translation_from_default",
            field=models.BooleanField(default=False),
        ),
    ]
