# Generated by Django 5.1.4 on 2024-12-09 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footeritem",
            name="title_eo",
        ),
        migrations.RemoveField(
            model_name="footeritem",
            name="title_fi",
        ),
        migrations.RemoveField(
            model_name="footeritem",
            name="title_nn",
        ),
        migrations.RemoveField(
            model_name="footeritem",
            name="title_sq",
        ),
        migrations.RemoveField(
            model_name="footeritem",
            name="title_sr",
        ),
        migrations.RemoveField(
            model_name="socialmedialink",
            name="url_eo",
        ),
        migrations.RemoveField(
            model_name="socialmedialink",
            name="url_fi",
        ),
        migrations.RemoveField(
            model_name="socialmedialink",
            name="url_nn",
        ),
        migrations.RemoveField(
            model_name="socialmedialink",
            name="url_sq",
        ),
        migrations.RemoveField(
            model_name="socialmedialink",
            name="url_sr",
        ),
    ]
