# Generated by Django 5.1.2 on 2024-10-31 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0002_menuitem_emoji"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pagelink",
            old_name="target_blank",
            new_name="new_tab",
        ),
        migrations.RenameField(
            model_name="socialmedialink",
            old_name="target_blank",
            new_name="new_tab",
        ),
    ]
