# Generated by Django 5.1.3 on 2024-11-09 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0002_footeritem_force_translation_from_default_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="footeritem",
            old_name="force_translation_from_default",
            new_name="translate_fields_from_default_language",
        ),
        migrations.RenameField(
            model_name="footerlink",
            old_name="force_translation_from_default",
            new_name="translate_fields_from_default_language",
        ),
        migrations.RenameField(
            model_name="navbarlink",
            old_name="force_translation_from_default",
            new_name="translate_fields_from_default_language",
        ),
        migrations.RenameField(
            model_name="socialmedialink",
            old_name="force_translation_from_default",
            new_name="translate_fields_from_default_language",
        ),
    ]
