# Generated by Django 5.1.2 on 2024-11-01 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0003_rename_target_blank_pagelink_new_tab_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagelink",
            name="emoji_as_title",
        ),
    ]
