# Generated by Django 5.1.3 on 2024-11-18 19:30

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0001_initial"),
        ("menus", "0003_alter_navbarlink_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footerlink",
            name="link",
            field=auto_prefetch.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="links.link"
            ),
        ),
    ]
