# Generated by Django 5.1.3 on 2024-11-09 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "menus",
            "0003_rename_force_translation_from_default_footeritem_translate_fields_from_default_language_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="footeritem",
            old_name="translate_fields_from_default_language",
            new_name="translate_fields_from_default",
        ),
        migrations.RenameField(
            model_name="footerlink",
            old_name="translate_fields_from_default_language",
            new_name="translate_fields_from_default",
        ),
        migrations.RenameField(
            model_name="navbarlink",
            old_name="translate_fields_from_default_language",
            new_name="translate_fields_from_default",
        ),
        migrations.RenameField(
            model_name="socialmedialink",
            old_name="translate_fields_from_default_language",
            new_name="translate_fields_from_default",
        ),
    ]
