# Generated by Django 5.1.4 on 2024-12-09 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0004_remove_footeritem_title_pt_br_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footeritem",
            name="title_uk",
        ),
        migrations.RemoveField(
            model_name="socialmedialink",
            name="url_uk",
        ),
    ]
