# Generated by Django 5.1.2 on 2024-11-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0004_remove_pagelink_emoji_as_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagelink",
            name="show_as_emoji",
            field=models.BooleanField(default=False),
        ),
    ]
