# Generated by Django 5.1.3 on 2024-11-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "menus",
            "0004_rename_translate_fields_from_default_language_footeritem_translate_fields_from_default_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="footeritem",
            old_name="translate_fields_from_default",
            new_name="allow_field_translation",
        ),
        migrations.RenameField(
            model_name="footerlink",
            old_name="translate_fields_from_default",
            new_name="allow_field_translation",
        ),
        migrations.RenameField(
            model_name="navbarlink",
            old_name="translate_fields_from_default",
            new_name="allow_field_translation",
        ),
        migrations.RenameField(
            model_name="socialmedialink",
            old_name="translate_fields_from_default",
            new_name="allow_field_translation",
        ),
    ]
