# Generated by Django 5.1.3 on 2024-11-10 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "menus",
            "0005_rename_translate_fields_from_default_footeritem_allow_field_translation_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="socialmedialink",
            options={"base_manager_name": "prefetch_manager", "ordering": ("order",)},
        ),
    ]
