# Generated by Django 5.1.2 on 2024-11-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0005_pagelink_show_as_emoji"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pagelink",
            old_name="url_path",
            new_name="django_url_path",
        ),
        migrations.AlterField(
            model_name="pagelink",
            name="external_url",
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
