# Generated by Django 5.1.3 on 2024-11-23 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0005_rename_site_footerlink_sites"),
    ]

    operations = [
        migrations.RenameField(
            model_name="footeritem",
            old_name="allow_field_translation",
            new_name="allow_translation",
        ),
    ]
