# Generated by Django 5.1.3 on 2024-11-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0006_rename_allow_field_translation_footeritem_allow_translation"),
    ]

    operations = [
        migrations.AddField(
            model_name="footeritem",
            name="title_fr",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="socialmedialink",
            name="url_fr",
            field=models.URLField(max_length=256, null=True),
        ),
    ]
