# Generated by Django 5.1.2 on 2024-11-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0006_rename_url_path_pagelink_django_url_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmedialink",
            name="new_tab",
            field=models.BooleanField(default=True),
        ),
    ]
