# Generated by Django 5.1.4 on 2024-12-14 17:05

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0007_link_custom_title_uk"),
        ("menus", "0006_footeritem_title_uk_socialmedialink_url_uk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footerlink",
            name="link",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="links.link"
            ),
        ),
        migrations.AlterField(
            model_name="navbarlink",
            name="link",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="links.link"
            ),
        ),
    ]
