# Generated by Django 5.1.3 on 2024-11-11 20:20

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0003_remove_link_new_tab"),
        ("menus", "0007_alter_footeritem_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="navbarlink",
            name="link",
            field=auto_prefetch.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="links.link"
            ),
        ),
    ]
