# Generated by Django 5.1.3 on 2024-11-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0007_footeritem_title_fr_socialmedialink_url_fr"),
    ]

    operations = [
        migrations.AddField(
            model_name="footeritem",
            name="title_el",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="footeritem",
            name="title_eo",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="footeritem",
            name="title_fi",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="footeritem",
            name="title_it",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="footeritem",
            name="title_nl",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="footeritem",
            name="title_nn",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="footeritem",
            name="title_pl",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="footeritem",
            name="title_pt",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="footeritem",
            name="title_pt_br",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="footeritem",
            name="title_ru",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="footeritem",
            name="title_sk",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="footeritem",
            name="title_sl",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="footeritem",
            name="title_sq",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="footeritem",
            name="title_sr",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="footeritem",
            name="title_sv",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="footeritem",
            name="title_tr",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="footeritem",
            name="title_uk",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="socialmedialink",
            name="url_el",
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="socialmedialink",
            name="url_eo",
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="socialmedialink",
            name="url_fi",
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="socialmedialink",
            name="url_it",
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="socialmedialink",
            name="url_nl",
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="socialmedialink",
            name="url_nn",
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="socialmedialink",
            name="url_pl",
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="socialmedialink",
            name="url_pt",
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="socialmedialink",
            name="url_pt_br",
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="socialmedialink",
            name="url_ru",
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="socialmedialink",
            name="url_sk",
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="socialmedialink",
            name="url_sl",
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="socialmedialink",
            name="url_sq",
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="socialmedialink",
            name="url_sr",
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="socialmedialink",
            name="url_sv",
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="socialmedialink",
            name="url_tr",
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="socialmedialink",
            name="url_uk",
            field=models.URLField(max_length=256, null=True),
        ),
    ]
