# Generated by Django 5.1.3 on 2024-11-24 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0008_footeritem_title_el_footeritem_title_eo_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="footeritem",
            old_name="site",
            new_name="sites",
        ),
        migrations.RenameField(
            model_name="socialmedialink",
            old_name="site",
            new_name="sites",
        ),
    ]
