# Generated by Django 5.1.2 on 2024-11-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0008_footeritem_remove_pagelink_menu_item_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footerlink",
            name="emoji",
        ),
        migrations.AlterField(
            model_name="footerlink",
            name="show",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="navbarlink",
            name="show",
            field=models.BooleanField(default=True),
        ),
    ]
