# Generated by Django 5.1.3 on 2024-11-11 20:23

import auto_prefetch
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0003_remove_link_new_tab"),
        ("menus", "0008_navbarlink_link"),
        # ("sites", "0005_delete_extendedsite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="navbarlink",
            name="link",
        ),
        migrations.CreateModel(
            name="NewNavbarLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("emoji", models.CharField(blank=True, max_length=8, null=True)),
                ("show_as_emoji", models.BooleanField(default=False)),
                (
                    "show_type",
                    models.CharField(
                        choices=[
                            ("user", "👤 For logged user"),
                            ("no_user", "🕵🏻 For anonymous user"),
                            ("always", "👁️ Show always"),
                            ("never", "🫣 Never show"),
                        ],
                        default="always",
                        max_length=16,
                    ),
                ),
                (
                    "link",
                    auto_prefetch.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="links.link",
                    ),
                ),
                ("site", models.ManyToManyField(to="sites.site")),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
