# Generated by Django 5.1.3 on 2024-11-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0009_remove_navbarlink_link_newnavbarlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="newnavbarlink",
            name="new_tab",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="NavbarLink",
        ),
    ]
