# Generated by Django 5.1.2 on 2024-11-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0009_remove_footerlink_emoji_alter_footerlink_show_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmedialink",
            name="url",
            field=models.URLField(max_length=128),
        ),
        migrations.AlterField(
            model_name="socialmedialink",
            name="url_de",
            field=models.URLField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="socialmedialink",
            name="url_en",
            field=models.URLField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="socialmedialink",
            name="url_es",
            field=models.URLField(max_length=128, null=True),
        ),
    ]
