# Generated by Django 5.1.3 on 2024-11-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0009_rename_site_footeritem_sites_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="footeritem",
            name="override_translated_fields",
            field=models.BooleanField(default=False),
        ),
    ]
