# Generated by Django 5.1.2 on 2024-11-02 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0010_alter_socialmedialink_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socialmedialink",
            name="title",
        ),
        migrations.RemoveField(
            model_name="socialmedialink",
            name="title_de",
        ),
        migrations.RemoveField(
            model_name="socialmedialink",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="socialmedialink",
            name="title_es",
        ),
    ]
