# Generated by Django 5.1.3 on 2024-11-11 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0003_remove_link_new_tab"),
        ("menus", "0010_newnavbarlink_new_tab_delete_navbarlink"),
       # ("sites", "0005_delete_extendedsite"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NewNavbarLink",
            new_name="NavbarLink",
        ),
    ]
