# Generated by Django 5.1.2 on 2024-11-02 06:52

import auto_prefetch
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0011_remove_socialmedialink_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footerlink",
            name="footer_item",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="menus.footeritem",
            ),
        ),
        migrations.AlterField(
            model_name="socialmedialink",
            name="url",
            field=models.URLField(max_length=256),
        ),
        migrations.AlterField(
            model_name="socialmedialink",
            name="url_de",
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="socialmedialink",
            name="url_en",
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="socialmedialink",
            name="url_es",
            field=models.URLField(max_length=256, null=True),
        ),
    ]
