# Generated by Django 5.1.3 on 2024-11-11 20:33

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0003_remove_link_new_tab"),
        ("menus", "0011_rename_newnavbarlink_navbarlink"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footerlink",
            name="allow_field_translation",
        ),
        migrations.RemoveField(
            model_name="footerlink",
            name="article",
        ),
        migrations.RemoveField(
            model_name="footerlink",
            name="custom_title",
        ),
        migrations.RemoveField(
            model_name="footerlink",
            name="custom_title_de",
        ),
        migrations.RemoveField(
            model_name="footerlink",
            name="custom_title_en",
        ),
        migrations.RemoveField(
            model_name="footerlink",
            name="custom_title_es",
        ),
        migrations.RemoveField(
            model_name="footerlink",
            name="django_url_path",
        ),
        migrations.RemoveField(
            model_name="footerlink",
            name="external_url",
        ),
        migrations.RemoveField(
            model_name="footerlink",
            name="page",
        ),
        migrations.RemoveField(
            model_name="footerlink",
            name="plan",
        ),
        migrations.AddField(
            model_name="footerlink",
            name="link",
            field=auto_prefetch.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="links.link"
            ),
        ),
    ]
