# Generated by Django 5.1.2 on 2024-11-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0012_alter_footerlink_footer_item_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footerlink",
            name="django_url_path",
            field=models.CharField(
                blank=True,
                choices=[
                    ("home", "Home"),
                    ("search", "Search"),
                    ("article_list", "Articles"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="navbarlink",
            name="django_url_path",
            field=models.CharField(
                blank=True,
                choices=[
                    ("home", "Home"),
                    ("search", "Search"),
                    ("article_list", "Articles"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
