# Generated by Django 5.1.2 on 2024-11-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0013_alter_footerlink_django_url_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmedialink",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="footerlink",
            name="django_url_path",
            field=models.CharField(
                blank=True,
                choices=[
                    ("home", "Home"),
                    ("search", "Search"),
                    ("sitemap", "Sitemap"),
                    ("article_list", "Articles"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="navbarlink",
            name="django_url_path",
            field=models.CharField(
                blank=True,
                choices=[
                    ("home", "Home"),
                    ("search", "Search"),
                    ("sitemap", "Sitemap"),
                    ("article_list", "Articles"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
