# Generated by Django 5.1.3 on 2024-11-13 03:04

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0006_alter_link_unique_together"),
        ("menus", "0013_remove_socialmedialink_allow_field_translation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footerlink",
            name="link",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="links.link"
            ),
        ),
        migrations.AlterField(
            model_name="navbarlink",
            name="link",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="links.link"
            ),
        ),
    ]
