# Generated by Django 5.1.2 on 2024-11-03 10:58

import auto_prefetch
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0015_alter_footeritem_order_alter_footerlink_order_and_more"),
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="footerlink",
            name="plan",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="plans.plan",
            ),
        ),
        migrations.AddField(
            model_name="navbarlink",
            name="plan",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="plans.plan",
            ),
        ),
        migrations.AlterField(
            model_name="footerlink",
            name="django_url_path",
            field=models.CharField(
                blank=True,
                choices=[
                    ("home", "Home"),
                    ("search", "Search"),
                    ("sitemap", "Sitemap"),
                    ("article_list", "Articles"),
                    ("plan_list", "Plans"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="navbarlink",
            name="django_url_path",
            field=models.CharField(
                blank=True,
                choices=[
                    ("home", "Home"),
                    ("search", "Search"),
                    ("sitemap", "Sitemap"),
                    ("article_list", "Articles"),
                    ("plan_list", "Plans"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
