# Generated by Django 5.1.2 on 2024-11-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0016_footerlink_plan_navbarlink_plan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="footerlink",
            name="show_type",
            field=models.CharField(
                choices=[
                    ("user", "Show if user is authenticated"),
                    ("no_user", "Show if user is not authenticated"),
                    ("always", "Show always"),
                    ("never", "Never show"),
                ],
                default="always",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="navbarlink",
            name="show_type",
            field=models.CharField(
                choices=[
                    ("user", "Show if user is authenticated"),
                    ("no_user", "Show if user is not authenticated"),
                    ("always", "Show always"),
                    ("never", "Never show"),
                ],
                default="always",
                max_length=16,
            ),
        ),
    ]
