# Generated by Django 5.1.2 on 2024-11-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0018_remove_footeritem_show_remove_footerlink_show_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footeritem",
            name="show_type",
            field=models.CharField(
                choices=[
                    ("user", "👤 When user is authenticated"),
                    ("no_user", "🕵🏻 When user is not authenticated"),
                    ("always", "👁️ Show always"),
                    ("never", "🫣 Never show"),
                ],
                default="always",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="footerlink",
            name="django_url_path",
            field=models.CharField(
                blank=True,
                choices=[
                    ("home", "Home"),
                    ("search", "Search"),
                    ("sitemap", "Sitemap"),
                    ("article_list", "Articles"),
                    ("plan_list", "Plans"),
                    ("account_login", "Sign In"),
                    ("account_signup", "Sign Up"),
                    ("user_dashboard", "Account"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="footerlink",
            name="show_type",
            field=models.CharField(
                choices=[
                    ("user", "👤 When user is authenticated"),
                    ("no_user", "🕵🏻 When user is not authenticated"),
                    ("always", "👁️ Show always"),
                    ("never", "🫣 Never show"),
                ],
                default="always",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="navbarlink",
            name="django_url_path",
            field=models.CharField(
                blank=True,
                choices=[
                    ("home", "Home"),
                    ("search", "Search"),
                    ("sitemap", "Sitemap"),
                    ("article_list", "Articles"),
                    ("plan_list", "Plans"),
                    ("account_login", "Sign In"),
                    ("account_signup", "Sign Up"),
                    ("user_dashboard", "Account"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="navbarlink",
            name="show_type",
            field=models.CharField(
                choices=[
                    ("user", "👤 When user is authenticated"),
                    ("no_user", "🕵🏻 When user is not authenticated"),
                    ("always", "👁️ Show always"),
                    ("never", "🫣 Never show"),
                ],
                default="always",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="socialmedialink",
            name="show_type",
            field=models.CharField(
                choices=[
                    ("user", "👤 When user is authenticated"),
                    ("no_user", "🕵🏻 When user is not authenticated"),
                    ("always", "👁️ Show always"),
                    ("never", "🫣 Never show"),
                ],
                default="always",
                max_length=16,
            ),
        ),
    ]
