# Generated by Django 5.1.2 on 2024-11-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0019_alter_footeritem_show_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footeritem",
            name="show_type",
            field=models.CharField(
                choices=[
                    ("user", "👤 For logged user"),
                    ("no_user", "🕵🏻 For anonymous user"),
                    ("always", "👁️ Show always"),
                    ("never", "🫣 Never show"),
                ],
                default="always",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="footerlink",
            name="show_type",
            field=models.CharField(
                choices=[
                    ("user", "👤 For logged user"),
                    ("no_user", "🕵🏻 For anonymous user"),
                    ("always", "👁️ Show always"),
                    ("never", "🫣 Never show"),
                ],
                default="always",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="navbarlink",
            name="show_type",
            field=models.CharField(
                choices=[
                    ("user", "👤 For logged user"),
                    ("no_user", "🕵🏻 For anonymous user"),
                    ("always", "👁️ Show always"),
                    ("never", "🫣 Never show"),
                ],
                default="always",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="socialmedialink",
            name="show_type",
            field=models.CharField(
                choices=[
                    ("user", "👤 For logged user"),
                    ("no_user", "🕵🏻 For anonymous user"),
                    ("always", "👁️ Show always"),
                    ("never", "🫣 Never show"),
                ],
                default="always",
                max_length=16,
            ),
        ),
    ]
