# Generated by Django 5.1.4 on 2024-12-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_alter_client_country_delete_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="user_agent",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
