# Generated by Django 5.1.4 on 2024-12-24 17:13

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_client_user_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="client",
            field=auto_prefetch.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.client",
            ),
            preserve_default=False,
        ),
    ]
