# Generated by Django 5.1.4 on 2024-12-29 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0015_remove_request_path"),
    ]

    operations = [
        migrations.RenameField(
            model_name="request",
            old_name="path_obj",
            new_name="path",
        ),
    ]
