# Generated by Django 5.1.4 on 2024-12-29 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0017_alter_client_geoinfo_delete_geoinfo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SpamPath",
        ),
    ]
