# Generated by Django 5.1.4 on 2024-12-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0018_delete_spampath"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="dark_theme",
            field=models.BooleanField(default=True),
        ),
    ]
