# Generated by Django 5.1.7 on 2025-03-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tex", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="yearlyholidaycalender",
            name="image1",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="yearlyholidaycalender",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
