# Generated by Django 5.2 on 2025-05-21 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tex", "0002_alter_englishquizlection_created_on_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="englishquizlection",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="englishquizlection",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="yearlyholidaycalender",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="yearlyholidaycalender",
            name="updated_on",
        ),
        migrations.AddField(
            model_name="englishquizlection",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848231, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="englishquizlection",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848323, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="yearlyholidaycalender",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848231, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="yearlyholidaycalender",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848323, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
