# Generated by Django 5.1.7 on 2025-03-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tex", "0003_yearlyholidaycalender_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="yearlyholidaycalender",
            name="title",
        ),
        migrations.AddField(
            model_name="yearlyholidaycalender",
            name="lang",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("de", "German"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("el", "Greek"),
                    ("it", "Italian"),
                    ("nl", "Dutch"),
                    ("pl", "Polish"),
                    ("pt", "Portuguese"),
                    ("ru", "Russian"),
                    ("sk", "Slovak"),
                    ("sl", "Slovenian"),
                    ("sv", "Swedish"),
                    ("tr", "Turkish"),
                    ("uk", "Ukrainian"),
                ],
                default="en",
                max_length=2,
            ),
            preserve_default=False,
        ),
    ]
