# Generated by Django 5.1.7 on 2025-03-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tex", "0004_remove_yearlyholidaycalender_title_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="yearlyholidaycalender",
            unique_together={("year", "country", "subdiv", "lang")},
        ),
    ]
