# Generated by Django 5.2 on 2025-05-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tex", "0004_alter_englishquizlection_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="englishquizlection",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="englishquizlection",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="yearlyholidaycalender",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="yearlyholidaycalender",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
