# Generated by Django 5.1.7 on 2025-03-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tex", "0006_alter_yearlyholidaycalender_subdiv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yearlyholidaycalender",
            name="subdiv",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
