# Generated by Django 5.1.7 on 2025-03-23 19:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tex", "0007_alter_yearlyholidaycalender_subdiv"),
    ]

    operations = [
        migrations.AddField(
            model_name="yearlyholidaycalender",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="yearlyholidaycalender",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
