# Generated by Django 5.1.7 on 2025-03-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tex", "0008_yearlyholidaycalender_created_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yearlyholidaycalender",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="calendars/"),
        ),
        migrations.AlterField(
            model_name="yearlyholidaycalender",
            name="image1",
            field=models.ImageField(blank=True, null=True, upload_to="calendars/"),
        ),
        migrations.AlterField(
            model_name="yearlyholidaycalender",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to="calendars/"),
        ),
        migrations.AlterField(
            model_name="yearlyholidaycalender",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to="calendars/"),
        ),
    ]
