# Generated by Django 5.1.7 on 2025-03-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tex", "0009_alter_yearlyholidaycalender_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yearlyholidaycalender",
            name="lang",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("de", "German"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("it", "Italian"),
                    ("nl", "Dutch"),
                    ("pt", "Portuguese"),
                ],
                max_length=2,
            ),
        ),
    ]
