# Generated by Django 5.1 on 2025-03-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tex", "0011_englishquizlection"),
    ]

    operations = [
        migrations.AddField(
            model_name="englishquizlection",
            name="print",
            field=models.FileField(
                blank=True, null=True, upload_to="english-quiz-lections/"
            ),
        ),
    ]
