# Generated by Django 5.2 on 2025-05-27 04:10

import auto_prefetch
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.manager
import one.candidates.models
import one.db
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CandidateProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("de", "German"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("pt", "Portuguese"),
                        ],
                        db_index=True,
                        default="en",
                        max_length=4,
                    ),
                ),
                (
                    "languages",
                    one.db.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("en", "English"),
                                ("de", "German"),
                                ("es", "Spanish"),
                                ("fr", "French"),
                                ("it", "Italian"),
                                ("nl", "Dutch"),
                                ("pt", "Portuguese"),
                            ],
                            max_length=8,
                        ),
                        blank=True,
                        db_index=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("m", "male"), ("f", "female")],
                        max_length=64,
                        null=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                (
                    "full_name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.text.Concat(
                            "first_name", models.Value(" "), "last_name"
                        ),
                        output_field=models.CharField(max_length=128),
                    ),
                ),
                ("job_title", models.CharField(max_length=64)),
                ("email", models.EmailField(max_length=64)),
                ("phone", models.CharField(max_length=32)),
                ("location", models.CharField(blank=True, max_length=32, null=True)),
                ("linkedin", models.CharField(blank=True, max_length=32, null=True)),
                ("github", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "website_label",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("website_url", models.URLField(blank=True, max_length=128, null=True)),
                ("about", models.TextField(blank=True, null=True)),
                (
                    "why_me",
                    models.CharField(
                        blank=True,
                        default="Why Should You Hire Me?",
                        max_length=128,
                        null=True,
                    ),
                ),
                ("latex_pt", models.PositiveSmallIntegerField(default=12)),
                ("photo_width", models.CharField(default="0.7", max_length=3)),
                ("margin_left", models.CharField(default="25mm", max_length=5)),
                ("margin_right", models.CharField(default="20mm", max_length=5)),
                ("margin_top", models.CharField(default="20mm", max_length=5)),
                ("margin_bottom", models.CharField(default="20mm", max_length=5)),
                (
                    "about_label",
                    models.CharField(default="Professional Profile", max_length=32),
                ),
                (
                    "experience_label",
                    models.CharField(default="Work Experience", max_length=32),
                ),
                (
                    "education_label",
                    models.CharField(default="Education", max_length=32),
                ),
                (
                    "skill_label",
                    models.CharField(default="Technical Skills", max_length=32),
                ),
                (
                    "certificate_label",
                    models.CharField(default="Certifications", max_length=32),
                ),
                (
                    "language_label",
                    models.CharField(default="Languages", max_length=32),
                ),
                ("project_label", models.CharField(default="Projects", max_length=32)),
                (
                    "signature",
                    models.ImageField(
                        null=True,
                        upload_to=one.candidates.models.CandidateProfile.get_upload_path,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        null=True,
                        upload_to=one.candidates.models.CandidateProfile.get_upload_path,
                    ),
                ),
                (
                    "docs",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=one.candidates.models.CandidateProfile.get_upload_path,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CandidateExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company_name", models.CharField(max_length=64)),
                ("job_title", models.CharField(max_length=64)),
                ("from_to", models.CharField(max_length=32)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "profile",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidates.candidateprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CandidateCv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tex_template",
                    models.CharField(
                        choices=[("tex/cvs/alice/cv.tex", "Alice")], max_length=64
                    ),
                ),
                ("rendered_text", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=one.candidates.models.CandidateCv.get_upload_path,
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=one.candidates.models.CandidateCv.get_upload_path,
                    ),
                ),
                ("pdf_time", models.FloatField(default=0)),
                ("image_time", models.FloatField(default=0)),
                ("render_time", models.FloatField(default=0)),
                ("auto_created", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidates.candidateprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CandidateApplicationLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("area", django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                (
                    "profile",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidates.candidateprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CandiateProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=64)),
                ("url", models.URLField(blank=True, max_length=128, null=True)),
                ("from_to", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "profile",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidates.candidateprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "profile",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidates.candidateprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("institution_name", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=64)),
                ("from_to", models.CharField(max_length=32)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "profile",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidates.candidateprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="LanguageSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "profile",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidates.candidateprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64)),
                (
                    "profile",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidates.candidateprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
