# Generated by Django 5.2 on 2025-06-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="receive_job_alerts",
            field=models.BooleanField(default=True),
        ),
    ]
