# Generated by Django 5.2 on 2025-06-15 18:44

import auto_prefetch
import django.db.models.deletion
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidates", "0001_initial"),
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="user",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="candidatelanguageskill",
            name="profile",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="candidates.candidateprofile",
            ),
        ),
        migrations.AddField(
            model_name="candidatejobalert",
            name="profile",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="candidates.candidateprofile",
            ),
        ),
        migrations.AddField(
            model_name="candidateexperience",
            name="profile",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="candidates.candidateprofile",
            ),
        ),
        migrations.AddField(
            model_name="candidateeducation",
            name="profile",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="candidates.candidateprofile",
            ),
        ),
        migrations.AddField(
            model_name="candidatecertificate",
            name="profile",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="candidates.candidateprofile",
            ),
        ),
        migrations.AddField(
            model_name="candidateproject",
            name="profile",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="candidates.candidateprofile",
            ),
        ),
        migrations.AddField(
            model_name="candidateskill",
            name="profile",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="candidates.candidateprofile",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="job",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="companies.job"
            ),
        ),
        migrations.AddField(
            model_name="texcv",
            name="profile",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="candidates.candidateprofile",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="cv",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="candidates.texcv"
            ),
        ),
    ]
