# Generated by Django 5.2 on 2025-06-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="about_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="about_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="about_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="about_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="about_it",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="about_label_de",
            field=models.CharField(
                default="Professional Profile", max_length=32, null=True
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="about_label_en",
            field=models.CharField(
                default="Professional Profile", max_length=32, null=True
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="about_label_es",
            field=models.CharField(
                default="Professional Profile", max_length=32, null=True
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="about_label_fr",
            field=models.CharField(
                default="Professional Profile", max_length=32, null=True
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="about_label_it",
            field=models.CharField(
                default="Professional Profile", max_length=32, null=True
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="about_label_nl",
            field=models.CharField(
                default="Professional Profile", max_length=32, null=True
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="about_label_pt",
            field=models.CharField(
                default="Professional Profile", max_length=32, null=True
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="about_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="about_pt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="certificate_label_de",
            field=models.CharField(default="Certifications", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="certificate_label_en",
            field=models.CharField(default="Certifications", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="certificate_label_es",
            field=models.CharField(default="Certifications", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="certificate_label_fr",
            field=models.CharField(default="Certifications", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="certificate_label_it",
            field=models.CharField(default="Certifications", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="certificate_label_nl",
            field=models.CharField(default="Certifications", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="certificate_label_pt",
            field=models.CharField(default="Certifications", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="coverletter_body_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="coverletter_body_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="coverletter_body_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="coverletter_body_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="coverletter_body_it",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="coverletter_body_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="coverletter_body_pt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="education_label_de",
            field=models.CharField(default="Education", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="education_label_en",
            field=models.CharField(default="Education", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="education_label_es",
            field=models.CharField(default="Education", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="education_label_fr",
            field=models.CharField(default="Education", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="education_label_it",
            field=models.CharField(default="Education", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="education_label_nl",
            field=models.CharField(default="Education", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="education_label_pt",
            field=models.CharField(default="Education", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="experience_label_de",
            field=models.CharField(default="Work Experience", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="experience_label_en",
            field=models.CharField(default="Work Experience", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="experience_label_es",
            field=models.CharField(default="Work Experience", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="experience_label_fr",
            field=models.CharField(default="Work Experience", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="experience_label_it",
            field=models.CharField(default="Work Experience", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="experience_label_nl",
            field=models.CharField(default="Work Experience", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="experience_label_pt",
            field=models.CharField(default="Work Experience", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="job_title_de",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="job_title_en",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="job_title_es",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="job_title_fr",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="job_title_it",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="job_title_nl",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="job_title_pt",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="language_label_de",
            field=models.CharField(default="Languages", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="language_label_en",
            field=models.CharField(default="Languages", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="language_label_es",
            field=models.CharField(default="Languages", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="language_label_fr",
            field=models.CharField(default="Languages", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="language_label_it",
            field=models.CharField(default="Languages", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="language_label_nl",
            field=models.CharField(default="Languages", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="language_label_pt",
            field=models.CharField(default="Languages", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="location_de",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="location_en",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="location_es",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="location_fr",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="location_it",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="location_nl",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="location_pt",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="project_label_de",
            field=models.CharField(default="Projects", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="project_label_en",
            field=models.CharField(default="Projects", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="project_label_es",
            field=models.CharField(default="Projects", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="project_label_fr",
            field=models.CharField(default="Projects", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="project_label_it",
            field=models.CharField(default="Projects", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="project_label_nl",
            field=models.CharField(default="Projects", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="project_label_pt",
            field=models.CharField(default="Projects", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="skill_label_de",
            field=models.CharField(
                default="Technical Skills", max_length=32, null=True
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="skill_label_en",
            field=models.CharField(
                default="Technical Skills", max_length=32, null=True
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="skill_label_es",
            field=models.CharField(
                default="Technical Skills", max_length=32, null=True
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="skill_label_fr",
            field=models.CharField(
                default="Technical Skills", max_length=32, null=True
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="skill_label_it",
            field=models.CharField(
                default="Technical Skills", max_length=32, null=True
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="skill_label_nl",
            field=models.CharField(
                default="Technical Skills", max_length=32, null=True
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="skill_label_pt",
            field=models.CharField(
                default="Technical Skills", max_length=32, null=True
            ),
        ),
    ]
