# Generated by Django 5.2 on 2025-06-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "candidates",
            "0002_candidateprofile_about_de_candidateprofile_about_en_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateprofile",
            name="location",
            field=models.CharField(default="Bern", max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="location_de",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="location_en",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="location_es",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="location_fr",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="location_it",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="location_nl",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="location_pt",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
