# Generated by Django 5.2 on 2025-06-14 05:09

import django.core.validators
import one.db
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0002_candidateprofile_receive_job_alerts"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatecertificate",
            name="name_de",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="candidatecertificate",
            name="name_en",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="candidatecertificate",
            name="name_es",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="candidatecertificate",
            name="name_fr",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="candidatecertificate",
            name="name_it",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="candidatecertificate",
            name="name_nl",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="candidatecertificate",
            name="name_pt",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="candidateeducation",
            name="description_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateeducation",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateeducation",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateeducation",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateeducation",
            name="description_it",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateeducation",
            name="description_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateeducation",
            name="description_pt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateeducation",
            name="from_to_de",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateeducation",
            name="from_to_en",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateeducation",
            name="from_to_es",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateeducation",
            name="from_to_fr",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateeducation",
            name="from_to_it",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateeducation",
            name="from_to_nl",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateeducation",
            name="from_to_pt",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateeducation",
            name="title_de",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateeducation",
            name="title_en",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateeducation",
            name="title_es",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateeducation",
            name="title_fr",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateeducation",
            name="title_it",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateeducation",
            name="title_nl",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateeducation",
            name="title_pt",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateexperience",
            name="description_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateexperience",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateexperience",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateexperience",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateexperience",
            name="description_it",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateexperience",
            name="description_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateexperience",
            name="description_pt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateexperience",
            name="from_to_de",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateexperience",
            name="from_to_en",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateexperience",
            name="from_to_es",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateexperience",
            name="from_to_fr",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateexperience",
            name="from_to_it",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateexperience",
            name="from_to_nl",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateexperience",
            name="from_to_pt",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateexperience",
            name="job_title_de",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateexperience",
            name="job_title_en",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateexperience",
            name="job_title_es",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateexperience",
            name="job_title_fr",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateexperience",
            name="job_title_it",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateexperience",
            name="job_title_nl",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateexperience",
            name="job_title_pt",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidatejobalert",
            name="languages",
            field=one.db.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("en", "English"),
                        ("de", "German"),
                        ("es", "Spanish"),
                        ("fr", "French"),
                        ("it", "Italian"),
                        ("nl", "Dutch"),
                        ("pt", "Portuguese"),
                    ],
                    max_length=8,
                ),
                blank=True,
                db_index=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="candidateproject",
            name="description_de",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="candidateproject",
            name="description_en",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="candidateproject",
            name="description_es",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="candidateproject",
            name="description_fr",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="candidateproject",
            name="description_it",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="candidateproject",
            name="description_nl",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="candidateproject",
            name="description_pt",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="candidateproject",
            name="from_to_de",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateproject",
            name="from_to_en",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateproject",
            name="from_to_es",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateproject",
            name="from_to_fr",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateproject",
            name="from_to_it",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateproject",
            name="from_to_nl",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateproject",
            name="from_to_pt",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="candidateproject",
            name="title_de",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateproject",
            name="title_en",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateproject",
            name="title_es",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateproject",
            name="title_fr",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateproject",
            name="title_it",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateproject",
            name="title_nl",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateproject",
            name="title_pt",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateskill",
            name="level",
            field=models.PositiveSmallIntegerField(
                default=3,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="candidateskill",
            name="name_de",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateskill",
            name="name_en",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateskill",
            name="name_es",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateskill",
            name="name_fr",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateskill",
            name="name_it",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateskill",
            name="name_nl",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="candidateskill",
            name="name_pt",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
