# Generated by Django 5.2 on 2025-06-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
