# Generated by Django 5.2 on 2025-06-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0003_alter_candidateprofile_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="coverletter_latex_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
