# Generated by Django 5.2 on 2025-06-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0004_remove_candidatejobalert_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateskill",
            name="level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("learner", "Learner"),
                    ("intermediate", "Intermediate"),
                    ("proficient", "Proficient"),
                    ("advanced", "Advanced"),
                    ("expert", "Expert"),
                ],
                default="intermediate",
                max_length=16,
            ),
        ),
    ]
