# Generated by Django 5.2 on 2025-06-08 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "candidates",
            "0005_rename_coverletter_latex_text_jobapplication_coverletter_text_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="texcv",
            old_name="image",
            new_name="cv_image",
        ),
        migrations.RenameField(
            model_name="texcv",
            old_name="pdf",
            new_name="cv_pdf",
        ),
        migrations.RenameField(
            model_name="texcv",
            old_name="rendered_text",
            new_name="cv_text",
        ),
        migrations.RemoveField(
            model_name="texcv",
            name="photo_width",
        ),
    ]
