# Generated by Django 5.2 on 2025-06-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "candidates",
            "0006_rename_image_texcv_cv_image_rename_pdf_texcv_cv_pdf_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateprofile",
            name="linkedin_url",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
