# Generated by Django 5.2 on 2025-06-21 14:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0007_candidatecertificate_temp_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidatecertificate",
            name="id",
        ),
        migrations.RemoveField(
            model_name="candidateeducation",
            name="id",
        ),
        migrations.RemoveField(
            model_name="candidateexperience",
            name="id",
        ),
        migrations.RemoveField(
            model_name="candidatejobalert",
            name="id",
        ),
        migrations.RemoveField(
            model_name="candidatelanguageskill",
            name="id",
        ),
        migrations.RemoveField(
            model_name="candidateproject",
            name="id",
        ),
        migrations.RemoveField(
            model_name="candidateskill",
            name="id",
        ),
        migrations.AlterField(
            model_name="candidatecertificate",
            name="temp_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="candidateeducation",
            name="temp_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="candidateexperience",
            name="temp_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="candidatejobalert",
            name="temp_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="candidatelanguageskill",
            name="temp_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="candidateproject",
            name="temp_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="candidateskill",
            name="temp_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
