# Generated by Django 5.2 on 2025-06-21 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0008_remove_candidatecertificate_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidatecertificate",
            old_name="temp_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="candidateeducation",
            old_name="temp_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="candidateexperience",
            old_name="temp_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="candidatejobalert",
            old_name="temp_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="candidatelanguageskill",
            old_name="temp_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="candidateproject",
            old_name="temp_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="candidateskill",
            old_name="temp_id",
            new_name="id",
        ),
    ]
