# Generated by Django 5.2 on 2025-06-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0009_rename_temp_id_candidatecertificate_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candidatecertificate",
            options={"base_manager_name": "prefetch_manager", "ordering": ("order",)},
        ),
        migrations.AlterModelOptions(
            name="candidateeducation",
            options={"base_manager_name": "prefetch_manager", "ordering": ("order",)},
        ),
        migrations.AlterModelOptions(
            name="candidateexperience",
            options={"base_manager_name": "prefetch_manager", "ordering": ("order",)},
        ),
        migrations.AlterModelOptions(
            name="candidatejobalert",
            options={"base_manager_name": "prefetch_manager", "ordering": ("order",)},
        ),
        migrations.AlterModelOptions(
            name="candidatelanguageskill",
            options={"base_manager_name": "prefetch_manager", "ordering": ("order",)},
        ),
        migrations.AlterModelOptions(
            name="candidateproject",
            options={"base_manager_name": "prefetch_manager", "ordering": ("order",)},
        ),
        migrations.AlterModelOptions(
            name="candidateskill",
            options={"base_manager_name": "prefetch_manager", "ordering": ("order",)},
        ),
        migrations.AddField(
            model_name="candidatecertificate",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="candidateeducation",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="candidateexperience",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="candidatejobalert",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="candidatelanguageskill",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="candidateproject",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="candidateskill",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
