# Generated by Django 5.2 on 2025-06-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0010_alter_candidatecertificate_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidatelanguageskill",
            name="candidate",
        ),
        migrations.RemoveField(
            model_name="candidateproject",
            name="candidate",
        ),
        migrations.AddField(
            model_name="candidateskill",
            name="skill_type",
            field=models.CharField(
                choices=[
                    ("hard", "Hard skill"),
                    ("soft", "Soft skill"),
                    ("lang", "Language skill"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="candidatejobalert",
            name="notification",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("none", "No notification"),
                ],
                default="weekly",
            ),
        ),
        migrations.DeleteModel(
            name="CandidateCertificate",
        ),
        migrations.DeleteModel(
            name="CandidateLanguageSkill",
        ),
        migrations.DeleteModel(
            name="CandidateProject",
        ),
    ]
