# Generated by Django 5.2 on 2025-06-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0011_remove_candidatelanguageskill_candidate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="certificate_label",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="certificate_label_de",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="certificate_label_en",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="certificate_label_es",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="certificate_label_fr",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="certificate_label_it",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="certificate_label_nl",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="certificate_label_pt",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="language_label",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="language_label_de",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="language_label_en",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="language_label_es",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="language_label_fr",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="language_label_it",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="language_label_nl",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="language_label_pt",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="project_label",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="project_label_de",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="project_label_en",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="project_label_es",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="project_label_fr",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="project_label_it",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="project_label_nl",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="project_label_pt",
        ),
        migrations.AlterField(
            model_name="candidate",
            name="skill_label",
            field=models.CharField(default="Skills", max_length=32),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="skill_label_de",
            field=models.CharField(default="Skills", max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="skill_label_en",
            field=models.CharField(default="Skills", max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="skill_label_es",
            field=models.CharField(default="Skills", max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="skill_label_fr",
            field=models.CharField(default="Skills", max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="skill_label_it",
            field=models.CharField(default="Skills", max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="skill_label_nl",
            field=models.CharField(default="Skills", max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="skill_label_pt",
            field=models.CharField(default="Skills", max_length=32, null=True),
        ),
    ]
