# Generated by Django 5.2 on 2025-06-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0012_remove_candidate_certificate_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateeducation",
            name="order",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="candidateexperience",
            name="order",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="candidatejobalert",
            name="order",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="candidateskill",
            name="order",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
