# Generated by Django 5.2 on 2025-06-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0013_alter_candidateeducation_order_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidateeducation",
            old_name="institution_name",
            new_name="institution",
        ),
        migrations.AddField(
            model_name="candidateeducation",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateeducation",
            name="start_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="candidateeducation",
            name="studying_now",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
