# Generated by Django 5.2 on 2025-06-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "candidates",
            "0014_rename_institution_name_candidateeducation_institution_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateeducation",
            name="studying_now",
            field=models.BooleanField(default=False),
        ),
    ]
