# Generated by Django 5.2 on 2025-06-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0015_alter_candidateeducation_studying_now"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateeducation",
            name="studying_now",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
