# Generated by Django 5.2 on 2025-06-24 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0016_alter_candidateeducation_studying_now"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidateeducation",
            name="from_to",
        ),
        migrations.RemoveField(
            model_name="candidateeducation",
            name="from_to_de",
        ),
        migrations.RemoveField(
            model_name="candidateeducation",
            name="from_to_en",
        ),
        migrations.RemoveField(
            model_name="candidateeducation",
            name="from_to_es",
        ),
        migrations.RemoveField(
            model_name="candidateeducation",
            name="from_to_fr",
        ),
        migrations.RemoveField(
            model_name="candidateeducation",
            name="from_to_it",
        ),
        migrations.RemoveField(
            model_name="candidateeducation",
            name="from_to_nl",
        ),
        migrations.RemoveField(
            model_name="candidateeducation",
            name="from_to_pt",
        ),
    ]
