# Generated by Django 5.2 on 2025-06-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0017_remove_candidateeducation_from_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateeducation",
            name="studying_now",
            field=models.BooleanField(default=False),
        ),
    ]
