# Generated by Django 5.2 on 2025-06-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0018_alter_candidateeducation_studying_now"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateexperience",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateexperience",
            name="start_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="candidateexperience",
            name="studying_now",
            field=models.BooleanField(default=False),
        ),
    ]
