# Generated by Django 5.2 on 2025-06-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0019_candidateexperience_end_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidateexperience",
            old_name="studying_now",
            new_name="here_now",
        ),
        migrations.RemoveField(
            model_name="candidateexperience",
            name="from_to",
        ),
        migrations.RemoveField(
            model_name="candidateexperience",
            name="from_to_de",
        ),
        migrations.RemoveField(
            model_name="candidateexperience",
            name="from_to_en",
        ),
        migrations.RemoveField(
            model_name="candidateexperience",
            name="from_to_es",
        ),
        migrations.RemoveField(
            model_name="candidateexperience",
            name="from_to_fr",
        ),
        migrations.RemoveField(
            model_name="candidateexperience",
            name="from_to_it",
        ),
        migrations.RemoveField(
            model_name="candidateexperience",
            name="from_to_nl",
        ),
        migrations.RemoveField(
            model_name="candidateexperience",
            name="from_to_pt",
        ),
        migrations.AlterField(
            model_name="candidate",
            name="about_label",
            field=models.CharField(default="About me", max_length=32),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="about_label_de",
            field=models.CharField(default="About me", max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="about_label_en",
            field=models.CharField(default="About me", max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="about_label_es",
            field=models.CharField(default="About me", max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="about_label_fr",
            field=models.CharField(default="About me", max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="about_label_it",
            field=models.CharField(default="About me", max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="about_label_nl",
            field=models.CharField(default="About me", max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="about_label_pt",
            field=models.CharField(default="About me", max_length=32, null=True),
        ),
    ]
