# Generated by Django 5.2 on 2025-06-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0021_remove_candidate_about_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="about",
            field=models.TextField(blank=True, null=True, verbose_name="about me"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="about_de",
            field=models.TextField(blank=True, null=True, verbose_name="about me"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="about_en",
            field=models.TextField(blank=True, null=True, verbose_name="about me"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="about_es",
            field=models.TextField(blank=True, null=True, verbose_name="about me"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="about_fr",
            field=models.TextField(blank=True, null=True, verbose_name="about me"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="about_it",
            field=models.TextField(blank=True, null=True, verbose_name="about me"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="about_nl",
            field=models.TextField(blank=True, null=True, verbose_name="about me"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="about_pt",
            field=models.TextField(blank=True, null=True, verbose_name="about me"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="linkedin_url",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="linkedin URL"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="website_url",
            field=models.URLField(
                blank=True, max_length=128, null=True, verbose_name="website URL"
            ),
        ),
        migrations.AlterField(
            model_name="candidateeducation",
            name="end_date",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="candidateeducation",
            name="start_date",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="candidateexperience",
            name="end_date",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="candidateexperience",
            name="start_date",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
    ]
