# Generated by Django 5.2 on 2025-07-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0022_alter_candidate_about_alter_candidate_about_de_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("de", "German"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("it", "Italian"),
                    ("nl", "Dutch"),
                    ("pt", "Portuguese"),
                ],
                db_index=True,
                default="en",
                max_length=4,
                verbose_name="Main language",
            ),
        ),
    ]
