# Generated by Django 5.2 on 2025-07-10 07:31

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0023_alter_candidate_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="candidate",
            field=auto_prefetch.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="candidates.candidate",
            ),
            preserve_default=False,
        ),
    ]
