# Generated by Django 5.2 on 2025-07-12 18:48

import auto_prefetch
import django.db.models.deletion
import one.db
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0025_jobapplication_coverletter_de_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("de", "German"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("it", "Italian"),
                    ("nl", "Dutch"),
                    ("pt", "Portuguese"),
                ],
                default="en",
                max_length=4,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("de", "German"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("it", "Italian"),
                    ("nl", "Dutch"),
                    ("pt", "Portuguese"),
                ],
                default="en",
                max_length=4,
                verbose_name="Main language",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="languages",
            field=one.db.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("en", "English"),
                        ("de", "German"),
                        ("es", "Spanish"),
                        ("fr", "French"),
                        ("it", "Italian"),
                        ("nl", "Dutch"),
                        ("pt", "Portuguese"),
                    ],
                    max_length=8,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="cv",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="candidates.texcv",
            ),
        ),
    ]
