# Generated by Django 5.2 on 2025-07-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "candidates",
            "0026_jobapplication_language_alter_candidate_language_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("de", "German"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("it", "Italian"),
                    ("nl", "Dutch"),
                    ("pt", "Portuguese"),
                ],
                max_length=4,
                verbose_name="Main language",
            ),
        ),
    ]
