# Generated by Django 5.2 on 2025-07-13 19:20

import auto_prefetch
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.db.models.functions.text
import one.candidates.models
import one.db
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0028_alter_candidate_user"),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="about",
            field=models.TextField(blank=True, null=True, verbose_name="About me"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="about_de",
            field=models.TextField(blank=True, null=True, verbose_name="About me"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="about_en",
            field=models.TextField(blank=True, null=True, verbose_name="About me"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="about_es",
            field=models.TextField(blank=True, null=True, verbose_name="About me"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="about_fr",
            field=models.TextField(blank=True, null=True, verbose_name="About me"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="about_it",
            field=models.TextField(blank=True, null=True, verbose_name="About me"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="about_nl",
            field=models.TextField(blank=True, null=True, verbose_name="About me"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="about_pt",
            field=models.TextField(blank=True, null=True, verbose_name="About me"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="coverletter_body",
            field=models.TextField(
                blank=True, null=True, verbose_name="Body of cover letter"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="coverletter_body_de",
            field=models.TextField(
                blank=True, null=True, verbose_name="Body of cover letter"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="coverletter_body_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Body of cover letter"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="coverletter_body_es",
            field=models.TextField(
                blank=True, null=True, verbose_name="Body of cover letter"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="coverletter_body_fr",
            field=models.TextField(
                blank=True, null=True, verbose_name="Body of cover letter"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="coverletter_body_it",
            field=models.TextField(
                blank=True, null=True, verbose_name="Body of cover letter"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="coverletter_body_nl",
            field=models.TextField(
                blank=True, null=True, verbose_name="Body of cover letter"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="coverletter_body_pt",
            field=models.TextField(
                blank=True, null=True, verbose_name="Body of cover letter"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="email",
            field=models.EmailField(max_length=64, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="first_name",
            field=models.CharField(max_length=64, verbose_name="First name"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="full_name",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.text.Concat(
                    "first_name", models.Value(" "), "last_name"
                ),
                output_field=models.CharField(max_length=128),
                verbose_name="Full name",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="job_title",
            field=models.CharField(max_length=64, verbose_name="Job title"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="job_title_de",
            field=models.CharField(max_length=64, null=True, verbose_name="Job title"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="job_title_en",
            field=models.CharField(max_length=64, null=True, verbose_name="Job title"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="job_title_es",
            field=models.CharField(max_length=64, null=True, verbose_name="Job title"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="job_title_fr",
            field=models.CharField(max_length=64, null=True, verbose_name="Job title"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="job_title_it",
            field=models.CharField(max_length=64, null=True, verbose_name="Job title"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="job_title_nl",
            field=models.CharField(max_length=64, null=True, verbose_name="Job title"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="job_title_pt",
            field=models.CharField(max_length=64, null=True, verbose_name="Job title"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="languages",
            field=one.db.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("en", "English"),
                        ("de", "German"),
                        ("es", "Spanish"),
                        ("fr", "French"),
                        ("it", "Italian"),
                        ("nl", "Dutch"),
                        ("pt", "Portuguese"),
                    ],
                    max_length=8,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Languages",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="last_name",
            field=models.CharField(max_length=64, verbose_name="Last name"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="linkedin_url",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="LinkedIn URL"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="location",
            field=models.CharField(max_length=32, verbose_name="Location"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="location_de",
            field=models.CharField(max_length=32, null=True, verbose_name="Location"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="location_en",
            field=models.CharField(max_length=32, null=True, verbose_name="Location"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="location_es",
            field=models.CharField(max_length=32, null=True, verbose_name="Location"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="location_fr",
            field=models.CharField(max_length=32, null=True, verbose_name="Location"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="location_it",
            field=models.CharField(max_length=32, null=True, verbose_name="Location"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="location_nl",
            field=models.CharField(max_length=32, null=True, verbose_name="Location"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="location_pt",
            field=models.CharField(max_length=32, null=True, verbose_name="Location"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="phone",
            field=models.CharField(max_length=32, verbose_name="Phone number"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="photo",
            field=models.ImageField(
                null=True,
                upload_to=one.candidates.models.Candidate.get_upload_path,
                verbose_name="Photo",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="website_url",
            field=models.URLField(
                blank=True, max_length=128, null=True, verbose_name="Website URL"
            ),
        ),
        migrations.AlterField(
            model_name="candidateeducation",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="candidateeducation",
            name="description_de",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="candidateeducation",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="candidateeducation",
            name="description_es",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="candidateeducation",
            name="description_fr",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="candidateeducation",
            name="description_it",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="candidateeducation",
            name="description_nl",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="candidateeducation",
            name="description_pt",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="candidateeducation",
            name="end_date",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="End date"
            ),
        ),
        migrations.AlterField(
            model_name="candidateeducation",
            name="institution",
            field=models.CharField(max_length=64, verbose_name="Institution"),
        ),
        migrations.AlterField(
            model_name="candidateeducation",
            name="start_date",
            field=models.CharField(max_length=64, verbose_name="Start date"),
        ),
        migrations.AlterField(
            model_name="candidateeducation",
            name="studying_now",
            field=models.BooleanField(default=False, verbose_name="Studying this now"),
        ),
        migrations.AlterField(
            model_name="candidateeducation",
            name="title",
            field=models.CharField(max_length=64, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="candidateeducation",
            name="title_de",
            field=models.CharField(max_length=64, null=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="candidateeducation",
            name="title_en",
            field=models.CharField(max_length=64, null=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="candidateeducation",
            name="title_es",
            field=models.CharField(max_length=64, null=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="candidateeducation",
            name="title_fr",
            field=models.CharField(max_length=64, null=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="candidateeducation",
            name="title_it",
            field=models.CharField(max_length=64, null=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="candidateeducation",
            name="title_nl",
            field=models.CharField(max_length=64, null=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="candidateeducation",
            name="title_pt",
            field=models.CharField(max_length=64, null=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="candidateexperience",
            name="company_name",
            field=models.CharField(max_length=64, verbose_name="Company name"),
        ),
        migrations.AlterField(
            model_name="candidateexperience",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="candidateexperience",
            name="description_de",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="candidateexperience",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="candidateexperience",
            name="description_es",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="candidateexperience",
            name="description_fr",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="candidateexperience",
            name="description_it",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="candidateexperience",
            name="description_nl",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="candidateexperience",
            name="description_pt",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="candidateexperience",
            name="end_date",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="End date"
            ),
        ),
        migrations.AlterField(
            model_name="candidateexperience",
            name="here_now",
            field=models.BooleanField(default=False, verbose_name="Working here now"),
        ),
        migrations.AlterField(
            model_name="candidateexperience",
            name="job_title",
            field=models.CharField(max_length=64, verbose_name="Role"),
        ),
        migrations.AlterField(
            model_name="candidateexperience",
            name="job_title_de",
            field=models.CharField(max_length=64, null=True, verbose_name="Role"),
        ),
        migrations.AlterField(
            model_name="candidateexperience",
            name="job_title_en",
            field=models.CharField(max_length=64, null=True, verbose_name="Role"),
        ),
        migrations.AlterField(
            model_name="candidateexperience",
            name="job_title_es",
            field=models.CharField(max_length=64, null=True, verbose_name="Role"),
        ),
        migrations.AlterField(
            model_name="candidateexperience",
            name="job_title_fr",
            field=models.CharField(max_length=64, null=True, verbose_name="Role"),
        ),
        migrations.AlterField(
            model_name="candidateexperience",
            name="job_title_it",
            field=models.CharField(max_length=64, null=True, verbose_name="Role"),
        ),
        migrations.AlterField(
            model_name="candidateexperience",
            name="job_title_nl",
            field=models.CharField(max_length=64, null=True, verbose_name="Role"),
        ),
        migrations.AlterField(
            model_name="candidateexperience",
            name="job_title_pt",
            field=models.CharField(max_length=64, null=True, verbose_name="Role"),
        ),
        migrations.AlterField(
            model_name="candidateexperience",
            name="start_date",
            field=models.CharField(max_length=64, verbose_name="Start date"),
        ),
        migrations.AlterField(
            model_name="candidatejobalert",
            name="area",
            field=django.contrib.gis.db.models.fields.PolygonField(
                srid=4326, verbose_name="Area"
            ),
        ),
        migrations.AlterField(
            model_name="candidatejobalert",
            name="languages",
            field=one.db.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("en", "English"),
                        ("de", "German"),
                        ("es", "Spanish"),
                        ("fr", "French"),
                        ("it", "Italian"),
                        ("nl", "Dutch"),
                        ("pt", "Portuguese"),
                    ],
                    max_length=8,
                ),
                blank=True,
                db_index=True,
                default=list,
                size=None,
                verbose_name="Languages",
            ),
        ),
        migrations.AlterField(
            model_name="candidatejobalert",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="candidatejobalert",
            name="notification",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("none", "No notification"),
                ],
                default="weekly",
                verbose_name="Notification type",
            ),
        ),
        migrations.AlterField(
            model_name="candidatejobalert",
            name="query",
            field=models.CharField(max_length=255, verbose_name="Term"),
        ),
        migrations.AlterField(
            model_name="candidateskill",
            name="level",
            field=models.IntegerField(
                choices=[
                    (1, "Beginner"),
                    (2, "Learner"),
                    (3, "Competent"),
                    (4, "Proficient"),
                    (5, "Expert"),
                ],
                verbose_name="Level",
            ),
        ),
        migrations.AlterField(
            model_name="candidateskill",
            name="name",
            field=models.CharField(max_length=64, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="candidateskill",
            name="name_de",
            field=models.CharField(max_length=64, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="candidateskill",
            name="name_en",
            field=models.CharField(max_length=64, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="candidateskill",
            name="name_es",
            field=models.CharField(max_length=64, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="candidateskill",
            name="name_fr",
            field=models.CharField(max_length=64, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="candidateskill",
            name="name_it",
            field=models.CharField(max_length=64, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="candidateskill",
            name="name_nl",
            field=models.CharField(max_length=64, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="candidateskill",
            name="name_pt",
            field=models.CharField(max_length=64, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="candidateskill",
            name="skill_type",
            field=models.CharField(
                choices=[
                    ("hard", "Hard skill"),
                    ("soft", "Soft skill"),
                    ("lang", "Language skill"),
                ],
                max_length=32,
                null=True,
                verbose_name="Skill type",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="candidate",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="candidates.candidate",
                verbose_name="Candidate",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="coverletter",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=one.candidates.models.JobApplication.get_upload_path,
                verbose_name="Cover letter",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="coverletter_de",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=one.candidates.models.JobApplication.get_upload_path,
                verbose_name="Cover letter",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="coverletter_en",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=one.candidates.models.JobApplication.get_upload_path,
                verbose_name="Cover letter",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="coverletter_es",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=one.candidates.models.JobApplication.get_upload_path,
                verbose_name="Cover letter",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="coverletter_fr",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=one.candidates.models.JobApplication.get_upload_path,
                verbose_name="Cover letter",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="coverletter_it",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=one.candidates.models.JobApplication.get_upload_path,
                verbose_name="Cover letter",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="coverletter_nl",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=one.candidates.models.JobApplication.get_upload_path,
                verbose_name="Cover letter",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="coverletter_pt",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=one.candidates.models.JobApplication.get_upload_path,
                verbose_name="Cover letter",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="coverletter_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="LaTeX text of Cover letter"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="coverletter_text_de",
            field=models.TextField(
                blank=True, null=True, verbose_name="LaTeX text of Cover letter"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="coverletter_text_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="LaTeX text of Cover letter"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="coverletter_text_es",
            field=models.TextField(
                blank=True, null=True, verbose_name="LaTeX text of Cover letter"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="coverletter_text_fr",
            field=models.TextField(
                blank=True, null=True, verbose_name="LaTeX text of Cover letter"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="coverletter_text_it",
            field=models.TextField(
                blank=True, null=True, verbose_name="LaTeX text of Cover letter"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="coverletter_text_nl",
            field=models.TextField(
                blank=True, null=True, verbose_name="LaTeX text of Cover letter"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="coverletter_text_pt",
            field=models.TextField(
                blank=True, null=True, verbose_name="LaTeX text of Cover letter"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="cv",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="candidates.texcv",
                verbose_name="Curriculum Vitae",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="dossier",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=one.candidates.models.JobApplication.get_upload_path,
                verbose_name="Dossier",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="dossier_de",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=one.candidates.models.JobApplication.get_upload_path,
                verbose_name="Dossier",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="dossier_en",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=one.candidates.models.JobApplication.get_upload_path,
                verbose_name="Dossier",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="dossier_es",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=one.candidates.models.JobApplication.get_upload_path,
                verbose_name="Dossier",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="dossier_fr",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=one.candidates.models.JobApplication.get_upload_path,
                verbose_name="Dossier",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="dossier_it",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=one.candidates.models.JobApplication.get_upload_path,
                verbose_name="Dossier",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="dossier_nl",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=one.candidates.models.JobApplication.get_upload_path,
                verbose_name="Dossier",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="dossier_pt",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=one.candidates.models.JobApplication.get_upload_path,
                verbose_name="Dossier",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="dossier_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="LaTeX text of Dossier"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="dossier_text_de",
            field=models.TextField(
                blank=True, null=True, verbose_name="LaTeX text of Dossier"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="dossier_text_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="LaTeX text of Dossier"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="dossier_text_es",
            field=models.TextField(
                blank=True, null=True, verbose_name="LaTeX text of Dossier"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="dossier_text_fr",
            field=models.TextField(
                blank=True, null=True, verbose_name="LaTeX text of Dossier"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="dossier_text_it",
            field=models.TextField(
                blank=True, null=True, verbose_name="LaTeX text of Dossier"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="dossier_text_nl",
            field=models.TextField(
                blank=True, null=True, verbose_name="LaTeX text of Dossier"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="dossier_text_pt",
            field=models.TextField(
                blank=True, null=True, verbose_name="LaTeX text of Dossier"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="job",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="companies.job",
                verbose_name="Job",
            ),
        ),
    ]
