# Generated by Django 5.2 on 2025-07-14 21:06

import one.db
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0029_alter_candidate_about_alter_candidate_about_de_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("de", "German"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("it", "Italian"),
                    ("nl", "Dutch"),
                    ("pt", "Portuguese"),
                ],
                max_length=4,
                verbose_name="Primary language",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="languages",
            field=one.db.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("en", "English"),
                        ("de", "German"),
                        ("es", "Spanish"),
                        ("fr", "French"),
                        ("it", "Italian"),
                        ("nl", "Dutch"),
                        ("pt", "Portuguese"),
                    ],
                    max_length=8,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Additional Languages",
            ),
        ),
    ]
