# Generated by Django 5.2 on 2025-07-17 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0031_remove_jobapplication_coverletter_de_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobapplication",
            name="job",
        ),
    ]
