# Generated by Django 5.2 on 2025-07-17 08:00

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0032_remove_jobapplication_job"),
        ("companies", "0009_job_company_locations"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="job",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="companies.job",
                verbose_name="Job",
            ),
        ),
    ]
