# Generated by Django 5.2 on 2025-07-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0033_jobapplication_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("de", "German"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("it", "Italian"),
                    ("nl", "Dutch"),
                    ("pt", "Portuguese"),
                ],
                default="en",
                max_length=4,
                verbose_name="Application language",
            ),
        ),
    ]
