# Generated by Django 5.2.4 on 2025-07-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0034_alter_jobapplication_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="email_force_send",
            field=models.BooleanField(default=False, verbose_name="Force send E-mail"),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="sent_on",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Sent at"),
        ),
    ]
