# Generated by Django 5.2.4 on 2025-07-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0037_candidateprofile_candidate_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateprofile",
            name="title",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
