# Generated by Django 5.2.4 on 2025-07-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0038_alter_candidateprofile_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
    ]
