# Generated by Django 5.2 on 2025-05-23 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "articles",
            "0006_remove_article_created_on_remove_article_updated_on_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="articlefile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="articlefile",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="maintopic",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="maintopic",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.utils.timezone.now
            ),
        ),
    ]
