# Generated by Django 5.1.4 on 2025-01-03 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0006_alter_article_featured"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articleparentfolder",
            name="sites",
        ),
    ]
