# Generated by Django 5.1.4 on 2025-01-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0009_article_default_language_article_rest_languages"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="rest_languages",
            new_name="languages",
        ),
    ]
