# Generated by Django 5.1 on 2025-03-15 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0010_rename_rest_languages_article_languages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="default_language",
        ),
        migrations.RemoveField(
            model_name="article",
            name="languages",
        ),
    ]
