# Generated by Django 5.1 on 2025-03-15 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0012_article_language_article_languages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="language",
        ),
    ]
