# Generated by Django 5.1.7 on 2025-03-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0013_remove_article_language"),
        ("base", "0013_topic_article_folders"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleparentfolder",
            name="topics",
            field=models.ManyToManyField(blank=True, to="base.topic"),
        ),
    ]
