# Generated by Django 5.1.7 on 2025-03-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0014_articleparentfolder_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleparentfolder",
            name="present_in_filesystem",
            field=models.BooleanField(default=True),
        ),
    ]
