# Generated by Django 5.1.7 on 2025-03-26 19:20

import one.base.utils.db
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0015_articleparentfolder_present_in_filesystem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="body_el",
        ),
        migrations.RemoveField(
            model_name="article",
            name="body_pl",
        ),
        migrations.RemoveField(
            model_name="article",
            name="body_ru",
        ),
        migrations.RemoveField(
            model_name="article",
            name="body_sk",
        ),
        migrations.RemoveField(
            model_name="article",
            name="body_sl",
        ),
        migrations.RemoveField(
            model_name="article",
            name="body_sv",
        ),
        migrations.RemoveField(
            model_name="article",
            name="body_tr",
        ),
        migrations.RemoveField(
            model_name="article",
            name="body_uk",
        ),
        migrations.RemoveField(
            model_name="article",
            name="slug_el",
        ),
        migrations.RemoveField(
            model_name="article",
            name="slug_pl",
        ),
        migrations.RemoveField(
            model_name="article",
            name="slug_ru",
        ),
        migrations.RemoveField(
            model_name="article",
            name="slug_sk",
        ),
        migrations.RemoveField(
            model_name="article",
            name="slug_sl",
        ),
        migrations.RemoveField(
            model_name="article",
            name="slug_sv",
        ),
        migrations.RemoveField(
            model_name="article",
            name="slug_tr",
        ),
        migrations.RemoveField(
            model_name="article",
            name="slug_uk",
        ),
        migrations.RemoveField(
            model_name="article",
            name="title_el",
        ),
        migrations.RemoveField(
            model_name="article",
            name="title_pl",
        ),
        migrations.RemoveField(
            model_name="article",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="article",
            name="title_sk",
        ),
        migrations.RemoveField(
            model_name="article",
            name="title_sl",
        ),
        migrations.RemoveField(
            model_name="article",
            name="title_sv",
        ),
        migrations.RemoveField(
            model_name="article",
            name="title_tr",
        ),
        migrations.RemoveField(
            model_name="article",
            name="title_uk",
        ),
        migrations.AlterField(
            model_name="article",
            name="languages",
            field=one.base.utils.db.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("en", "English"),
                        ("de", "German"),
                        ("es", "Spanish"),
                        ("fr", "French"),
                        ("it", "Italian"),
                        ("nl", "Dutch"),
                        ("pt", "Portuguese"),
                    ],
                    max_length=8,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
