# Generated by Django 5.2 on 2025-04-14 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0016_remove_article_body_el_remove_article_body_pl_and_more"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="articleparentfolder",
        #     name="topics",
        # ),
    ]
