# Generated by Django 5.2 on 2025-04-14 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0017_remove_articleparentfolder_topics"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ArticleParentFolder",
            new_name="MainTopic",
        ),
    ]
