# Generated by Django 5.2 on 2025-04-14 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0020_alter_maintopic_present_in_filesystem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="parent_folder",
            new_name="main_topic",
        ),
    ]
