# Generated by Django 5.1.4 on 2025-01-05 22:02

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0003_alter_link_django_url_path"),
        ("sites", "0021_rename_spammy_requests_duration_site_spam_requests_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="django_url_path",
            field=models.CharField(
                blank=True,
                choices=[
                    ("home", "Home"),
                    ("search", "Search"),
                    ("sitemap", "Sitemap"),
                    ("article_list", "Articles"),
                    ("plan_list", "Plans"),
                    ("account_login", "Sign In"),
                    ("account_signup", "Sign Up"),
                    ("user_dashboard", "Account"),
                    ("faq_list", "FAQs"),
                    ("chat_detail", "Chat"),
                    ("quiz_list", "English Quizzes"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="LinkRedirect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_link",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="links.link",
                    ),
                ),
                (
                    "site",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.site"
                    ),
                ),
                (
                    "to_link",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="links.link",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
