# Generated by Django 5.1.4 on 2025-01-05 22:12

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0019_client_dark_theme"),
        ("links", "0004_alter_link_django_url_path_linkredirect"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="linkredirect",
            name="from_link",
        ),
        migrations.AddField(
            model_name="linkredirect",
            name="from_path",
            field=auto_prefetch.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.path",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="linkredirect",
            name="to_link",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="links.link"
            ),
        ),
    ]
