# Generated by Django 5.1.4 on 2025-01-05 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0005_remove_linkredirect_from_link_linkredirect_from_path_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LinkRedirect",
        ),
    ]
