# Generated by Django 5.1.4 on 2025-01-06 21:15

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_delete_traffic"),
        ("links", "0006_delete_linkredirect"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="topic",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.topic",
            ),
        ),
    ]
