# Generated by Django 5.2 on 2025-05-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0006_alter_link_created_at_alter_link_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="link",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
