# Generated by Django 5.1.4 on 2025-01-26 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0010_alter_link_languages"),
    ]

    operations = [
        migrations.RenameField(
            model_name="link",
            old_name="languages",
            new_name="rest_languages",
        ),
    ]
