# Generated by Django 5.1 on 2025-03-15 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0012_rename_rest_languages_link_languages"),
    ]

    operations = [
        migrations.RenameField(
            model_name="link",
            old_name="default_language",
            new_name="language",
        ),
    ]
