# Generated by Django 5.1.7 on 2025-03-21 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0013_rename_default_language_link_language"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="link",
        #     name="page",
        # ),
    ]
