# Generated by Django 5.1.7 on 2025-03-26 19:20

import one.base.utils.db
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0014_remove_link_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="link",
            name="custom_title_el",
        ),
        migrations.RemoveField(
            model_name="link",
            name="custom_title_pl",
        ),
        migrations.RemoveField(
            model_name="link",
            name="custom_title_ru",
        ),
        migrations.RemoveField(
            model_name="link",
            name="custom_title_sk",
        ),
        migrations.RemoveField(
            model_name="link",
            name="custom_title_sl",
        ),
        migrations.RemoveField(
            model_name="link",
            name="custom_title_sv",
        ),
        migrations.RemoveField(
            model_name="link",
            name="custom_title_tr",
        ),
        migrations.RemoveField(
            model_name="link",
            name="custom_title_uk",
        ),
        migrations.AlterField(
            model_name="link",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("de", "German"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("it", "Italian"),
                    ("nl", "Dutch"),
                    ("pt", "Portuguese"),
                ],
                default="en",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="languages",
            field=one.base.utils.db.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("en", "English"),
                        ("de", "German"),
                        ("es", "Spanish"),
                        ("fr", "French"),
                        ("it", "Italian"),
                        ("nl", "Dutch"),
                        ("pt", "Portuguese"),
                    ],
                    max_length=8,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
