# Generated by Django 5.2 on 2025-04-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0015_remove_link_custom_title_el_and_more"),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name="link",
        #     name="topic",
        #     field=models.CharField(
        #         blank=True,
        #         choices=[
        #             ("django", "Django"),
        #             ("htmx", "htmx"),
        #             ("alpinejs", "AlpineJS"),
        #             ("devops", "DevOps"),
        #             ("python", "Python"),
        #             ("linux", "Linux"),
        #             ("latex", "LaTex"),
        #             ("matlab", "Matlab"),
        #             ("siemens", "Siemens"),
        #             ("excel", "Excel"),
        #             ("maths", "Maths"),
        #             ("mechanics", "Mechanics"),
        #             ("english", "English"),
        #             ("electronics", "Electronics"),
        #             ("calendar", "Calendars"),
        #         ],
        #         max_length=16,
        #         null=True,
        #     ),
        # ),
    ]
