# Generated by Django 5.2 on 2025-04-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0017_rename_django_url_path_link_url_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="url_path",
            field=models.CharField(
                blank=True,
                choices=[
                    ("home", "Home"),
                    ("search", "Search"),
                    ("sitemap", "Sitemap"),
                    ("contact", "Contact"),
                    ("article_list", "Articles"),
                    ("plan_list", "Plans"),
                    ("account_login", "Sign In"),
                    ("account_signup", "Sign Up"),
                    ("user_dashboard", "Account"),
                    ("faq_list", "FAQs"),
                    ("quiz_list", "English Quizzes"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
