# Generated by Django 5.1.4 on 2024-12-29 02:49

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeoInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accuracy_radius", models.SmallIntegerField(null=True)),
                ("city", models.CharField(max_length=128, null=True)),
                ("continent_code", models.CharField(max_length=64, null=True)),
                ("continent_name", models.CharField(max_length=128, null=True)),
                ("country_code", models.CharField(max_length=64, null=True)),
                ("country_name", models.CharField(max_length=64, null=True)),
                ("is_in_european_union", models.BooleanField(null=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("metro_code", models.SmallIntegerField(null=True)),
                ("postal_code", models.CharField(max_length=64, null=True)),
                ("region_code", models.CharField(max_length=64, null=True)),
                ("region_name", models.CharField(max_length=128, null=True)),
                ("time_zone", models.CharField(max_length=128, null=True)),
                ("dma_code", models.SmallIntegerField(null=True)),
                ("region", models.CharField(max_length=32, null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
                "unique_together": {("latitude", "longitude")},
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
