# Generated by Django 5.1.4 on 2024-12-22 15:48

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_alter_message_options"),
        ("sites", "0010_alter_site_rest_languages"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="site",
            field=auto_prefetch.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="sites.site"
            ),
        ),
    ]
