# Generated by Django 5.1.4 on 2025-01-03 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_alter_book_pdf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="sites",
        ),
    ]
