# Generated by Django 5.1.4 on 2025-01-15 22:21

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MessageSent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="", max_length=128)),
                ("details", models.CharField(default="", max_length=512)),
                ("output", models.CharField(default="", max_length=512)),
                ("time", models.FloatField(default=0.0)),
                ("sent_with_ssl", models.BooleanField(default=False)),
                ("timestamp", models.FloatField(null=True)),
                ("message_int_id", models.PositiveIntegerField(null=True)),
                ("message_token", models.CharField(default="", max_length=128)),
                ("message_direction", models.CharField(default="", max_length=128)),
                ("message_id", models.CharField(default="", max_length=128)),
                ("message_to", models.EmailField(max_length=254)),
                ("message_from", models.EmailField(max_length=254)),
                ("message_subject", models.CharField(default="", max_length=128)),
                ("message_timestamp", models.FloatField(null=True)),
                ("message_spam_status", models.CharField(default="", max_length=128)),
                ("message_tag", models.CharField(default="", max_length=128)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
