# Generated by Django 5.1.4 on 2025-01-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0002_domaindnserror_messagelinkclicked_messageloaded"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messagesent",
            name="message_int_id",
        ),
        migrations.AddField(
            model_name="domaindnserror",
            name="dkim_error",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AddField(
            model_name="domaindnserror",
            name="dkim_status",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="domaindnserror",
            name="dns_checked_at",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="domaindnserror",
            name="domain",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="domaindnserror",
            name="mx_error",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AddField(
            model_name="domaindnserror",
            name="mx_status",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="domaindnserror",
            name="return_path_error",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AddField(
            model_name="domaindnserror",
            name="return_path_status",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="domaindnserror",
            name="spf_error",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AddField(
            model_name="domaindnserror",
            name="spf_status",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="domaindnserror",
            name="uuid",
            field=models.CharField(default="", max_length=128),
        ),
    ]
