# Generated by Django 5.2 on 2025-05-21 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0003_alter_postaldomaindnserror_created_on_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postaldomaindnserror",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="postaldomaindnserror",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="postalmessage",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="postalmessage",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="postalmessagelinkclicked",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="postalmessagelinkclicked",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="postalmessageloaded",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="postalmessageloaded",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="replymessage",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="replymessage",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="sender",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="sender",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="templateattachment",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="templateattachment",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="templatemessage",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="templatemessage",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="templaterecipient",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="templaterecipient",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="templaterecipientfile",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="templaterecipientfile",
            name="updated_on",
        ),
        migrations.AddField(
            model_name="postaldomaindnserror",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848231, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="postaldomaindnserror",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848323, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="postalmessage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848231, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="postalmessage",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848323, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="postalmessagelinkclicked",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848231, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="postalmessagelinkclicked",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848323, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="postalmessageloaded",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848231, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="postalmessageloaded",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848323, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="replymessage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848231, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="replymessage",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848323, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="sender",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848231, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="sender",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848323, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="templateattachment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848231, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="templateattachment",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848323, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="templatemessage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848231, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="templatemessage",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848323, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="templaterecipient",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848231, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="templaterecipient",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848323, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="templaterecipientfile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848231, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="templaterecipientfile",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848323, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
