# Generated by Django 5.1.4 on 2025-01-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0003_remove_messagesent_message_int_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domaindnserror",
            name="dkim_error",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="domaindnserror",
            name="dkim_status",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="domaindnserror",
            name="domain",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="domaindnserror",
            name="mx_error",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="domaindnserror",
            name="mx_status",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="domaindnserror",
            name="return_path_error",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="domaindnserror",
            name="return_path_status",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="domaindnserror",
            name="spf_error",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="domaindnserror",
            name="spf_status",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="domaindnserror",
            name="uuid",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="messagesent",
            name="details",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="messagesent",
            name="message_direction",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="messagesent",
            name="message_id",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="messagesent",
            name="message_spam_status",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="messagesent",
            name="message_subject",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="messagesent",
            name="message_tag",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="messagesent",
            name="message_token",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="messagesent",
            name="output",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="messagesent",
            name="status",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
