# Generated by Django 5.1.4 on 2025-01-16 21:51

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0004_alter_domaindnserror_dkim_error_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailMessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address_from", models.EmailField(max_length=64)),
                ("subject", models.CharField(max_length=128)),
                ("reply_to", models.EmailField(blank=True, max_length=64, null=True)),
                ("cc", models.EmailField(blank=True, max_length=64, null=True)),
                ("body", models.TextField()),
                (
                    "var1_meaning",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "var2_meaning",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "var3_meaning",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="EmailAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=storages.backends.s3.S3Storage(
                            default_acl="private",
                            gzip=False,
                            location="private",
                            querystring_auth=True,
                        ),
                        upload_to="emails",
                    ),
                ),
                (
                    "email_template",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="emails.emailmessagetemplate",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="EmailRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=128)),
                ("body", models.TextField()),
                ("to_address", models.EmailField(max_length=128)),
                ("var_1", models.CharField(blank=True, max_length=64, null=True)),
                ("var_2", models.CharField(blank=True, max_length=64, null=True)),
                ("var_3", models.CharField(blank=True, max_length=64, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("draft", models.BooleanField(default=False)),
                (
                    "email_sent_on",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("email_sent", models.BooleanField(default=False, editable=False)),
                (
                    "email_template",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="emails.emailmessagetemplate",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
