# Generated by Django 5.1.4 on 2025-01-16 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0005_emailmessagetemplate_emailattachment_emailrecipient"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EmailAttachment",
            new_name="Attachment",
        ),
        migrations.RenameModel(
            old_name="EmailMessageTemplate",
            new_name="MessageTemplate",
        ),
        migrations.RenameModel(
            old_name="EmailRecipient",
            new_name="Recipient",
        ),
    ]
