# Generated by Django 5.1.4 on 2025-01-17 17:41

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0006_rename_emailattachment_attachment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("address", models.EmailField(max_length=64, unique=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name="domaindnserror",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "Postal: DomainDNSError",
                "verbose_name_plural": "Postal: DomainDNSError",
            },
        ),
        migrations.AlterModelOptions(
            name="messagelinkclicked",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "Postal: MessageLinkClicked",
                "verbose_name_plural": "Postal: MessageLinkClicked",
            },
        ),
        migrations.AlterModelOptions(
            name="messageloaded",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "Postal: MessageLoaded",
                "verbose_name_plural": "Postal: MessageLoaded",
            },
        ),
        migrations.AlterModelOptions(
            name="messagesent",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "Postal: MessageSent",
                "verbose_name_plural": "Postal: MessageSent",
            },
        ),
        migrations.RemoveField(
            model_name="messagetemplate",
            name="address_from",
        ),
        migrations.AddField(
            model_name="messagetemplate",
            name="sender",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="emails.sender",
            ),
        ),
    ]
