# Generated by Django 5.2 on 2025-05-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0006_alter_postaldomaindnserror_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postalmessage",
            name="message_id",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
