# Generated by Django 5.2 on 2025-06-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0007_postalmessage_message_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postalmessage",
            options={
                "base_manager_name": "prefetch_manager",
                "ordering": ("received_at",),
                "verbose_name": "Postal: Message",
                "verbose_name_plural": "Postal: Messages",
            },
        ),
    ]
