# Generated by Django 5.1.4 on 2025-01-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0008_rename_recipient_templaterecipient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messagetemplate",
            name="var1_meaning",
        ),
        migrations.RemoveField(
            model_name="messagetemplate",
            name="var2_meaning",
        ),
        migrations.RemoveField(
            model_name="messagetemplate",
            name="var3_meaning",
        ),
        migrations.RemoveField(
            model_name="templaterecipient",
            name="remarks",
        ),
        migrations.AddField(
            model_name="messagetemplate",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
