# Generated by Django 5.1.4 on 2025-01-18 07:27

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0009_remove_messagetemplate_var1_meaning_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagetemplate",
            name="inverval",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="messagetemplate",
            name="is_periodic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="messagetemplate",
            name="start_time",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="messagetemplate",
            name="stop_time",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "send_times",
                    models.PositiveSmallIntegerField(default=0, editable=False),
                ),
                (
                    "sent_on",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("to_address", models.EmailField(max_length=128)),
                ("var_1", models.CharField(blank=True, max_length=64, null=True)),
                ("var_2", models.CharField(blank=True, max_length=64, null=True)),
                ("var_3", models.CharField(blank=True, max_length=64, null=True)),
                ("draft", models.BooleanField(default=False)),
                (
                    "email",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="emails.messagetemplate",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name="TemplateRecipient",
        ),
    ]
