# Generated by Django 5.1.4 on 2025-01-18 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "emails",
            "0010_messagetemplate_inverval_messagetemplate_is_periodic_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MessageTemplate",
            new_name="EmailMessageTemplate",
        ),
    ]
