# Generated by Django 5.1.4 on 2025-01-18 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0011_rename_messagetemplate_emailmessagetemplate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailmessagetemplate",
            old_name="inverval",
            new_name="interval",
        ),
    ]
