# Generated by Django 5.1.4 on 2025-01-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0014_alter_emailmessagetemplate_interval_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailmessagetemplate",
            name="start_time",
            field=models.DateTimeField(
                blank=True, help_text="Set when email message is periodic.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="emailmessagetemplate",
            name="stop_time",
            field=models.DateTimeField(
                blank=True, help_text="Set when email message is periodic.", null=True
            ),
        ),
    ]
