# Generated by Django 5.1.4 on 2025-01-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0015_alter_emailmessagetemplate_start_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messagesent",
            name="message_subject",
        ),
        migrations.AddField(
            model_name="messagesent",
            name="subject",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
