# Generated by Django 5.1.4 on 2025-01-22 04:10

import one.emails.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0019_postalmessage_delayed_postalmessage_delivery_failed_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attachment",
            old_name="email_template",
            new_name="email",
        ),
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(
                storage=storages.backends.s3.S3Storage(
                    default_acl="private",
                    gzip=False,
                    location="private",
                    querystring_auth=True,
                ),
                upload_to=one.emails.models.Attachment.get_directory,
            ),
        ),
    ]
