# Generated by Django 5.1.4 on 2025-01-22 06:07

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
import one.emails.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0020_rename_email_template_attachment_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostalReplyMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("replied", models.BooleanField(default=False)),
                (
                    "replied_on",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "file",
                    models.FileField(
                        storage=storages.backends.s3.S3Storage(
                            default_acl="private",
                            gzip=False,
                            location="private",
                            querystring_auth=True,
                        ),
                        upload_to=one.emails.models.PostalReplyMessage.get_directory,
                    ),
                ),
                (
                    "postal_message",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="emails.postalmessage",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
