# Generated by Django 5.1.4 on 2025-01-26 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0022_postalreplymessage_draft_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DomainDNSError",
            new_name="PostalDomainDNSError",
        ),
        migrations.RenameModel(
            old_name="MessageLoaded",
            new_name="PostalMessageLinkClicked",
        ),
        migrations.RenameModel(
            old_name="MessageLinkClicked",
            new_name="PostalMessageLoaded",
        ),
        migrations.RenameModel(
            old_name="Attachment",
            new_name="TemplateAttachment",
        ),
        migrations.RenameModel(
            old_name="EmailMessageTemplate",
            new_name="TemplateMessage",
        ),
        migrations.RenameModel(
            old_name="Recipient",
            new_name="TemplateRecipient",
        ),
        migrations.AlterModelOptions(
            name="postaldomaindnserror",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "Postal: Domain DNS Error",
                "verbose_name_plural": "Postal: Domain DNS Errors",
            },
        ),
        migrations.AlterModelOptions(
            name="postalmessagelinkclicked",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "Postal: MessageLinkClicked",
                "verbose_name_plural": "Postal: MessageLinkClicked",
            },
        ),
        migrations.AlterModelOptions(
            name="postalmessageloaded",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name": "Postal: Message Loaded",
                "verbose_name_plural": "Postal: Messages Loaded",
            },
        ),
    ]
