# Generated by Django 5.1.4 on 2025-03-01 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0023_rename_domaindnserror_postaldomaindnserror_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="templaterecipient",
            unique_together={("email", "to_address")},
        ),
    ]
