# Generated by Django 5.1.4 on 2025-03-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0024_alter_templaterecipient_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postalmessage",
            name="message_timestamp",
        ),
        migrations.AddField(
            model_name="postalmessage",
            name="message_dict",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="postalmessage",
            name="received_at",
            field=models.DateTimeField(null=True),
        ),
    ]
