# Generated by Django 5.1.4 on 2025-03-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0025_remove_postalmessage_message_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="templaterecipient",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
