# Generated by Django 5.1.4 on 2025-03-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0026_templaterecipient_remarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postalmessage",
            name="time",
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
