# Generated by Django 5.2b1 on 2025-03-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0027_alter_postalmessage_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postalmessage",
            name="sent_with_ssl",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
