# Generated by Django 5.1 on 2025-03-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0030_templaterecipientfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="templaterecipientfile",
            name="process_on_save",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="templaterecipientfile",
            name="processed",
            field=models.BooleanField(default=False),
        ),
    ]
