# Generated by Django 5.1 on 2025-03-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0031_templaterecipientfile_process_on_save_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templaterecipientfile",
            name="process_on_save",
            field=models.BooleanField(default=True),
        ),
    ]
