# Generated by Django 5.1 on 2025-03-31 19:26

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0032_alter_templaterecipientfile_process_on_save"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templaterecipientfile",
            name="file",
            field=models.FileField(
                storage=storages.backends.s3.S3Storage(
                    default_acl="private",
                    gzip=False,
                    location="private",
                    querystring_auth=True,
                ),
                upload_to="emails/recipients-files/",
            ),
        ),
    ]
