# Generated by Django 5.2 on 2025-04-20 11:55

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0023_contactmessage_site"),
        ("emails", "0033_alter_templaterecipientfile_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="postalreplymessage",
            name="contact_message",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.contactmessage",
            ),
        ),
        migrations.AlterField(
            model_name="postalreplymessage",
            name="postal_message",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="emails.postalmessage",
            ),
        ),
    ]
