# Generated by Django 5.2 on 2025-04-20 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0023_contactmessage_site"),
        ("emails", "0034_postalreplymessage_contact_message_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PostalReplyMessage",
            new_name="ReplyMessage",
        ),
    ]
