# Generated by Django 5.2 on 2025-04-20 18:43

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0035_rename_postalreplymessage_replymessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="replymessage",
            name="sender",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="emails.sender",
            ),
        ),
    ]
