# Generated by Django 5.2 on 2025-06-15 18:44

import auto_prefetch
import datetime
import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.manager
import one.db
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("website", models.URLField(max_length=128, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "jobs_page_url",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "jobs_page_html",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("jobs_scrape_ready", models.BooleanField(default=False)),
                ("jobs_container_tag", models.CharField(default="div")),
                (
                    "jobs_container_class",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "jobs_container_id",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "job_link_class",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("job_detail_container_tag", models.CharField(default="main")),
                (
                    "job_detail_container_class",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "job_detail_container_id",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "job_application_methods",
                    one.db.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("email", "Email"),
                                ("website", "Own website"),
                                ("external", "External service"),
                            ],
                            max_length=32,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "company",
                "verbose_name_plural": "companies",
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CompanyLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("local_name", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "company",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                    ),
                ),
                (
                    "geoinfo",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geo.googlegeoinfo",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_hr", models.BooleanField(default=False)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("m", "male"), ("f", "female")],
                        max_length=64,
                        null=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                (
                    "full_name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.text.Concat(
                            "first_name", models.Value(" "), "last_name"
                        ),
                        output_field=models.CharField(max_length=128),
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=64, null=True)),
                ("phone", models.CharField(blank=True, max_length=64, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "company",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("de", "German"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("pt", "Portuguese"),
                        ],
                        default="de",
                        max_length=8,
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("body", models.TextField(blank=True, null=True)),
                ("job_id", models.CharField(blank=True, max_length=64, null=True)),
                ("source_url", models.URLField(blank=True, max_length=256, null=True)),
                ("duration", models.DurationField(default=datetime.timedelta(days=60))),
                ("expires_on", models.DateTimeField(editable=False)),
                ("is_active", models.BooleanField(default=True, editable=False)),
                (
                    "company",
                    auto_prefetch.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="companies.company",
                    ),
                ),
                (
                    "company_locations",
                    models.ManyToManyField(blank=True, to="companies.companylocation"),
                ),
                (
                    "recruiter",
                    auto_prefetch.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="companies.person",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
                "indexes": [
                    models.Index(
                        condition=models.Q(
                            ("company__isnull", False), ("is_active", True)
                        ),
                        fields=["company"],
                        name="job_company_fkey_idx",
                    ),
                    models.Index(
                        condition=models.Q(
                            ("recruiter__isnull", False), ("is_active", True)
                        ),
                        fields=["recruiter"],
                        name="job_recruiter_fkey_idx",
                    ),
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
