# Generated by Django 5.2 on 2025-07-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("m", "Male"), ("f", "Female")],
                max_length=64,
                null=True,
            ),
        ),
    ]
