# Generated by Django 5.2 on 2025-05-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_person"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="jobs_url",
            new_name="jobs_page_url",
        ),
        migrations.AddField(
            model_name="company",
            name="job_link_class",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="jobs_page_html",
            field=models.TextField(blank=True, null=True),
        ),
    ]
