# Generated by Django 5.2 on 2025-07-16 08:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_alter_person_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="temp_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
