# Generated by Django 5.2 on 2025-05-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_company_jobs_container_class_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="application_methods",
            new_name="job_application_methods",
        ),
        migrations.AddField(
            model_name="company",
            name="jobs_scrape_ready",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="company",
            name="jobs_page_html",
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="website",
            field=models.URLField(max_length=128, null=True),
        ),
    ]
