# Generated by Django 5.2 on 2025-07-16 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_remove_job_id_alter_job_temp_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="temp_id",
            new_name="id",
        ),
    ]
