# Generated by Django 5.2 on 2025-07-16 08:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_rename_temp_id_job_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
