# Generated by Django 5.2 on 2025-05-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "companies",
            "0005_rename_application_methods_company_job_application_methods_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="jobs_container_id",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
