# Generated by Django 5.2 on 2025-05-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0006_company_jobs_container_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="job_detail_container_class",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="job_detail_container_id",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="job_detail_container_tag",
            field=models.CharField(default="main"),
        ),
    ]
