# Generated by Django 5.2 on 2025-07-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0006_alter_job_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="job_id",
        ),
    ]
