# Generated by Django 5.2 on 2025-07-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0007_remove_job_job_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="company_locations",
        ),
    ]
