# Generated by Django 5.2 on 2025-07-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0008_remove_job_company_locations"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="company_locations",
            field=models.ManyToManyField(blank=True, to="companies.companylocation"),
        ),
    ]
