# Generated by Django 5.2 on 2025-05-17 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0008_job"),
    ]

    operations = [
        migrations.RenameField(
            model_name="companylocation",
            old_name="geo_info",
            new_name="geoinfo",
        ),
    ]
