# Generated by Django 5.2 on 2025-07-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0009_job_company_locations"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
