# Generated by Django 5.2 on 2025-05-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0009_rename_geo_info_companylocation_geoinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="companylocation",
            name="local_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
