# Generated by Django 5.1.4 on 2024-12-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlessection",
            name="title_de",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="articlessection",
            name="title_el",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="articlessection",
            name="title_en",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="articlessection",
            name="title_es",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="articlessection",
            name="title_fr",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="articlessection",
            name="title_it",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="articlessection",
            name="title_nl",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="articlessection",
            name="title_pl",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="articlessection",
            name="title_pt",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="articlessection",
            name="title_ru",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="articlessection",
            name="title_sk",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="articlessection",
            name="title_sl",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="articlessection",
            name="title_sv",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="articlessection",
            name="title_tr",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="articlessection",
            name="title_uk",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
