# Generated by Django 5.1.4 on 2024-12-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_remove_benefitssection_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="herosection",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="home",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="problemsection",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="solutionsection",
            name="is_active",
        ),
    ]
