# Generated by Django 5.1.4 on 2024-12-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_articlessection_card_animation_event_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlessection",
            name="card_animation_event",
            field=models.CharField(
                blank=True,
                choices=[
                    ("onclick", "onclick: A user clicks on an element"),
                    ("oncontextmenu", "oncontextmenu: Right-clicks on an element"),
                    ("ondblclick", "ondblclick: A user double-clicks on an element"),
                    ("onmousedown", "onmousedown: Button is pressed over an element"),
                    ("onmouseenter", "onmouseenter: Pointer moves into an element"),
                    ("onmouseleave", "onmouseleave: Pointer moves out of an element"),
                    ("onmousemove", "onmousemove: Pointer moves over an element"),
                    (
                        "onmouseout",
                        "onmouseout: The mouse pointer moves out of an element",
                    ),
                    ("onmouseover", "onmouseover: Pointer moves onto an element"),
                    (
                        "onmouseup",
                        "onmouseup: A mouse button is released over an element",
                    ),
                    ("ontouchcancel", "ontouchcancel: A touch is interrupted"),
                    (
                        "ontouchend",
                        "ontouchend: A finger is removed from a touch screen",
                    ),
                    (
                        "ontouchmove",
                        "ontouchmove: A finger is dragged across the screen",
                    ),
                    ("ontouchstart", "ontouchstart: Finger is placed on screen"),
                ],
                default="onmouseover",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="articlessection",
            name="card_animation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vanilla", "Vanilla"),
                    ("onmouseover", "On event: onmouseover"),
                ],
                default="onmouseover",
                max_length=16,
                null=True,
            ),
        ),
    ]
