# Generated by Django 5.1.4 on 2024-12-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "home",
            "0012_rename_card_animation_articlessection_card_animation_class_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlessection",
            name="card_animation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vanilla", "Vanilla"),
                    ("onmouseover", "On event: onmouseover"),
                ],
                default="onmouseover",
                max_length=16,
                null=True,
            ),
        ),
    ]
