# Generated by Django 5.1.4 on 2024-12-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_alter_articlessection_card_animation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlessection",
            name="card_animation_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bounce", "Bounce"),
                    ("flash", "Flash"),
                    ("pulse", "Pulse"),
                    ("rubberBand", "Rubber Band"),
                    ("shakeX", "Shake X"),
                    ("shakeY", "Shake Y"),
                    ("headShake", "Head Shake"),
                    ("swing", "Swing"),
                    ("tada", "Tada"),
                    ("wobble", "Wobble"),
                    ("jello", "Jello"),
                    ("heartBeat", "Heart Beat"),
                ],
                default="pulse",
                max_length=16,
                null=True,
            ),
        ),
    ]
