# Generated by Django 5.1.4 on 2024-12-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_alter_articlessection_card_animation_repeat"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlessection",
            name="card_animation_delay",
            field=models.CharField(
                blank=True,
                choices=[
                    ("2s", "2 Seconds"),
                    ("3s", "3 Seconds"),
                    ("4s", "4 Seconds"),
                    ("5s", "5 Seconds"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="articlessection",
            name="card_animation_speed",
            field=models.CharField(
                blank=True,
                choices=[
                    ("slow", "Slow 2s"),
                    ("slower", "Slow 3s"),
                    ("fast", "Fast 800ms"),
                    ("faster", "Faster 500ms"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="herosection",
            name="cta_animation_delay",
            field=models.CharField(
                blank=True,
                choices=[
                    ("2s", "2 Seconds"),
                    ("3s", "3 Seconds"),
                    ("4s", "4 Seconds"),
                    ("5s", "5 Seconds"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="herosection",
            name="cta_animation_repeat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("repeat-1", "1 Time"),
                    ("repeat-2", "2 Times"),
                    ("repeat-3", "3 Times"),
                    ("infinite", "Infinite times"),
                ],
                default="repeat-1",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="herosection",
            name="cta_animation_speed",
            field=models.CharField(
                blank=True,
                choices=[
                    ("slow", "Slow 2s"),
                    ("slower", "Slow 3s"),
                    ("fast", "Fast 800ms"),
                    ("faster", "Faster 500ms"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="articlessection",
            name="card_animation_repeat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("repeat-1", "1 Time"),
                    ("repeat-2", "2 Times"),
                    ("repeat-3", "3 Times"),
                    ("infinite", "Infinite times"),
                ],
                default="repeat-1",
                max_length=16,
                null=True,
            ),
        ),
    ]
