# Generated by Django 5.1.4 on 2025-01-08 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_articlessection_card_animation_delay_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserHome",
        ),
    ]
