# Generated by Django 5.1.4 on 2025-01-26 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0022_alter_articlessection_languages_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="articlessection",
            old_name="languages",
            new_name="rest_languages",
        ),
        migrations.RenameField(
            model_name="benefitssection",
            old_name="languages",
            new_name="rest_languages",
        ),
        migrations.RenameField(
            model_name="faqssection",
            old_name="languages",
            new_name="rest_languages",
        ),
        migrations.RenameField(
            model_name="herosection",
            old_name="languages",
            new_name="rest_languages",
        ),
        migrations.RenameField(
            model_name="home",
            old_name="languages",
            new_name="rest_languages",
        ),
        migrations.RenameField(
            model_name="solutionsection",
            old_name="languages",
            new_name="rest_languages",
        ),
        migrations.RenameField(
            model_name="stepaction",
            old_name="languages",
            new_name="rest_languages",
        ),
    ]
