# Generated by Django 5.1.4 on 2025-01-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0023_rename_languages_articlessection_rest_languages_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="faqssection",
            old_name="auto_add_categories",
            new_name="categories",
        ),
        migrations.RemoveField(
            model_name="articlessection",
            name="articles",
        ),
        migrations.RemoveField(
            model_name="articlessection",
            name="auto_add_articles",
        ),
        migrations.RemoveField(
            model_name="faqssection",
            name="auto_add_faqs",
        ),
        migrations.RemoveField(
            model_name="faqssection",
            name="faqs",
        ),
    ]
