# Generated by Django 5.1.4 on 2025-01-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0024_rename_auto_add_categories_faqssection_categories_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="articlessection",
            old_name="rest_languages",
            new_name="languages",
        ),
        migrations.RenameField(
            model_name="benefitssection",
            old_name="rest_languages",
            new_name="languages",
        ),
        migrations.RenameField(
            model_name="faqssection",
            old_name="rest_languages",
            new_name="languages",
        ),
        migrations.RenameField(
            model_name="herosection",
            old_name="rest_languages",
            new_name="languages",
        ),
        migrations.RenameField(
            model_name="home",
            old_name="rest_languages",
            new_name="languages",
        ),
        migrations.RenameField(
            model_name="solutionsection",
            old_name="rest_languages",
            new_name="languages",
        ),
        migrations.RenameField(
            model_name="stepaction",
            old_name="rest_languages",
            new_name="languages",
        ),
    ]
