# Generated by Django 5.1 on 2025-03-15 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0026_problemsection_default_language_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlessection",
            name="default_language",
        ),
        migrations.RemoveField(
            model_name="articlessection",
            name="languages",
        ),
        migrations.RemoveField(
            model_name="benefitssection",
            name="default_language",
        ),
        migrations.RemoveField(
            model_name="benefitssection",
            name="languages",
        ),
        migrations.RemoveField(
            model_name="faqssection",
            name="default_language",
        ),
        migrations.RemoveField(
            model_name="faqssection",
            name="languages",
        ),
        migrations.RemoveField(
            model_name="herosection",
            name="default_language",
        ),
        migrations.RemoveField(
            model_name="herosection",
            name="languages",
        ),
        migrations.RemoveField(
            model_name="home",
            name="default_language",
        ),
        migrations.RemoveField(
            model_name="home",
            name="languages",
        ),
        migrations.RemoveField(
            model_name="problemsection",
            name="default_language",
        ),
        migrations.RemoveField(
            model_name="problemsection",
            name="languages",
        ),
        migrations.RemoveField(
            model_name="solutionsection",
            name="default_language",
        ),
        migrations.RemoveField(
            model_name="solutionsection",
            name="languages",
        ),
        migrations.RemoveField(
            model_name="stepaction",
            name="default_language",
        ),
        migrations.RemoveField(
            model_name="stepaction",
            name="languages",
        ),
    ]
