# Generated by Django 5.1.7 on 2025-03-16 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0027_remove_articlessection_default_language_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="home",
            name="display_faqs",
        ),
        migrations.RemoveField(
            model_name="home",
            name="display_last_articles",
        ),
        migrations.RemoveField(
            model_name="home",
            name="enable_section_changing",
        ),
        migrations.RemoveField(
            model_name="home",
            name="num_articles",
        ),
    ]
