# Generated by Django 5.1.7 on 2025-03-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0028_remove_home_display_faqs_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="home",
            name="benefits_title",
        ),
        migrations.RemoveField(
            model_name="home",
            name="steps_title",
        ),
    ]
