# Generated by Django 5.1 on 2025-03-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0031_remove_articlessection_title_el_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="home",
            name="template_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("home/home.html", "Standard"),
                    ("home/saas.html", "SaaS"),
                    ("home/portfolio.html", "Portfolio"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="home",
            name="view_type",
            field=models.CharField(
                choices=[
                    ("one.home.views.home_view", "Standard home view"),
                    ("one.dgt.views.test_index", "DGT view"),
                    ("one.quiz.views.quiz_list", "English quizzes view"),
                ],
                default="one.home.views.home_view",
            ),
        ),
    ]
