# Generated by Django 5.1 on 2025-03-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0032_home_template_name_home_view_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="template_name",
            field=models.CharField(
                choices=[
                    ("home/home.html", "Standard"),
                    ("home/saas.html", "SaaS"),
                    ("home/portfolio.html", "Portfolio"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="home",
            name="view_type",
            field=models.CharField(
                choices=[
                    ("home", "Standard home"),
                    ("dgt", "DGT"),
                    ("english", "English quizzes"),
                ],
                default="home",
            ),
        ),
    ]
