# Generated by Django 5.1 on 2025-03-31 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0033_alter_home_template_name_alter_home_view_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="home",
            name="template_name",
        ),
        migrations.RemoveField(
            model_name="home",
            name="view_type",
        ),
    ]
