# Generated by Django 5.2 on 2025-04-07 22:27

import auto_prefetch
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0035_remove_benefitssection_emoji_benefitssection_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="benefititem",
            name="section",
        ),
        migrations.AddField(
            model_name="benefititem",
            name="home",
            field=auto_prefetch.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="home.home"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="home",
            name="benefits_title",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name="BenefitsSection",
        ),
    ]
