# Generated by Django 5.2 on 2025-04-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0038_home_steps_title"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="articlessection",
        #     name="card_animation",
        # ),
        # migrations.RemoveField(
        #     model_name="herosection",
        #     name="cta_animation",
        # ),
    ]
