# Generated by Django 5.2 on 2025-04-08 16:56

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0019_animation"),
        ("home", "0039_remove_articlessection_card_animation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlessection",
            name="card_animation",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.animation",
            ),
        ),
        migrations.AddField(
            model_name="herosection",
            name="cta_animation",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.animation",
            ),
        ),
    ]
