# Generated by Django 5.2 on 2025-04-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0040_articlessection_card_animation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemsection",
            name="emoji",
            field=models.CharField(db_default="⚠️", max_length=8),
        ),
    ]
