# Generated by Django 5.2 on 2025-04-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0042_solutionsection_emoji_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="benefititem",
            name="emoji",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
