# Generated by Django 5.2 on 2025-04-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0045_stepactionsection_description_de_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="benefititem",
            name="emoji",
            field=models.CharField(db_default="🚀", max_length=8),
        ),
        migrations.DeleteModel(
            name="StepAction",
        ),
    ]
