# Generated by Django 5.2 on 2025-04-20 06:57

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0046_alter_benefititem_emoji_delete_stepaction"),
        ("links", "0017_rename_django_url_path_link_url_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faqssection",
            name="title",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="faqssection",
            name="title_de",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="faqssection",
            name="title_en",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="faqssection",
            name="title_es",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="faqssection",
            name="title_fr",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="faqssection",
            name="title_it",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="faqssection",
            name="title_nl",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="faqssection",
            name="title_pt",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="problemsection",
            name="title",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="problemsection",
            name="title_de",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="problemsection",
            name="title_en",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="problemsection",
            name="title_es",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="problemsection",
            name="title_fr",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="problemsection",
            name="title_it",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="problemsection",
            name="title_nl",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="problemsection",
            name="title_pt",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="solutionsection",
            name="title",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="solutionsection",
            name="title_de",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="solutionsection",
            name="title_en",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="solutionsection",
            name="title_es",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="solutionsection",
            name="title_fr",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="solutionsection",
            name="title_it",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="solutionsection",
            name="title_nl",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="solutionsection",
            name="title_pt",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="stepactionsection",
            name="title",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="stepactionsection",
            name="title_de",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="stepactionsection",
            name="title_en",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="stepactionsection",
            name="title_es",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="stepactionsection",
            name="title_fr",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="stepactionsection",
            name="title_it",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="stepactionsection",
            name="title_nl",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="stepactionsection",
            name="title_pt",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.CreateModel(
            name="FinalCTASection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=256)),
                ("description", models.TextField()),
                ("cta_title", models.CharField(blank=True, max_length=64, null=True)),
                ("cta_new_tab", models.BooleanField(default=False)),
                (
                    "cta_link",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="links.link"
                    ),
                ),
                (
                    "home",
                    auto_prefetch.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="home.home"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
