# Generated by Django 5.2 on 2025-04-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0047_alter_faqssection_title_alter_faqssection_title_de_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalctasection",
            name="cta_title_de",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="finalctasection",
            name="cta_title_en",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="finalctasection",
            name="cta_title_es",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="finalctasection",
            name="cta_title_fr",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="finalctasection",
            name="cta_title_it",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="finalctasection",
            name="cta_title_nl",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="finalctasection",
            name="cta_title_pt",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="finalctasection",
            name="description_de",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="finalctasection",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="finalctasection",
            name="description_es",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="finalctasection",
            name="description_fr",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="finalctasection",
            name="description_it",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="finalctasection",
            name="description_nl",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="finalctasection",
            name="description_pt",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="finalctasection",
            name="title_de",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="finalctasection",
            name="title_en",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="finalctasection",
            name="title_es",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="finalctasection",
            name="title_fr",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="finalctasection",
            name="title_it",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="finalctasection",
            name="title_nl",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="finalctasection",
            name="title_pt",
            field=models.TextField(max_length=256, null=True),
        ),
    ]
