# Generated by Django 5.2 on 2025-04-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0048_finalctasection_cta_title_de_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlessection",
            name="emoji",
            field=models.CharField(db_default="📝", max_length=8),
        ),
        migrations.AddField(
            model_name="articlessection",
            name="show_all_link",
            field=models.BooleanField(db_default=True),
        ),
        migrations.AddField(
            model_name="articlessection",
            name="show_created_on",
            field=models.BooleanField(db_default=True),
        ),
    ]
