# Generated by Django 5.2 on 2025-05-21 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dgt", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sessiondgtquestion",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="sessiondgttest",
            old_name="created_on",
            new_name="created_at",
        ),
    ]
