# Generated by Django 5.1.4 on 2025-01-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dgt", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="title",
            field=models.TextField(max_length=512),
        ),
    ]
