# Generated by Django 5.1.4 on 2025-01-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dgt", "0002_alter_question_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="img_alt",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="img_url",
            field=models.URLField(max_length=256),
        ),
        migrations.AlterField(
            model_name="question",
            name="option_a",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="question",
            name="option_b",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="question",
            name="option_c",
            field=models.CharField(max_length=512),
        ),
    ]
