# Generated by Django 5.1.4 on 2025-01-11 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dgt", "0003_alter_question_img_alt_alter_question_img_url_and_more"),
        ("sessions", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Question",
            new_name="DgtQuestion",
        ),
        migrations.RenameModel(
            old_name="Test",
            new_name="DgtTest",
        ),
        migrations.RenameModel(
            old_name="SessionQuestion",
            new_name="SessionDgtQuestion",
        ),
        migrations.RenameModel(
            old_name="SessionTest",
            new_name="SessionDgtTest",
        ),
    ]
