# Generated by Django 5.1.4 on 2025-01-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dgt", "0004_rename_question_dgtquestion_rename_test_dgttest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dgttest",
            name="dgt_page",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
