# Generated by Django 5.1.4 on 2025-01-12 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dgt", "0005_dgttest_dgt_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessiondgtquestion",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="sessiondgttest",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
