# Generated by Django 5.1.4 on 2025-03-09 07:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dgt", "0006_sessiondgtquestion_created_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dgttest",
            name="scrapped_on",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
