# Generated by Django 5.1.4 on 2025-03-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dgt", "0007_dgttest_scrapped_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="dgtquestion",
            name="image",
            field=models.ImageField(null=True, upload_to="dgt/questions"),
        ),
    ]
