# Generated by Django 5.1.3 on 2024-11-23 12:20

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="submodule_folder",
            field=auto_prefetch.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="pages.pagesfolder",
            ),
            preserve_default=False,
        ),
    ]
