# Generated by Django 5.1.3 on 2024-11-07 21:03

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="body_de",
            field=markdownx.models.MarkdownxField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="body_en",
            field=markdownx.models.MarkdownxField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="body_es",
            field=markdownx.models.MarkdownxField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="slug_de",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="slug_en",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="slug_es",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="title_de",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="title_en",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="title_es",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
    ]
