# Generated by Django 5.1.4 on 2024-12-09 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="body_eo",
        ),
        migrations.RemoveField(
            model_name="page",
            name="body_fi",
        ),
        migrations.RemoveField(
            model_name="page",
            name="body_nn",
        ),
        migrations.RemoveField(
            model_name="page",
            name="body_sq",
        ),
        migrations.RemoveField(
            model_name="page",
            name="body_sr",
        ),
        migrations.RemoveField(
            model_name="page",
            name="slug_eo",
        ),
        migrations.RemoveField(
            model_name="page",
            name="slug_fi",
        ),
        migrations.RemoveField(
            model_name="page",
            name="slug_nn",
        ),
        migrations.RemoveField(
            model_name="page",
            name="slug_sq",
        ),
        migrations.RemoveField(
            model_name="page",
            name="slug_sr",
        ),
        migrations.RemoveField(
            model_name="page",
            name="title_eo",
        ),
        migrations.RemoveField(
            model_name="page",
            name="title_fi",
        ),
        migrations.RemoveField(
            model_name="page",
            name="title_nn",
        ),
        migrations.RemoveField(
            model_name="page",
            name="title_sq",
        ),
        migrations.RemoveField(
            model_name="page",
            name="title_sr",
        ),
    ]
