# Generated by Django 5.1.4 on 2024-12-09 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_remove_page_body_pt_br_remove_page_slug_pt_br_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="body_uk",
        ),
        migrations.RemoveField(
            model_name="page",
            name="slug_uk",
        ),
        migrations.RemoveField(
            model_name="page",
            name="title_uk",
        ),
    ]
