# Generated by Django 5.1.3 on 2024-11-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_page_body_el_page_body_eo_page_body_fi_page_body_it_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="allow_translation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="page",
            name="override_translated_fields",
            field=models.BooleanField(default=False),
        ),
    ]
