# Generated by Django 5.1.4 on 2024-12-16 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_page_body_uk_page_slug_uk_page_title_uk"),
        ("sites", "0009_rename_domain_host_alter_site_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PagesSubmodule",
            new_name="PageParentFolder",
        ),
        migrations.RenameField(
            model_name="page",
            old_name="submodule",
            new_name="parent",
        ),
    ]
