# Generated by Django 5.1.3 on 2024-11-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_rename_pagesfolder_pagessubmodule"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagessubmodule",
            name="sites",
            field=models.ManyToManyField(to="sites.site"),
        ),
    ]
