# Generated by Django 5.1.3 on 2024-11-27 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_pagessubmodule_sites"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="allow_translation",
        ),
        migrations.RemoveField(
            model_name="page",
            name="override_translated_fields",
        ),
    ]
