# Generated by Django 5.1.3 on 2024-11-27 21:31

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_remove_page_allow_translation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="submodule",
            field=auto_prefetch.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="pages.pagessubmodule",
            ),
            preserve_default=False,
        ),
    ]
