# Generated by Django 5.1.3 on 2024-11-15 17:14

import auto_prefetch
import codebase.utils.abstracts
import django.db.models.deletion
import django.db.models.manager

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("articles", "0001_initial"),
        ("faqs", "0001_initial"),
        ("links", "__first__"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQsSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("title_en", models.CharField(max_length=64, null=True)),
                ("title_de", models.CharField(max_length=64, null=True)),
                ("title_es", models.CharField(max_length=64, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("enable_section_changing", models.BooleanField(default=False)),
                ("auto_add_articles", models.BooleanField(default=False)),
                ("allow_field_translation", models.BooleanField(default=False)),
                (
                    "benefits_title",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("steps_title", models.CharField(blank=True, max_length=64, null=True)),
                ("faqs_title", models.CharField(blank=True, max_length=64, null=True)),
                ("articles", models.ManyToManyField(to="articles.article")),
                ("faqs", models.ManyToManyField(to="faqs.faq")),
                (
                    "site",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.site"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            bases=(models.Model, codebase.utils.abstracts.PageMixin),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.TextField(max_length=256)),
                ("headline_en", models.TextField(max_length=256, null=True)),
                ("headline_de", models.TextField(max_length=256, null=True)),
                ("headline_es", models.TextField(max_length=256, null=True)),
                ("subheadline", models.TextField(max_length=256)),
                ("subheadline_en", models.TextField(max_length=256, null=True)),
                ("subheadline_de", models.TextField(max_length=256, null=True)),
                ("subheadline_es", models.TextField(max_length=256, null=True)),
                ("cta_title", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "cta_title_en",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "cta_title_de",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "cta_title_es",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("cta_new_tab", models.BooleanField(default=False)),
                ("image", models.ImageField(upload_to="homepages/hero/")),
                ("is_active", models.BooleanField()),
                ("allow_field_translation", models.BooleanField(default=False)),
                (
                    "cta_link",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="links.link"
                    ),
                ),
                (
                    "homepage",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.homepage"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Benefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emoji", models.CharField(max_length=8)),
                ("is_active", models.BooleanField()),
                (
                    "homepage",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.homepage"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ProblemSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("is_active", models.BooleanField()),
                (
                    "homepage",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.homepage"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="SolutionSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("is_active", models.BooleanField()),
                (
                    "homepage",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.homepage"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="StepAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_label", models.CharField(default="01", max_length=4)),
                ("title", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("is_active", models.BooleanField()),
                (
                    "homepage",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.homepage"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
