# Generated by Django 5.1.3 on 2024-12-07 22:36

import codebase.base.utils.mixins
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BenefitsSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emoji", models.CharField(max_length=8)),
                ("is_active", models.BooleanField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allow_translation", models.BooleanField(default=False)),
                ("override_translated_fields", models.BooleanField(default=False)),
                ("headline", models.TextField(max_length=256)),
                ("headline_en", models.TextField(max_length=256, null=True)),
                ("headline_de", models.TextField(max_length=256, null=True)),
                ("headline_es", models.TextField(max_length=256, null=True)),
                ("headline_fr", models.TextField(max_length=256, null=True)),
                ("headline_el", models.TextField(max_length=256, null=True)),
                ("headline_eo", models.TextField(max_length=256, null=True)),
                ("headline_fi", models.TextField(max_length=256, null=True)),
                ("headline_it", models.TextField(max_length=256, null=True)),
                ("headline_nl", models.TextField(max_length=256, null=True)),
                ("headline_nn", models.TextField(max_length=256, null=True)),
                ("headline_pl", models.TextField(max_length=256, null=True)),
                ("headline_pt", models.TextField(max_length=256, null=True)),
                ("headline_pt_br", models.TextField(max_length=256, null=True)),
                ("headline_ru", models.TextField(max_length=256, null=True)),
                ("headline_sk", models.TextField(max_length=256, null=True)),
                ("headline_sl", models.TextField(max_length=256, null=True)),
                ("headline_sq", models.TextField(max_length=256, null=True)),
                ("headline_sr", models.TextField(max_length=256, null=True)),
                ("headline_sv", models.TextField(max_length=256, null=True)),
                ("headline_tr", models.TextField(max_length=256, null=True)),
                ("headline_uk", models.TextField(max_length=256, null=True)),
                ("subheadline", models.TextField(max_length=256)),
                ("subheadline_en", models.TextField(max_length=256, null=True)),
                ("subheadline_de", models.TextField(max_length=256, null=True)),
                ("subheadline_es", models.TextField(max_length=256, null=True)),
                ("subheadline_fr", models.TextField(max_length=256, null=True)),
                ("subheadline_el", models.TextField(max_length=256, null=True)),
                ("subheadline_eo", models.TextField(max_length=256, null=True)),
                ("subheadline_fi", models.TextField(max_length=256, null=True)),
                ("subheadline_it", models.TextField(max_length=256, null=True)),
                ("subheadline_nl", models.TextField(max_length=256, null=True)),
                ("subheadline_nn", models.TextField(max_length=256, null=True)),
                ("subheadline_pl", models.TextField(max_length=256, null=True)),
                ("subheadline_pt", models.TextField(max_length=256, null=True)),
                ("subheadline_pt_br", models.TextField(max_length=256, null=True)),
                ("subheadline_ru", models.TextField(max_length=256, null=True)),
                ("subheadline_sk", models.TextField(max_length=256, null=True)),
                ("subheadline_sl", models.TextField(max_length=256, null=True)),
                ("subheadline_sq", models.TextField(max_length=256, null=True)),
                ("subheadline_sr", models.TextField(max_length=256, null=True)),
                ("subheadline_sv", models.TextField(max_length=256, null=True)),
                ("subheadline_tr", models.TextField(max_length=256, null=True)),
                ("subheadline_uk", models.TextField(max_length=256, null=True)),
                ("cta_title", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "cta_title_en",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "cta_title_de",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "cta_title_es",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "cta_title_fr",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "cta_title_el",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "cta_title_eo",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "cta_title_fi",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "cta_title_it",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "cta_title_nl",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "cta_title_nn",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "cta_title_pl",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "cta_title_pt",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "cta_title_pt_br",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "cta_title_ru",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "cta_title_sk",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "cta_title_sl",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "cta_title_sq",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "cta_title_sr",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "cta_title_sv",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "cta_title_tr",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "cta_title_uk",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("cta_new_tab", models.BooleanField(default=False)),
                ("image", models.ImageField(upload_to="homepages/hero/")),
                ("is_active", models.BooleanField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allow_translation", models.BooleanField(default=False)),
                ("override_translated_fields", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("enable_section_changing", models.BooleanField(default=False)),
                ("display_last_articles", models.BooleanField(default=False)),
                ("num_articles", models.PositiveSmallIntegerField(default=6)),
                ("display_faqs", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=64)),
                ("title_en", models.CharField(max_length=64, null=True)),
                ("title_de", models.CharField(max_length=64, null=True)),
                ("title_es", models.CharField(max_length=64, null=True)),
                ("title_fr", models.CharField(max_length=64, null=True)),
                ("title_el", models.CharField(max_length=64, null=True)),
                ("title_eo", models.CharField(max_length=64, null=True)),
                ("title_fi", models.CharField(max_length=64, null=True)),
                ("title_it", models.CharField(max_length=64, null=True)),
                ("title_nl", models.CharField(max_length=64, null=True)),
                ("title_nn", models.CharField(max_length=64, null=True)),
                ("title_pl", models.CharField(max_length=64, null=True)),
                ("title_pt", models.CharField(max_length=64, null=True)),
                ("title_pt_br", models.CharField(max_length=64, null=True)),
                ("title_ru", models.CharField(max_length=64, null=True)),
                ("title_sk", models.CharField(max_length=64, null=True)),
                ("title_sl", models.CharField(max_length=64, null=True)),
                ("title_sq", models.CharField(max_length=64, null=True)),
                ("title_sr", models.CharField(max_length=64, null=True)),
                ("title_sv", models.CharField(max_length=64, null=True)),
                ("title_tr", models.CharField(max_length=64, null=True)),
                ("title_uk", models.CharField(max_length=64, null=True)),
                (
                    "benefits_title",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "benefits_title_en",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "benefits_title_de",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "benefits_title_es",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "benefits_title_fr",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "benefits_title_el",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "benefits_title_eo",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "benefits_title_fi",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "benefits_title_it",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "benefits_title_nl",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "benefits_title_nn",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "benefits_title_pl",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "benefits_title_pt",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "benefits_title_pt_br",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "benefits_title_ru",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "benefits_title_sk",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "benefits_title_sl",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "benefits_title_sq",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "benefits_title_sr",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "benefits_title_sv",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "benefits_title_tr",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "benefits_title_uk",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("steps_title", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "steps_title_en",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "steps_title_de",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "steps_title_es",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "steps_title_fr",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "steps_title_el",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "steps_title_eo",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "steps_title_fi",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "steps_title_it",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "steps_title_nl",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "steps_title_nn",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "steps_title_pl",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "steps_title_pt",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "steps_title_pt_br",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "steps_title_ru",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "steps_title_sk",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "steps_title_sl",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "steps_title_sq",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "steps_title_sr",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "steps_title_sv",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "steps_title_tr",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "steps_title_uk",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("faqs_title", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "faqs_title_en",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "faqs_title_de",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "faqs_title_es",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "faqs_title_fr",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "faqs_title_el",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "faqs_title_eo",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "faqs_title_fi",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "faqs_title_it",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "faqs_title_nl",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "faqs_title_nn",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "faqs_title_pl",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "faqs_title_pt",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "faqs_title_pt_br",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "faqs_title_ru",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "faqs_title_sk",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "faqs_title_sl",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "faqs_title_sq",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "faqs_title_sr",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "faqs_title_sv",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "faqs_title_tr",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "faqs_title_uk",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            bases=(models.Model, codebase.base.utils.mixins.PageMixin),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ProblemSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("is_active", models.BooleanField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="SolutionSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("is_active", models.BooleanField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="StepAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_label", models.CharField(default="01", max_length=4)),
                ("title", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("is_active", models.BooleanField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="UserHomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allow_translation", models.BooleanField(default=False)),
                ("override_translated_fields", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            bases=(models.Model, codebase.base.utils.mixins.PageMixin),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
