# Generated by Django 5.1.3 on 2024-11-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="site",
        ),
        migrations.AddField(
            model_name="homepage",
            name="sites",
            field=models.ManyToManyField(to="sites.site"),
        ),
    ]
