# Generated by Django 5.1.3 on 2024-11-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hero",
            name="headline_de",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="hero",
            name="headline_en",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="hero",
            name="headline_es",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="hero",
            name="subheadline_de",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="hero",
            name="subheadline_en",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="hero",
            name="subheadline_es",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="herocta",
            name="custom_title_de",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="herocta",
            name="custom_title_en",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="herocta",
            name="custom_title_es",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="title_de",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="title_en",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="title_es",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
