# Generated by Django 5.1.3 on 2024-11-15 16:54

import auto_prefetch
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("articles", "0001_initial"),
        ("faqs", "0001_initial"),
        ("home", "0001_initial"),
        ("links", "0001_initial"),
        ("sites", "0005_delete_extendedsite"),
    ]

    operations = [
        migrations.AddField(
            model_name="herosection",
            name="cta_link",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="links.link"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="articles",
            field=models.ManyToManyField(to="articles.article"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faqs",
            field=models.ManyToManyField(to="faqs.faq"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="site",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sites.site"
            ),
        ),
        migrations.AddField(
            model_name="herosection",
            name="homepage",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.homepage"
            ),
        ),
        migrations.AddField(
            model_name="benefit",
            name="homepage",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.homepage"
            ),
        ),
        migrations.AddField(
            model_name="problemsection",
            name="homepage",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.homepage"
            ),
        ),
        migrations.AddField(
            model_name="solutionsection",
            name="homepage",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.homepage"
            ),
        ),
        migrations.AddField(
            model_name="stepaction",
            name="homepage",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.homepage"
            ),
        ),
    ]
