# Generated by Django 5.1.4 on 2024-12-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faqs", "0004_faq_featured"),
        ("home", "0002_articlessection_title_de_articlessection_title_el_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="benefitssection",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="stepaction",
            name="is_active",
        ),
        migrations.AddField(
            model_name="faqssection",
            name="auto_add_faqs",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="faqssection",
            name="faqs",
            field=models.ManyToManyField(
                limit_choices_to={"featured": True}, to="faqs.faq"
            ),
        ),
    ]
