# Generated by Django 5.1.3 on 2024-11-21 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_homepage_site_homepage_sites"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FAQsSection",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="faqs",
        ),
    ]
