# Generated by Django 5.1.3 on 2024-12-07 22:36

import auto_prefetch
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("home", "0002_initial"),
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="sites",
            field=models.ManyToManyField(to="sites.site"),
        ),
        migrations.AddField(
            model_name="herosection",
            name="homepage",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.homepage"
            ),
        ),
        migrations.AddField(
            model_name="benefitssection",
            name="homepage",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.homepage"
            ),
        ),
        migrations.AddField(
            model_name="problemsection",
            name="homepage",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.homepage"
            ),
        ),
        migrations.AddField(
            model_name="solutionsection",
            name="homepage",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.homepage"
            ),
        ),
        migrations.AddField(
            model_name="stepaction",
            name="homepage",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.homepage"
            ),
        ),
        migrations.AddField(
            model_name="userhomepage",
            name="sites",
            field=models.ManyToManyField(to="sites.site"),
        ),
    ]
