# Generated by Django 5.1.3 on 2024-11-10 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_hero_allow_field_translation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="allow_field_translation",
        ),
    ]
