# Generated by Django 5.1.3 on 2024-11-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_delete_faqssection_remove_homepage_faqs"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="benefits_title_de",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="benefits_title_en",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="benefits_title_es",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faqs_title_de",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faqs_title_en",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faqs_title_es",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="steps_title_de",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="steps_title_en",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="steps_title_es",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
