# Generated by Django 5.1.4 on 2024-12-21 09:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_remove_herosection_is_active_remove_home_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="faqssection",
            name="faq_categories",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("plans", "Plans"),
                        ("products", "Products"),
                        ("info", "Informative"),
                        ("accounts", "Accounts"),
                        ("legal", "Legal concerns"),
                    ],
                    max_length=32,
                ),
                default=[],
                size=None,
            ),
            preserve_default=False,
        ),
    ]
