# Generated by Django 5.1.3 on 2024-11-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_remove_homepage_allow_field_translation"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="allow_field_translation",
            field=models.BooleanField(default=False),
        ),
    ]
