# Generated by Django 5.1.4 on 2024-12-09 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_remove_herosection_cta_title_eo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="herosection",
            name="cta_title_pt_br",
        ),
        migrations.RemoveField(
            model_name="herosection",
            name="headline_pt_br",
        ),
        migrations.RemoveField(
            model_name="herosection",
            name="subheadline_pt_br",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="benefits_title_pt_br",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="faqs_title_pt_br",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="steps_title_pt_br",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="title_pt_br",
        ),
    ]
