# Generated by Django 5.1.4 on 2024-12-21 09:36

import codebase.base.utils.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_faqssection_faq_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faqssection",
            name="faq_categories",
            field=codebase.base.utils.db_fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("plans", "Plans"),
                        ("products", "Products"),
                        ("info", "Informative"),
                        ("accounts", "Accounts"),
                        ("legal", "Legal concerns"),
                    ],
                    max_length=32,
                ),
                size=None,
            ),
        ),
    ]
