# Generated by Django 5.1.3 on 2024-11-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_homepage_allow_field_translation"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
