# Generated by Django 5.1.3 on 2024-11-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_rename_show_last_articles_homepage_display_faqs_and_more"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="userhomepage",
            name="allow_field_translation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userhomepage",
            name="sites",
            field=models.ManyToManyField(to="sites.site"),
        ),
    ]
