# Generated by Django 5.1.4 on 2024-12-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_faqssection_faq_categories"),
    ]

    operations = [
        migrations.RenameField(
            model_name="faqssection",
            old_name="faq_categories",
            new_name="auto_add_categories",
        ),
    ]
