# Generated by Django 5.1.3 on 2024-11-23 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_remove_userhomepage_sites_userhomepage_sites"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userhomepage",
            old_name="sites",
            new_name="site",
        ),
    ]
