# Generated by Django 5.1.4 on 2024-12-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_remove_herosection_cta_title_uk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="herosection",
            name="cta_title_uk",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="herosection",
            name="headline_uk",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="herosection",
            name="subheadline_uk",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="benefits_title_uk",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faqs_title_uk",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="steps_title_uk",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="title_uk",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
