# Generated by Django 5.1.3 on 2024-11-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_herocta_custom_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herocta",
            name="custom_title",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="herocta",
            name="custom_title_de",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="herocta",
            name="custom_title_en",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="herocta",
            name="custom_title_es",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
