# Generated by Django 5.1.4 on 2024-12-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_articlessection_number_of_articles"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlessection",
            name="card_animation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("flip", "Flip"),
                    ("flipInX", "Flip In X"),
                    ("flipInY", "Flip In Y"),
                    ("flipOutX", "Flip Out X"),
                    ("flipOutY", "Flip Out Y"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="articlessection",
            name="card_animation_type",
            field=models.CharField(
                blank=True,
                choices=[("vanilla", "Vanilla"), ("on_event", "Based on event")],
                max_length=16,
                null=True,
            ),
        ),
    ]
