# Generated by Django 5.1.3 on 2024-11-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_herocta_custom_title_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hero",
            old_name="active",
            new_name="is_active",
        ),
        migrations.RenameField(
            model_name="homepage",
            old_name="active",
            new_name="is_active",
        ),
    ]
