# Generated by Django 5.1.4 on 2024-12-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_articlessection_card_animation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlessection",
            name="card_animation_event",
            field=models.CharField(
                blank=True,
                choices=[
                    ("onclick", "A user clicks on an element"),
                    ("oncontextmenu", "A user right-clicks on an element"),
                    ("ondblclick", "A user double-clicks on an element"),
                    ("onmousedown", "A mouse button is pressed over an element"),
                    ("onmouseenter", "The mouse pointer moves into an element"),
                    ("onmouseleave", "The mouse pointer moves out of an element"),
                    ("onmousemove", "The mouse pointer moves over an element"),
                    ("onmouseout", "The mouse pointer moves out of an element"),
                    ("onmouseover", "The mouse pointer moves onto an element"),
                    ("onmouseup", "A mouse button is released over an element"),
                    ("ontouchcancel", "A touch is interrupted"),
                    ("ontouchend", "A finger is removed from a touch screen"),
                    ("ontouchmove", "A finger is dragged across the screen"),
                    ("ontouchstart", "A finger is placed on a touch screen"),
                ],
                default="onmouseenter",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="articlessection",
            name="card_animation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("flip", "Flip"),
                    ("flipInX", "Flip In X"),
                    ("flipInY", "Flip In Y"),
                    ("flipOutX", "Flip Out X"),
                    ("flipOutY", "Flip Out Y"),
                ],
                default="flipInX",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="articlessection",
            name="card_animation_type",
            field=models.CharField(
                blank=True,
                choices=[("vanilla", "Vanilla"), ("on_event", "Based on event")],
                default="on_event",
                max_length=16,
                null=True,
            ),
        ),
    ]
