# Generated by Django 5.1.3 on 2024-11-23 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_remove_userhomepage_site_userhomepage_sites"),
    ]

    operations = [
        migrations.RenameField(
            model_name="herosection",
            old_name="allow_field_translation",
            new_name="allow_translation",
        ),
        migrations.RenameField(
            model_name="homepage",
            old_name="allow_field_translation",
            new_name="allow_translation",
        ),
        migrations.RenameField(
            model_name="userhomepage",
            old_name="allow_field_translation",
            new_name="allow_translation",
        ),
    ]
