# Generated by Django 5.1.3 on 2024-11-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_rename_active_hero_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="herocta",
            name="site",
        ),
    ]
