# Generated by Django 5.1.3 on 2024-11-10 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_remove_herocta_site"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="herocta",
            name="show_type",
        ),
    ]
