# Generated by Django 5.1.4 on 2024-12-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_rename_homepage_home_and_more"),
        ("links", "0007_link_custom_title_uk"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HeroSection",
            new_name="HomeHeroSection",
        ),
    ]
