# Generated by Django 5.1.3 on 2024-11-23 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "home",
            "0010_rename_allow_field_translation_herosection_allow_translation_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Benefit",
            new_name="BenefitsSection",
        ),
    ]
