# Generated by Django 5.1.3 on 2024-11-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_rename_benefit_benefitssection"),
    ]

    operations = [
        migrations.AddField(
            model_name="herosection",
            name="cta_title_fr",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="herosection",
            name="headline_fr",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="herosection",
            name="subheadline_fr",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="benefits_title_fr",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faqs_title_fr",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="steps_title_fr",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="title_fr",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
