# Generated by Django 5.1.3 on 2024-11-11 19:59

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_remove_herocta_show_type"),
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hero",
            name="cta_new",
            field=auto_prefetch.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="links.link"
            ),
        ),
    ]
