# Generated by Django 5.1.4 on 2024-12-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_alter_articlessection_card_animation_event_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="articlessection",
            old_name="card_animation",
            new_name="card_animation_class",
        ),
        migrations.RemoveField(
            model_name="articlessection",
            name="card_animation_event",
        ),
        migrations.AlterField(
            model_name="articlessection",
            name="card_animation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vanilla", "Vanilla"),
                    ("onmouseover", "On event: onmouseover"),
                    ("onclick", "onclick - NOT WORKING"),
                    ("onmouseenter", "On event: onmouseenter - NOT WORKING"),
                    ("onmouseleave", "onmouseleave - NOT WORKING"),
                    ("onmousemove", "onmousemove - NOT WORKING"),
                    ("onmouseout", "onmouseout - NOT WORKING"),
                    ("ontouchend", "ontouchend - NOT WORKING"),
                    ("ontouchmove", "ontouchmove - NOT WORKING"),
                    ("ontouchstart", "ontouchstart - NOT WORKING"),
                ],
                default="onmouseover",
                max_length=16,
                null=True,
            ),
        ),
    ]
