# Generated by Django 5.1.4 on 2024-12-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_rename_herosection_homeherosection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="title",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="home",
            name="title_de",
            field=models.CharField(default="", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="home",
            name="title_el",
            field=models.CharField(default="", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="home",
            name="title_en",
            field=models.CharField(default="", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="home",
            name="title_es",
            field=models.CharField(default="", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="home",
            name="title_fr",
            field=models.CharField(default="", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="home",
            name="title_it",
            field=models.CharField(default="", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="home",
            name="title_nl",
            field=models.CharField(default="", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="home",
            name="title_pl",
            field=models.CharField(default="", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="home",
            name="title_pt",
            field=models.CharField(default="", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="home",
            name="title_ru",
            field=models.CharField(default="", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="home",
            name="title_sk",
            field=models.CharField(default="", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="home",
            name="title_sl",
            field=models.CharField(default="", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="home",
            name="title_sv",
            field=models.CharField(default="", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="home",
            name="title_tr",
            field=models.CharField(default="", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="home",
            name="title_uk",
            field=models.CharField(default="", max_length=64, null=True),
        ),
    ]
