# Generated by Django 5.1.3 on 2024-11-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_hero_cta_new"),
    ]

    operations = [
        migrations.AddField(
            model_name="hero",
            name="cta_new_tab",
            field=models.BooleanField(default=False),
        ),
    ]
