# Generated by Django 5.1.3 on 2024-11-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_herosection_cta_title_el_herosection_cta_title_eo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="override_translated_fields",
            field=models.BooleanField(default=False),
        ),
    ]
