# Generated by Django 5.1.3 on 2024-11-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_homepage_override_translated_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="herosection",
            name="override_translated_fields",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userhomepage",
            name="override_translated_fields",
            field=models.BooleanField(default=False),
        ),
    ]
