# Generated by Django 5.1.3 on 2024-11-11 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_remove_hero_cta"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hero",
            old_name="cta_new",
            new_name="cta_link",
        ),
    ]
