# Generated by Django 5.1.3 on 2024-11-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_herosection_override_translated_fields_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="number_of_last_articles",
            field=models.PositiveSmallIntegerField(default=6),
        ),
    ]
