# Generated by Django 5.1.3 on 2024-11-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_rename_cta_new_hero_cta_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="hero",
            name="cta_title",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
