# Generated by Django 5.1.3 on 2024-11-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_hero_cta_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="hero",
            name="cta_title_de",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="hero",
            name="cta_title_en",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="hero",
            name="cta_title_es",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
