# Generated by Django 5.1.3 on 2024-11-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_remove_homepage_number_of_last_articles_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="num_articles",
            field=models.PositiveSmallIntegerField(default=6),
        ),
    ]
