# Generated by Django 5.1.4 on 2024-12-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_articlessection_card_animation_repeat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlessection",
            name="card_animation_repeat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("repeat-1", "1 Time"),
                    ("repeat-2", "2 Times"),
                    ("repeat-3", "3 Times"),
                    ("infinite", "Infinite times"),
                ],
                default="infinite",
                max_length=16,
                null=True,
            ),
        ),
    ]
