# Generated by Django 5.1.3 on 2024-11-11 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_hero_cta_title_de_hero_cta_title_en_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HeroCTA",
        ),
    ]
