# Generated by Django 5.1.3 on 2024-11-12 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_delete_herocta"),
        ("links", "0003_remove_link_new_tab"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HomePage",
            new_name="Home",
        ),
        migrations.RenameModel(
            old_name="Hero",
            new_name="HomeHero",
        ),
    ]
