# Generated by Django 5.1.3 on 2024-11-12 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_rename_homepage_home_rename_hero_homehero"),
        ("links", "0003_remove_link_new_tab"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Home",
            new_name="HomePage",
        ),
        migrations.RenameModel(
            old_name="HomeHero",
            new_name="HomePageHero",
        ),
    ]
