# Generated by Django 5.1.3 on 2024-11-12 11:00

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faqs", "0001_initial"),
        ("home", "0021_rename_homepagehero_herosection_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQsSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("home_faqs", models.ManyToManyField(to="faqs.faq")),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
