# Generated by Django 5.1.3 on 2024-11-12 12:30

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_article_sites"),
        ("faqs", "0001_initial"),
        ("home", "0022_faqssection"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepage",
            old_name="action_section_title",
            new_name="benefits_title",
        ),
        migrations.RenameField(
            model_name="homepage",
            old_name="benefit_section_title",
            new_name="faqs_title",
        ),
        migrations.RemoveField(
            model_name="faqssection",
            name="home_faqs",
        ),
        migrations.AddField(
            model_name="homepage",
            name="articles",
            field=models.ManyToManyField(to="articles.article"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="auto_add_articles",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="homepage",
            name="faqs",
            field=models.ManyToManyField(to="faqs.faq"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="steps_title",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name="StepAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_label", models.CharField(default="01", max_length=4)),
                ("title", models.CharField(max_length=64)),
                ("description", markdownx.models.MarkdownxField()),
                ("is_active", models.BooleanField()),
                (
                    "homepage",
                    auto_prefetch.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name="Action",
        ),
    ]
