# Generated by Django 5.1.3 on 2024-11-13 03:03

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0023_rename_action_section_title_homepage_benefits_title_and_more"),
        ("links", "0006_alter_link_unique_together"),
        ("sites", "0005_delete_extendedsite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herosection",
            name="cta_link",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="links.link"
            ),
        ),
        migrations.AlterField(
            model_name="herosection",
            name="homepage",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.homepage"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="site",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sites.site"
            ),
        ),
    ]
