# Generated by Django 5.2 on 2025-04-26 09:29

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("correct", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="DeeplLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=5)),
                ("supports_formality", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Lection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("slug", models.SlugField(blank=True)),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_one", models.CharField(blank=True, max_length=200, null=True)),
                ("text_two", models.CharField(blank=True, max_length=200, null=True)),
                ("text_three", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1: One text input"),
                            (2, "2: Two text inputs"),
                            (5, "5: One choice selection"),
                        ],
                        default=5,
                    ),
                ),
                (
                    "explanation",
                    models.TextField(blank=True, max_length=250, null=True),
                ),
                ("promoted", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("id",),
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "A1"),
                            (2, "A2"),
                            (3, "B1"),
                            (4, "B2"),
                            (5, "C1"),
                            (6, "C2"),
                        ],
                        default=5,
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("image_credits_url", models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TranslatedQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_text", models.CharField(max_length=650)),
                ("translated_text", models.CharField(max_length=650)),
                ("created", models.DateField(auto_now_add=True, null=True)),
                ("updated", models.DateField(auto_now=True, null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
