# Generated by Django 5.1.2 on 2024-11-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchterm",
            name="country_code",
            field=models.CharField(max_length=8, null=True),
        ),
    ]
