# Generated by Django 5.1.3 on 2024-11-06 18:28

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0020_remove_website_footer_links_separator"),
        ("search", "0002_alter_searchterm_country_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchterm",
            name="website",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.website",
            ),
        ),
    ]
