# Generated by Django 5.1.4 on 2024-12-19 19:34

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(editable=False, max_length=256)),
                (
                    "title_en",
                    models.CharField(editable=False, max_length=256, null=True),
                ),
                (
                    "title_de",
                    models.CharField(editable=False, max_length=256, null=True),
                ),
                (
                    "title_es",
                    models.CharField(editable=False, max_length=256, null=True),
                ),
                (
                    "title_fr",
                    models.CharField(editable=False, max_length=256, null=True),
                ),
                (
                    "title_el",
                    models.CharField(editable=False, max_length=256, null=True),
                ),
                (
                    "title_it",
                    models.CharField(editable=False, max_length=256, null=True),
                ),
                (
                    "title_nl",
                    models.CharField(editable=False, max_length=256, null=True),
                ),
                (
                    "title_pl",
                    models.CharField(editable=False, max_length=256, null=True),
                ),
                (
                    "title_pt",
                    models.CharField(editable=False, max_length=256, null=True),
                ),
                (
                    "title_ru",
                    models.CharField(editable=False, max_length=256, null=True),
                ),
                (
                    "title_sk",
                    models.CharField(editable=False, max_length=256, null=True),
                ),
                (
                    "title_sl",
                    models.CharField(editable=False, max_length=256, null=True),
                ),
                (
                    "title_sv",
                    models.CharField(editable=False, max_length=256, null=True),
                ),
                (
                    "title_tr",
                    models.CharField(editable=False, max_length=256, null=True),
                ),
                (
                    "title_uk",
                    models.CharField(editable=False, max_length=256, null=True),
                ),
                ("slug", models.SlugField(editable=False, max_length=128, unique=True)),
                (
                    "slug_en",
                    models.SlugField(
                        editable=False, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "slug_de",
                    models.SlugField(
                        editable=False, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "slug_es",
                    models.SlugField(
                        editable=False, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "slug_fr",
                    models.SlugField(
                        editable=False, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "slug_el",
                    models.SlugField(
                        editable=False, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "slug_it",
                    models.SlugField(
                        editable=False, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "slug_nl",
                    models.SlugField(
                        editable=False, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "slug_pl",
                    models.SlugField(
                        editable=False, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "slug_pt",
                    models.SlugField(
                        editable=False, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "slug_ru",
                    models.SlugField(
                        editable=False, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "slug_sk",
                    models.SlugField(
                        editable=False, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "slug_sl",
                    models.SlugField(
                        editable=False, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "slug_sv",
                    models.SlugField(
                        editable=False, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "slug_tr",
                    models.SlugField(
                        editable=False, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "slug_uk",
                    models.SlugField(
                        editable=False, max_length=128, null=True, unique=True
                    ),
                ),
                ("folder", models.CharField(editable=False, max_length=128)),
                ("subfolder", models.CharField(editable=False, max_length=256)),
                ("body", models.TextField(editable=False)),
                ("body_en", models.TextField(editable=False, null=True)),
                ("body_de", models.TextField(editable=False, null=True)),
                ("body_es", models.TextField(editable=False, null=True)),
                ("body_fr", models.TextField(editable=False, null=True)),
                ("body_el", models.TextField(editable=False, null=True)),
                ("body_it", models.TextField(editable=False, null=True)),
                ("body_nl", models.TextField(editable=False, null=True)),
                ("body_pl", models.TextField(editable=False, null=True)),
                ("body_pt", models.TextField(editable=False, null=True)),
                ("body_ru", models.TextField(editable=False, null=True)),
                ("body_sk", models.TextField(editable=False, null=True)),
                ("body_sl", models.TextField(editable=False, null=True)),
                ("body_sv", models.TextField(editable=False, null=True)),
                ("body_tr", models.TextField(editable=False, null=True)),
                ("body_uk", models.TextField(editable=False, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_on"],
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            # bases=(models.Model, one.base.utils.mixins.PageMixin),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="PageParentFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
