# Generated by Django 5.1.4 on 2024-12-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_rename_folder_page_folder_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={
                "base_manager_name": "prefetch_manager",
                "ordering": ["folder_name", "-created_on"],
            },
        ),
    ]
