# Generated by Django 5.1.4 on 2025-01-26 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_alter_page_slug_alter_page_slug_de_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={"base_manager_name": "prefetch_manager"},
        ),
        migrations.AlterUniqueTogether(
            name="page",
            unique_together=set(),
        ),
    ]
