# Generated by Django 5.1 on 2025-03-15 21:41

import auto_prefetch
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0001_initial"),
        ("sites", "0030_rename_default_language_site_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="description_de",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="description_el",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="description_en",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="description_es",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="description_fr",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="description_it",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="description_nl",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="description_pl",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="description_pt",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="description_ru",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="description_sk",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="description_sl",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="description_sv",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="description_tr",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="description_uk",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="site",
            field=auto_prefetch.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="sites.site"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plan",
            name="slug_de",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="slug_el",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="slug_en",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="slug_es",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="slug_fr",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="slug_it",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="slug_nl",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="slug_pl",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="slug_pt",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="slug_ru",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="slug_sk",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="slug_sl",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="slug_sv",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="slug_tr",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="slug_uk",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="title_de",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="title_el",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="title_en",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="title_es",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="title_fr",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="title_it",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="title_nl",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="title_pl",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="title_pt",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="title_ru",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="title_sk",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="title_sl",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="title_sv",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="title_tr",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="title_uk",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
    ]
