# Generated by Django 5.1 on 2025-03-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_plan_description_de_plan_description_el_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="title",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="plan",
            name="title_de",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="title_el",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="title_en",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="title_es",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="title_fr",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="title_it",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="title_nl",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="title_pl",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="title_pt",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="title_ru",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="title_sk",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="title_sl",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="title_sv",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="title_tr",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="title_uk",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
