# Generated by Django 5.2 on 2025-05-23 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0004_remove_plan_created_on_remove_plan_updated_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.utils.timezone.now
            ),
        ),
    ]
