# Generated by Django 5.1.7 on 2025-03-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0004_alter_plan_price_max_currency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="slug_de",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="slug_el",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="slug_en",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="slug_es",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="slug_fr",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="slug_it",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="slug_nl",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="slug_pl",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="slug_pt",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="slug_ru",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="slug_sk",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="slug_sl",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="slug_sv",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="slug_tr",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="slug_uk",
        ),
        migrations.AlterField(
            model_name="plan",
            name="title",
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="title_de",
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="title_el",
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="title_en",
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="title_es",
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="title_fr",
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="title_it",
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="title_nl",
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="title_pl",
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="title_pt",
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="title_ru",
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="title_sk",
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="title_sl",
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="title_sv",
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="title_tr",
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="title_uk",
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
    ]
