# Generated by Django 5.1 on 2025-03-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0006_remove_plan_description_el_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="slug",
            field=models.SlugField(default="default"),
            preserve_default=False,
        ),
    ]
