# Generated by Django 5.1.4 on 2024-12-21 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socialmedialink",
            name="url_de",
        ),
        migrations.RemoveField(
            model_name="socialmedialink",
            name="url_el",
        ),
        migrations.RemoveField(
            model_name="socialmedialink",
            name="url_en",
        ),
        migrations.RemoveField(
            model_name="socialmedialink",
            name="url_es",
        ),
        migrations.RemoveField(
            model_name="socialmedialink",
            name="url_fr",
        ),
        migrations.RemoveField(
            model_name="socialmedialink",
            name="url_it",
        ),
        migrations.RemoveField(
            model_name="socialmedialink",
            name="url_nl",
        ),
        migrations.RemoveField(
            model_name="socialmedialink",
            name="url_pl",
        ),
        migrations.RemoveField(
            model_name="socialmedialink",
            name="url_pt",
        ),
        migrations.RemoveField(
            model_name="socialmedialink",
            name="url_ru",
        ),
        migrations.RemoveField(
            model_name="socialmedialink",
            name="url_sk",
        ),
        migrations.RemoveField(
            model_name="socialmedialink",
            name="url_sl",
        ),
        migrations.RemoveField(
            model_name="socialmedialink",
            name="url_sv",
        ),
        migrations.RemoveField(
            model_name="socialmedialink",
            name="url_tr",
        ),
        migrations.RemoveField(
            model_name="socialmedialink",
            name="url_uk",
        ),
    ]
