# Generated by Django 5.1.4 on 2025-01-26 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0005_alter_footeritem_languages"),
    ]

    operations = [
        migrations.RenameField(
            model_name="footeritem",
            old_name="languages",
            new_name="rest_languages",
        ),
    ]
