# Generated by Django 5.2 on 2025-05-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0005_alter_footeritem_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footeritem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="footeritem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="footerlink",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="footerlink",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="navbarlink",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="navbarlink",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="socialmedialink",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="socialmedialink",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
