# Generated by Django 5.2 on 2025-06-15 18:30

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_link"),
        ("menus", "0006_alter_footeritem_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footerlink",
            name="link",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.link"
            ),
        ),
        migrations.AlterField(
            model_name="navbarlink",
            name="link",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.link"
            ),
        ),
    ]
