# Generated by Django 5.1 on 2025-03-15 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0007_rename_rest_languages_footeritem_languages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footeritem",
            name="default_language",
        ),
        migrations.RemoveField(
            model_name="footeritem",
            name="languages",
        ),
    ]
