# Generated by Django 5.1.3 on 2024-12-07 22:36

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allow_translation", models.BooleanField(default=False)),
                ("override_translated_fields", models.BooleanField(default=False)),
                (
                    "custom_title",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "custom_title_en",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "custom_title_de",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "custom_title_es",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "custom_title_fr",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "custom_title_el",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "custom_title_eo",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "custom_title_fi",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "custom_title_it",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "custom_title_nl",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "custom_title_nn",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "custom_title_pl",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "custom_title_pt",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "custom_title_pt_br",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "custom_title_ru",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "custom_title_sk",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "custom_title_sl",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "custom_title_sq",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "custom_title_sr",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "custom_title_sv",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "custom_title_tr",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "custom_title_uk",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "external_url",
                    models.URLField(blank=True, max_length=256, null=True),
                ),
                (
                    "django_url_path",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("home", "Home"),
                            ("search", "Search"),
                            ("sitemap", "Sitemap"),
                            ("article_list", "Articles"),
                            ("plan_list", "Plans"),
                            ("account_login", "Sign In"),
                            ("account_signup", "Sign Up"),
                            ("user_dashboard", "Account"),
                            ("faq_list", "FAQs"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "article",
                    auto_prefetch.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articles.article",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
