# Generated by Django 5.1.3 on 2024-11-23 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="link",
            old_name="allow_field_translation",
            new_name="allow_translation",
        ),
    ]
