# Generated by Django 5.1.3 on 2024-11-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="custom_title_de",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="link",
            name="custom_title_en",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="link",
            name="custom_title_es",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
