# Generated by Django 5.1.3 on 2024-12-09 21:18

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_topic"),
        ("links", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="topic",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.topic",
            ),
        ),
    ]
