# Generated by Django 5.1.4 on 2024-12-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="django_url_path",
            field=models.CharField(
                blank=True,
                choices=[
                    ("home", "Home"),
                    ("search", "Search"),
                    ("sitemap", "Sitemap"),
                    ("article_list", "Articles"),
                    ("plan_list", "Plans"),
                    ("account_login", "Sign In"),
                    ("account_signup", "Sign Up"),
                    ("user_dashboard", "Account"),
                    ("faq_list", "FAQs"),
                    ("chat_detail", "Chat"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
