# Generated by Django 5.1.3 on 2024-11-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0002_rename_allow_field_translation_link_allow_translation"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="custom_title_fr",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
