# Generated by Django 5.1.3 on 2024-11-11 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0002_link_custom_title_de_link_custom_title_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="link",
            name="new_tab",
        ),
    ]
