# Generated by Django 5.1.4 on 2024-12-09 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0003_link_topic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="link",
            name="custom_title_eo",
        ),
        migrations.RemoveField(
            model_name="link",
            name="custom_title_fi",
        ),
        migrations.RemoveField(
            model_name="link",
            name="custom_title_nn",
        ),
        migrations.RemoveField(
            model_name="link",
            name="custom_title_sq",
        ),
        migrations.RemoveField(
            model_name="link",
            name="custom_title_sr",
        ),
    ]
