# Generated by Django 5.1.3 on 2024-11-12 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_article_sites"),
        ("links", "0004_alter_link_django_url_path"),
        ("pages", "0001_initial"),
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="link",
            unique_together={("django_url_path", "page", "plan", "article")},
        ),
    ]
