# Generated by Django 5.1.4 on 2024-12-09 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0004_remove_link_custom_title_eo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="link",
            name="custom_title_pt_br",
        ),
    ]
