# Generated by Django 5.1.4 on 2024-12-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0006_remove_link_custom_title_uk"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="custom_title_uk",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
