# Generated by Django 5.2.4 on 2025-07-27 08:31

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="linkedinchannel",
            old_name="token",
            new_name="access_token",
        ),
        migrations.AddField(
            model_name="linkedinchannel",
            name="auth_code",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="linkedinchannel",
            name="auth_state",
            field=models.CharField(default=secrets.token_hex, max_length=128),
        ),
    ]
