# Generated by Django 5.2.4 on 2025-07-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="socialmediapost",
            old_name="scheduled_at",
            new_name="shared_at",
        ),
        migrations.RemoveField(
            model_name="socialmediapost",
            name="sent_at",
        ),
        migrations.RemoveField(
            model_name="socialmediapost",
            name="status",
        ),
        migrations.AddField(
            model_name="socialmediapost",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("de", "German"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("it", "Italian"),
                    ("nl", "Dutch"),
                    ("pt", "Portuguese"),
                ],
                default="en",
                max_length=4,
            ),
        ),
    ]
