# Generated by Django 5.2.4 on 2025-07-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0002_rename_scheduled_at_socialmediapost_shared_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediapost",
            name="is_draft",
            field=models.BooleanField(default=True),
        ),
    ]
