# Generated by Django 5.2.4 on 2025-07-27 20:55

import django.db.models.manager
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0002_rename_token_linkedinchannel_access_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkedinAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("state", models.CharField(default=secrets.token_hex, max_length=128)),
                ("code", models.TextField(blank=True, null=True)),
                ("access_token", models.TextField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("refresh_token", models.TextField(blank=True, null=True)),
                (
                    "refresh_token_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("scope", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name="LinkedinChannel",
        ),
    ]
