# Generated by Django 5.2.4 on 2025-07-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0003_linkedinauth_delete_linkedinchannel"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkedinauth",
            name="author_type",
            field=models.CharField(
                choices=[("person", "Person"), ("organization", "Organization")],
                default="person",
                max_length=32,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="linkedinauth",
            name="name",
            field=models.CharField(default="Dummy name", max_length=64),
            preserve_default=False,
        ),
    ]
