# Generated by Django 5.2.4 on 2025-07-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0003_socialmediapost_is_draft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkedinchannel",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="linkedingroupchannel",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="mastodonchannel",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="twitterchannel",
            name="name",
            field=models.CharField(max_length=128),
        ),
    ]
