# Generated by Django 5.2.4 on 2025-07-27 20:58

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0004_linkedinauth_author_type_linkedinauth_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="linkedinauth",
            name="author_type",
        ),
        migrations.RemoveField(
            model_name="linkedinauth",
            name="name",
        ),
        migrations.CreateModel(
            name="LinkedinChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64)),
                (
                    "author_type",
                    models.CharField(
                        choices=[
                            ("person", "Person"),
                            ("organization", "Organization"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "auth",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="socialmedia.linkedinauth",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
