# Generated by Django 5.2.4 on 2025-07-30 04:02

import one.db
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0004_alter_linkedinchannel_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="linkedingroupchannel",
            name="language",
        ),
        migrations.RemoveField(
            model_name="mastodonchannel",
            name="language",
        ),
        migrations.RemoveField(
            model_name="twitterchannel",
            name="language",
        ),
        migrations.AddField(
            model_name="linkedinchannel",
            name="languages",
            field=one.db.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("en", "English"),
                        ("de", "German"),
                        ("es", "Spanish"),
                        ("fr", "French"),
                        ("it", "Italian"),
                        ("nl", "Dutch"),
                        ("pt", "Portuguese"),
                    ],
                    max_length=8,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="linkedingroupchannel",
            name="languages",
            field=one.db.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("en", "English"),
                        ("de", "German"),
                        ("es", "Spanish"),
                        ("fr", "French"),
                        ("it", "Italian"),
                        ("nl", "Dutch"),
                        ("pt", "Portuguese"),
                    ],
                    max_length=8,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="mastodonchannel",
            name="languages",
            field=one.db.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("en", "English"),
                        ("de", "German"),
                        ("es", "Spanish"),
                        ("fr", "French"),
                        ("it", "Italian"),
                        ("nl", "Dutch"),
                        ("pt", "Portuguese"),
                    ],
                    max_length=8,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="twitterchannel",
            name="languages",
            field=one.db.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("en", "English"),
                        ("de", "German"),
                        ("es", "Spanish"),
                        ("fr", "French"),
                        ("it", "Italian"),
                        ("nl", "Dutch"),
                        ("pt", "Portuguese"),
                    ],
                    max_length=8,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
