# Generated by Django 5.2.4 on 2025-07-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0005_remove_linkedinauth_author_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkedinauth",
            name="access_token",
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="linkedinauth",
            name="refresh_token",
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
