# Generated by Django 5.2.4 on 2025-07-27 21:44

import one.db
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0006_alter_linkedinauth_access_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkedinchannel",
            name="author_id",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="linkedinchannel",
            name="post_english",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="linkedinchannel",
            name="post_jobs",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="linkedinchannel",
            name="topics",
            field=one.db.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("django", "Django"),
                        ("htmx", "htmx"),
                        ("alpinejs", "AlpineJS"),
                        ("devops", "DevOps"),
                        ("python", "Python"),
                        ("linux", "Linux"),
                        ("latex", "LaTex"),
                        ("matlab", "Matlab"),
                        ("siemens", "Siemens"),
                        ("excel", "Excel"),
                        ("maths", "Maths"),
                        ("mechanics", "Mechanics"),
                        ("english", "English"),
                        ("electronics", "Electronics"),
                        ("calendar", "Calendars"),
                        ("one", "One project"),
                    ],
                    max_length=16,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
