# Generated by Django 5.2.4 on 2025-07-30 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0006_telegramchannel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socialmediapost",
            name="image_li_urn",
        ),
    ]
