# Generated by Django 5.2.4 on 2025-08-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0009_alter_linkedinchannel_topics_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="linkedinchannel",
            name="language",
        ),
        migrations.AddField(
            model_name="socialmediapost",
            name="share_in_linkedin",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="socialmediapost",
            name="share_in_linkedin_groups",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="socialmediapost",
            name="share_in_mastodon",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="socialmediapost",
            name="share_in_telegram",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="socialmediapost",
            name="share_in_twitter",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="socialmediapost",
            name="shared_in_linkedin",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="socialmediapost",
            name="shared_in_linkedin_groups",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="socialmediapost",
            name="shared_in_mastodon",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="socialmediapost",
            name="shared_in_telegram",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="socialmediapost",
            name="shared_in_twitter",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
