# Generated by Django 5.2.4 on 2025-08-01 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("socialmedia", "0011_postedsocialmediapost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postedsocialmediapost",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={
                    "model__in": [
                        "linkedinchannel",
                        "linkedingroupchannel",
                        "twitterchannel",
                    ]
                },
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
