# Generated by Django 5.2.4 on 2025-08-02 10:08

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("socialmedia", "0012_alter_postedsocialmediapost_content_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostedSocialMediaContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("channel_id", models.PositiveBigIntegerField()),
                ("post_id", models.PositiveBigIntegerField()),
                ("response_json", models.JSONField()),
                (
                    "channel_type",
                    models.ForeignKey(
                        limit_choices_to={
                            "model__in": [
                                "linkedinchannel",
                                "linkedingroupchannel",
                                "twitterchannel",
                                "mastodonchannel",
                                "telegramchannel",
                            ]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_posted_contents",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "post_type",
                    models.ForeignKey(
                        limit_choices_to={
                            "app_in": ["quiz", "socialmedia"],
                            "model__in": ["socialmediapost", "question"],
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_posted_contents",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name="PostedSocialMediaPost",
        ),
    ]
