# Generated by Django 5.2.4 on 2025-08-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0013_postedsocialmediacontent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postedsocialmediacontent",
            name="response_headers",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="postedsocialmediacontent",
            name="respose_status",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
