# Generated by Django 5.2.4 on 2025-08-02 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("socialmedia", "0014_postedsocialmediacontent_response_headers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postedsocialmediacontent",
            name="post_type",
            field=models.ForeignKey(
                limit_choices_to={
                    "app_label__in": ["quiz", "socialmedia"],
                    "model__in": ["socialmediapost", "question"],
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_posted_contents",
                to="contenttypes.contenttype",
            ),
        ),
    ]
