# Generated by Django 4.2.5 on 2023-09-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RockenJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recruiter", models.CharField(max_length=64, null=True)),
                ("vacancy_url", models.CharField(max_length=128)),
                ("vacancy_id", models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="RockenJobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
