# Generated by Django 4.2.5 on 2023-09-13 19:46

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=32)),
                ("last_name", models.CharField(max_length=32)),
                (
                    "phone_country",
                    models.CharField(
                        choices=[("es", "Spain"), ("de", "Germany")], max_length=5
                    ),
                ),
                ("phone_number", models.PositiveIntegerField()),
                (
                    "actual_position",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("link", models.URLField(blank=True, max_length=64, null=True)),
                (
                    "cv",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to="jobs",
                    ),
                ),
                (
                    "certificates",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to="jobs",
                    ),
                ),
                (
                    "extra_doc",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to="jobs",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="rockenjobapplication",
            name="applied",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rockenjobapplication",
            name="job",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobs.rockenjob",
            ),
        ),
        migrations.CreateModel(
            name="RockenJobSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=128)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.profile"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="rockenjob",
            name="profile",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobs.profile",
            ),
        ),
        migrations.AddField(
            model_name="rockenjobapplication",
            name="profile",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobs.profile",
            ),
        ),
    ]
