# Generated by Django 4.2.5 on 2023-09-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0005_alter_rockenjob_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.CharField(default="ramiboutas@protonmail.com", max_length=64),
            preserve_default=False,
        ),
    ]
