# Generated by Django 4.2.5 on 2023-09-13 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0006_profile_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rockenjobapplication",
            name="job",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobs.rockenjob",
            ),
        ),
        migrations.AlterField(
            model_name="rockenjobapplication",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobs.profile",
            ),
        ),
    ]
