# Generated by Django 4.2.5 on 2023-09-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0007_alter_rockenjobapplication_job_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.PositiveBigIntegerField(),
        ),
    ]
