# Generated by Django 4.2.5 on 2023-09-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0008_alter_profile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.BigIntegerField(),
        ),
    ]
