# Generated by Django 5.1.4 on 2024-12-24 18:17

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_alter_request_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accuracy_radius", models.SmallIntegerField(null=True)),
                ("city", models.CharField(max_length=64, null=True)),
                ("continent_code", models.CharField(max_length=64, null=True)),
                ("continent_name", models.CharField(max_length=64, null=True)),
                ("country_code", models.CharField(max_length=64, null=True)),
                ("country_name", models.CharField(max_length=64, null=True)),
                ("is_in_european_union", models.BooleanField(null=True)),
                ("latitude", models.FloatField(null=True)),
                ("longitude", models.FloatField(null=True)),
                ("metro_code", models.SmallIntegerField(null=True)),
                ("postal_code", models.CharField(max_length=64, null=True)),
                ("region_code", models.CharField(max_length=64, null=True)),
                ("region_name", models.CharField(max_length=64, null=True)),
                ("time_zone", models.CharField(max_length=64, null=True)),
                ("dma_code", models.SmallIntegerField(null=True)),
                ("region", models.CharField(max_length=32, null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="client",
            name="geoinfo",
            field=auto_prefetch.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.geoinfo",
            ),
        ),
    ]
