# Generated by Django 5.1.4 on 2024-12-25 05:55

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_geoinfo_client_geoinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="geoinfo",
            field=auto_prefetch.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clients.geoinfo",
            ),
        ),
    ]
