# Generated by Django 5.1.4 on 2024-12-26 05:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0010_autoblockpath"),
    ]

    operations = [
        migrations.AddField(
            model_name="autoblockpath",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
