# Generated by Django 5.1.4 on 2024-12-26 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0011_autoblockpath_created_on"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AutoBlockPath",
            new_name="SpamPath",
        ),
    ]
