# Generated by Django 5.1.4 on 2024-12-29 01:52

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0013_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="path_obj",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.path",
            ),
        ),
    ]
