# Generated by Django 5.1.4 on 2024-12-29 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0014_request_path_obj"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="request",
            name="path",
        ),
    ]
