# Generated by Django 5.1.4 on 2025-01-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0020_pathredirect"),
    ]

    operations = [
        migrations.AddField(
            model_name="pathredirect",
            name="for_users_only",
            field=models.BooleanField(default=False),
        ),
    ]
