# Generated by Django 5.1.4 on 2025-01-08 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0022_remove_pathredirect_for_users_only_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pathredirect",
            old_name="applicable_when",
            new_name="applicable",
        ),
    ]
