# Generated by Django 5.1.4 on 2025-01-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0023_rename_applicable_when_pathredirect_applicable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pathredirect",
            name="applicable",
            field=models.CharField(
                choices=[
                    ("user", "👤 For logged users"),
                    ("no_user", "🕵🏻 For anonymous users"),
                    ("always", "🔄 Always"),
                ],
                default="always",
                max_length=16,
            ),
        ),
    ]
