# Generated by Django 5.1.4 on 2025-03-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0025_alter_request_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="user_agent",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="path",
            name="name",
            field=models.CharField(db_index=True, max_length=512, unique=True),
        ),
    ]
