# Generated by Django 5.1 on 2025-04-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0028_alter_client_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="possible_bot",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(
                        models.Q(
                            ("user_agent__contains", "bot"),
                            ("user_agent__contains", "Bot"),
                            _connector="OR",
                        ),
                        then=models.Value(True),
                    ),
                    default=models.Value(False),
                ),
                output_field=models.BooleanField(db_default=False),
            ),
        ),
    ]
