# Generated by Django 5.2 on 2025-04-03 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0029_client_possible_bot"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="possible_bot",
            new_name="is_bot",
        ),
    ]
