# Generated by Django 5.2 on 2025-04-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0030_rename_possible_bot_client_is_bot"),
        ("sites", "0035_site_keywords_de_site_keywords_en_site_keywords_es_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pathredirect",
            name="site",
        ),
        migrations.AddField(
            model_name="pathredirect",
            name="sites",
            field=models.ManyToManyField(to="sites.site"),
        ),
    ]
