# Generated by Django 5.2 on 2025-04-03 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0031_remove_pathredirect_site_pathredirect_sites"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="request",
            name="get",
        ),
        migrations.RemoveField(
            model_name="request",
            name="post",
        ),
    ]
