# Generated by Django 5.2 on 2025-04-03 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0032_remove_request_get_remove_request_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="is_bot",
        ),
    ]
