# Generated by Django 5.2 on 2025-04-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0034_client_is_bot"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="post",
            field=models.TextField(null=True),
        ),
    ]
