# Generated by Django 5.2 on 2025-04-14 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0035_request_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="dark_theme",
        ),
    ]
