# Generated by Django 5.2 on 2025-04-17 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0036_remove_client_dark_theme"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pathredirect",
            name="applicable",
        ),
    ]
