# Generated by Django 5.2 on 2025-04-24 20:17

import auto_prefetch
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0037_remove_pathredirect_applicable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="path",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clients.path"
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="ref",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="request",
            name="time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="time"
            ),
        ),
    ]
