# Generated by Django 5.2 on 2025-04-24 20:31

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0038_alter_request_path_alter_request_ref_and_more"),
        ("sites", "0041_site_footer_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="site",
            field=auto_prefetch.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="sites.site"
            ),
        ),
    ]
