# Generated by Django 5.2 on 2025-04-24 20:47

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0039_request_site"),
        ("sites", "0041_site_footer_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="site",
        ),
        migrations.AlterField(
            model_name="request",
            name="site",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sites.site"
            ),
        ),
    ]
