# Generated by Django 5.1.4 on 2024-12-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="body_de",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="body_el",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="body_en",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="body_es",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="body_fr",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="body_it",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="body_nl",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="body_pl",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="body_pt",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="body_ru",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="body_sk",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="body_sl",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="body_sv",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="body_tr",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="body_uk",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="slug_de",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="slug_el",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="slug_en",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="slug_es",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="slug_fr",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="slug_it",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="slug_nl",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="slug_pl",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="slug_pt",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="slug_ru",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="slug_sk",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="slug_sl",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="slug_sv",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="slug_tr",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="slug_uk",
            field=models.SlugField(
                editable=False, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="title_de",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="title_el",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="title_en",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="title_es",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="title_fr",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="title_it",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="title_nl",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="title_pl",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="title_pt",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="title_ru",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="title_sk",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="title_sl",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="title_sv",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="title_tr",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="title_uk",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
    ]
