# Generated by Django 5.2 on 2025-05-21 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_animation_created_on_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactmessage",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="searchterm",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="animation",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="animation",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="contactmessage",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="searchterm",
            name="updated_on",
        ),
        migrations.AddField(
            model_name="animation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848231, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="animation",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848323, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848323, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="searchterm",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 5, 21, 19, 18, 53, 848323, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
