# Generated by Django 5.2 on 2025-07-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_link_url_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="topic",
            field=models.CharField(
                blank=True,
                choices=[
                    ("django", "Django"),
                    ("htmx", "htmx"),
                    ("alpinejs", "AlpineJS"),
                    ("devops", "DevOps"),
                    ("python", "Python"),
                    ("linux", "Linux"),
                    ("latex", "LaTex"),
                    ("matlab", "Matlab"),
                    ("siemens", "Siemens"),
                    ("excel", "Excel"),
                    ("maths", "Maths"),
                    ("mechanics", "Mechanics"),
                    ("english", "English"),
                    ("electronics", "Electronics"),
                    ("calendar", "Calendars"),
                    ("one", "One project"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
