# Generated by Django 5.1.4 on 2024-12-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_rename_request_get_traffic_get_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="traffic",
            name="ip",
            field=models.GenericIPAddressField(null=True, verbose_name="ip address"),
        ),
    ]
