# Generated by Django 5.2 on 2025-05-23 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_rename_created_on_contactmessage_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="animation",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="searchterm",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.utils.timezone.now
            ),
        ),
    ]
