# Generated by Django 5.2 on 2025-07-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_alter_link_url_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="url_path",
            field=models.CharField(
                blank=True,
                choices=[
                    ("home", "Home"),
                    ("search", "Search"),
                    ("sitemap", "Sitemap"),
                    ("contact", "Contact"),
                    ("article_list", "Articles"),
                    ("plan_list", "Plans"),
                    ("account_login", "Sign In"),
                    ("account_signup", "Sign Up"),
                    ("user_dashboard", "Account"),
                    ("faq_list", "FAQs"),
                    ("quiz_list", "English Quizzes"),
                    ("privacy", "Privacy Policy"),
                    ("terms", "Terms and Conditions"),
                    ("impress", "Impress"),
                    ("candidate_create", "Create candidate profile"),
                    ("candidate_create_or_detail", "Candidate profile"),
                    ("candidate_dashboard", "Candidate dashboard"),
                    ("job_list", "Jobs"),
                    ("company_list", "Companies"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
