# Generated by Django 5.2 on 2025-06-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="custom_title_de",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="link",
            name="custom_title_en",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="link",
            name="custom_title_es",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="link",
            name="custom_title_fr",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="link",
            name="custom_title_it",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="link",
            name="custom_title_nl",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="link",
            name="custom_title_pt",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
