# Generated by Django 5.1 on 2025-03-15 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_rename_rest_languages_topic_languages"),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name="topic",
        #     old_name="default_language",
        #     new_name="language",
        # ),
    ]
