# Generated by Django 5.1.7 on 2025-03-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0013_remove_article_language"),
        ("base", "0012_rename_default_language_topic_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="article_folders",
            field=models.ManyToManyField(blank=True, to="articles.articleparentfolder"),
        ),
    ]
