# Generated by Django 5.1.7 on 2025-03-16 13:08

import django.db.models.manager
import one.base.utils.db
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_rename_default_language_topic_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="DummyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                (
                    "languages",
                    one.base.utils.db.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("en", "English"),
                                ("de", "German"),
                                ("es", "Spanish"),
                                ("fr", "French"),
                                ("el", "Greek"),
                                ("it", "Italian"),
                                ("nl", "Dutch"),
                                ("pl", "Polish"),
                                ("pt", "Portuguese"),
                                ("ru", "Russian"),
                                ("sk", "Slovak"),
                                ("sl", "Slovenian"),
                                ("sv", "Swedish"),
                                ("tr", "Turkish"),
                                ("uk", "Ukrainian"),
                            ],
                            max_length=8,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
