# Generated by Django 5.2.4 on 2025-07-24 17:48

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_alter_link_url_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="CSPReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blocked_uri",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                ("column_number", models.IntegerField(blank=True, null=True)),
                ("disposition", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "document_uri",
                    models.URLField(blank=True, max_length=2048, null=True),
                ),
                (
                    "effective_directive",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("line_number", models.IntegerField(blank=True, null=True)),
                ("original_policy", models.TextField(blank=True, null=True)),
                ("referrer", models.URLField(blank=True, max_length=2048, null=True)),
                (
                    "source_file",
                    models.URLField(blank=True, max_length=2048, null=True),
                ),
                ("status_code", models.IntegerField(blank=True, null=True)),
                (
                    "violated_directive",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
