# Generated by Django 5.1.7 on 2025-03-20 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_topic_article_folders"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="article_folders",
        ),
    ]
