# Generated by Django 5.2.4 on 2025-07-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_cspreport"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cspreport",
            constraint=models.UniqueConstraint(
                fields=(
                    "violated_directive",
                    "effective_directive",
                    "blocked_uri",
                    "document_uri",
                    "source_file",
                    "line_number",
                    "column_number",
                ),
                name="unique_csp_violation",
            ),
        ),
    ]
