# Generated by Django 5.2.4 on 2025-08-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_alter_link_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="topic",
            field=models.CharField(
                blank=True,
                choices=[
                    ("one", "One project"),
                    ("django", "Django"),
                    ("htmx", "htmx"),
                    ("alpinejs", "AlpineJS"),
                    ("devops", "DevOps"),
                    ("python", "Python"),
                    ("javascript", "JavasSript"),
                    ("linux", "Linux"),
                    ("latex", "LaTex"),
                    ("matlab", "Matlab"),
                    ("siemens", "Siemens"),
                    ("excel", "Excel"),
                    ("postgres", "PostgreSQL"),
                    ("maths", "Maths"),
                    ("mechanics", "Mechanics"),
                    ("english", "English"),
                    ("electronics", "Electronics"),
                    ("calendar", "Calendars"),
                    ("career", "Career"),
                    ("psychology", "Psychology"),
                    ("philosophy", "Philosophy"),
                    ("finance", "Finance"),
                    ("marketing", "Marketing"),
                    ("entrepreneurship", "Entrepreneurship"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
