# Generated by Django 5.1 on 2025-03-31 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0017_alter_searchterm_client_alter_searchterm_site_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="searchterm",
            name="user",
        ),
    ]
