# Generated by Django 5.2 on 2025-04-14 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0019_animation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Topic",
        ),
    ]
