# Generated by Django 5.2 on 2025-04-20 09:34

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0021_contactmessage"),
        ("clients", "0037_remove_pathredirect_applicable"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="client",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clients.client",
            ),
        ),
    ]
