# Generated by Django 5.2 on 2025-04-20 09:40

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0022_contactmessage_client"),
        ("sites", "0038_rename_topics_new_site_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="site",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sites.site",
            ),
        ),
    ]
