# Generated by Django 5.2 on 2025-04-20 18:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0023_contactmessage_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
